<?php
// English United States - en_US
$lang = [
    // Meta
    'meta_title' => 'OriginalisDoc - Documentation with QR Validation for Every Sector',
    'meta_description' => 'Digital document validation and issuance solutions for educational institutions, professionals, events, businesses, cooperatives, and mutuals.',

    // Header/Navigation
    'nav_inicio' => 'Home',
    'nav_categorias' => 'Categories',
    'nav_beneficios' => 'Benefits',
    'nav_faq' => 'FAQ',
    'nav_validar' => 'Validate',
    'nav_demo' => 'Request Demo',

    // Hero Section
    'hero_badge' => 'Trusted by institutions and professionals globally',
    'hero_title' => 'Documentation with QR Validation<br>for Every Sector',
    'hero_subtitle' => 'Digital document validation and issuance solutions for educational institutions, independent professionals, event organizers, businesses, cooperatives, and mutuals. Tamper-proof QR validation and customized portal.',
    'hero_cta_primary' => 'Explore Solutions',
    'hero_cta_secondary' => 'Validate Document',

    // Categories Section
    'cat_title' => 'Industry Solutions',
    'cat_subtitle' => 'Choose your sector to discover the perfect solution designed for your specific needs',

    'cat_academico' => 'Academic',
    'cat_academico_1' => 'Educational Institutions',
    'cat_academico_2' => 'Training Centers',
    'cat_academico_3' => 'Independent Instructors',
    'cat_academico_cta' => 'View Solution →',

    'cat_profesional' => 'Professional',
    'cat_profesional_1' => 'Health and Wellness',
    'cat_profesional_2' => 'Engineering and Architecture',
    'cat_profesional_3' => 'All Professionals',

    'cat_eventos' => 'Events',
    'cat_eventos_1' => 'Conferences and Conventions',
    'cat_eventos_2' => 'Festivals and Concerts',
    'cat_eventos_3' => 'Access Control',

    'cat_empresarial' => 'Business',
    'cat_empresarial_1' => 'Warranties and Authenticity',
    'cat_empresarial_2' => 'Quality Certificates',
    'cat_empresarial_3' => 'Validated Receipts',

    'cat_cooperativas' => 'Cooperatives',
    'cat_cooperativas_1' => 'Member Credentials',
    'cat_cooperativas_2' => 'Participation Certificates',
    'cat_cooperativas_3' => 'Activity Statements',

    'cat_mutuales' => 'Mutuals',
    'cat_mutuales_1' => 'Member Credentials',
    'cat_mutuales_2' => 'Service Receipts',
    'cat_mutuales_3' => 'Benefits Cards',

    'cat_proximamente' => 'Coming Soon',
    'cat_footer' => 'More categories coming soon.',
    'cat_footer_link' => 'Contact Us',
    'cat_footer_text' => 'if your sector is not listed.',

    // Main Services
    'servicios_title' => 'Our Main Services',
    'servicios_subtitle' => 'Essential functionalities that all our organizations enjoy, regardless of their sector',

    'serv_antifraude' => 'Total Anti-Fraud Security',
    'serv_antifraude_desc' => 'Unique QR codes that are impossible to forge, guaranteeing the authenticity of each document.',

    'serv_portal' => '24/7 Portal',
    'serv_portal_desc' => 'Permanent access for students, clients, members, or employees from any device.',

    'serv_impresion' => 'Premium Printing',
    'serv_impresion_desc' => 'High-quality physical documents with holograms and lamination, delivered to your door.',

    'serv_branding' => 'Custom Branding',
    'serv_branding_desc' => 'Portal and documents with your logo, colors, and unique institutional design.',

    'serv_emision' => 'Mass Issuance',
    'serv_emision_desc' => 'Generate hundreds of documents automatically with instant notifications.',

    'serv_validacion' => 'Validation Portal',
    'serv_validacion_desc' => 'Anyone can verify the authenticity of your documents instantly.',

    // Success Cases
    'casos_title' => 'Success Stories',
    'casos_subtitle' => 'Institutions and professionals who trust OriginalisDoc',

    'caso_sajur_org' => 'Argentine Society of Restorative Justice',
    'caso_sajur_tipo' => 'Specialized educational organization',
    'caso_sajur_texto' => '"We went from manually processing each certificate to issuing dozens in minutes. Our students value being able to access their complete trajectory 24/7, and employers trust the QR validation. Administrative time savings were 90%."',


    'caso_liberte_org' => 'Liberté Workers Cooperative',
    'caso_liberte_tipo' => 'Professional training and education',
    'caso_liberte_texto' => '"Implementation was instantaneous. Within less than 24 hours, we were already issuing certificates with our brand. The customized portal projects a professional image that our students share with pride. The premium printing option is the perfect finishing touch."',


    'caso_nutricion_org' => 'Prof. Maria Gonzalez',
    'caso_nutricion_tipo' => 'Independent professional nutritionist',
    'caso_nutricion_texto' => '"My nutritional plans now have a QR code that my patients can validate. This significantly increased trust and reduced queries about authenticity. Additionally, the premium physical delivery service is perfect for those who want to have them printed."',


    'caso_empresa_org' => 'TechVision S.A.',
    'caso_empresa_tipo' => 'Technology company',
    'caso_empresa_texto' => '"We use OriginalisDoc to issue warranties for our products with verifiable QR codes. Our customers can validate authenticity instantly and access all technical information. The reduction in falsification complaints was 95%."',


    // FAQ
    'faq_title' => 'Frequently Asked Questions',
    'faq_subtitle' => 'Everything you need to know about OriginalisDoc',

    'faq_1_q' => 'How long does it take to implement OriginalisDoc?',
    'faq_1_a' => 'Less than 24 hours. You just need to configure your branding (logo and colors), upload your data, and start issuing. We include step-by-step guided onboarding.',

    'faq_2_q' => 'Do digital documents have the same validity as physical ones?',
    'faq_2_a' => 'Yes. Digital documents have full legal validity. Additionally, our QR system allows instant verification of authenticity, something impossible with traditional physical documents.',

    'faq_3_q' => 'What happens if I need a physical version of the document?',
    'faq_3_a' => 'We offer a premium HD printing service with security holograms and lamination, sent by tracked mail throughout Argentina. You can request it directly from your portal and receive shipping tracking.',

    'faq_4_q' => 'How does QR validation work?',
    'faq_4_a' => 'Each document includes a unique QR code that redirects to a customized validation portal with your branding. All document information and its complete trajectory are shown there. It is impossible to forge or alter.',

    'faq_5_q' => 'Can I customize the design of documents?',
    'faq_5_a' => 'Yes, 100%. Each institution or professional has their portal completely customized with their logo, colors and brand design. Documents reflect your unique visual identity.',

    'faq_6_q' => 'Do I need technical knowledge to use the platform?',
    'faq_6_a' => 'No. The platform is designed to be extremely intuitive. If you can navigate the internet, you can manage OriginalisDoc without problems. Additionally, we offer complete technical support.',

    'faq_7_q' => 'What happens to my data? Is it secure?',
    'faq_7_a' => 'Absolute security. We use banking-level encryption, automatic daily backups, and comply with personal data protection regulations. Your data is more secure than in a physical file.',

    // Validate Document Section
    'validar_title' => 'Validate a Document',
    'validar_subtitle' => 'Enter the validation code that appears on the document (format: VALID-XXXXXXXXXXXX)',
    'validar_placeholder' => 'VALID-XXXXXXXXXXXX',
    'validar_btn' => 'Validate Now',
    'validar_ejemplo' => 'Example: VALID-A1B2C3D4E5F6',

    // Contact Section
    'contacto_title' => 'Start Issuing Professional Documents Today',
    'contacto_subtitle' => 'Contact us for a personalized demonstration and discover how OriginalisDoc can transform your document management.',


    // Footer
    'footer_descripcion' => 'The definitive platform for secure digital and physical documents with QR validation.',
    'footer_enlaces' => 'Quick Links',
    'footer_caracteristicas' => 'Features',
    'footer_contacto' => 'Contact',
    'footer_seguridad' => 'Enterprise-Level Technology and Security',
    'footer_copyright' => '© 2025 OriginalisDoc. All rights reserved.',
    'footer_terminos' => 'Terms of Service',
    'footer_privacidad' => 'Privacy Policy',

    // Security Badges
    'badge_ssl' => 'SSL',
    'badge_ssl_desc' => '256-bit Encryption',
    'badge_https' => 'HTTPS',
    'badge_https_desc' => 'Secure Connection',
    'badge_privacidad' => 'Privacy',
    'badge_privacidad_desc' => 'Protected Data',
    'badge_backup' => 'Backup',
    'badge_backup_desc' => 'Automatic Daily',
    'badge_uptime' => 'Uptime 99.9%',
    'badge_uptime_desc' => 'Availability',
    'badge_soporte' => 'Support',
    'badge_soporte_desc' => '24/7 Technical',

    // Hero Statistics
    'stat_uptime' => 'Availability',
    'stat_documentos' => 'Documents issued',
    'stat_acceso' => 'Access available',
    'stat_ahorro' => 'Administrative cost savings',

    // Contact Social Proof
    'social_confianza' => 'Institutions and professionals who already trust OriginalisDoc',
    'social_mas' => '+ more organizations and professionals',

    // Contact Benefits
    'benefit_demo' => 'Free demo without commitment',
    'benefit_demo_desc' => 'Try all functions',
    'benefit_implementacion' => 'Implementation in 24hrs',
    'benefit_implementacion_desc' => 'Start issuing tomorrow',
    'benefit_soporte' => 'Included technical support',
    'benefit_soporte_desc' => 'Complete assistance',

    // Contact CTA
    'contacto_cta_btn' => 'Request Free Demo',
    'contacto_cta_email' => 'Or write to us at',

    // Footer - Quick links
    'footer_link_beneficios' => 'Benefits',
    'footer_link_como' => 'How It Works',
    'footer_link_validar' => 'Validate Document',
    'footer_link_demo' => 'Request Demo',

    // Footer - Features
    'footer_feat_qr' => 'QR Validation',
    'footer_feat_portal' => '24/7 Portal',
    'footer_feat_impresion' => 'Premium Printing',
    'footer_feat_personalizable' => '100% Customizable',

    // Footer - Contact
    'footer_horario' => 'Monday - Friday: 9:00 AM - 6:00 PM',

    // Privacy Policy Page
    'privacidad_title' => 'Privacy Policy',
    'privacidad_updated' => 'Last updated',

    // Terms of Service - Content
    'terminos_seccion1_titulo' => '1. Acceptance of Terms',
    'terminos_seccion1_p1' => 'By accessing and using the OriginalisDoc platform ("the Service"), you agree to be legally bound by these Terms of Service. If you do not agree to these terms, do not use the Service.',
    'terminos_seccion1_p2' => 'OriginalisDoc reserves the right to modify these terms at any time. Changes will take effect immediately after their publication on the website.',

    'terminos_seccion2_titulo' => '2. Service Description',
    'terminos_seccion2_p1' => 'OriginalisDoc is a platform that allows educational institutions, independent professionals, event organizers, businesses, cooperatives, and mutuals to issue, manage, and validate digital documents with QR verification codes.',
    'terminos_seccion2_p2' => 'Services include, but are not limited to:',
    'terminos_seccion2_li1' => 'Custom digital document issuance',
    'terminos_seccion2_li2' => 'Customized portal for each institution/professional',
    'terminos_seccion2_li3' => 'Validation system with unique QR codes',
    'terminos_seccion2_li4' => 'Secure cloud storage',
    'terminos_seccion2_li5' => 'Premium printing option for physical documents',
    'terminos_seccion2_li6' => 'Mass document issuance',

    'terminos_seccion3_titulo' => '3. User Registration and Account',
    'terminos_seccion3_p1' => 'To use the Service, you must create an account providing accurate, complete, and current information. You are responsible for:',
    'terminos_seccion3_li1' => 'Maintaining the confidentiality of your password and access credentials',
    'terminos_seccion3_li2' => 'All activities that occur under your account',
    'terminos_seccion3_li3' => 'Promptly notifying of any unauthorized use of your account',
    'terminos_seccion3_li4' => 'Providing truthful data about your institution or organization',
    'terminos_seccion3_p2' => 'OriginalisDoc reserves the right to suspend or cancel accounts that violate these terms or provide false information.',

    'terminos_seccion4_titulo' => '4. Permitted Use',
    'terminos_seccion4_p1' => 'The Service may only be used for legitimate purposes and in accordance with these Terms. It is not permitted to use OriginalisDoc for fraudulent, illegal, or rights-infringing activities.',

    'terminos_seccion5_titulo' => '5. Intellectual Property',
    'terminos_seccion5_p1' => 'All content, design, logos, and technology of OriginalisDoc are exclusive property of the platform and are protected by intellectual property laws.',

    'terminos_seccion6_titulo' => '6. Limitation of Liability',
    'terminos_seccion6_p1' => 'OriginalisDoc will not be liable for indirect, incidental, or consequential damages arising from the use or inability to use the Service.',

    'terminos_seccion7_titulo' => '7. Contact',
    'terminos_seccion7_p1' => 'For inquiries about these Terms of Service, contact us at:',

    // Privacy Policy - Content
    'privacidad_intro_titulo' => 'Introduction',
    'privacidad_intro_p1' => 'At OriginalisDoc, the privacy and security of your data is our top priority. This Privacy Policy describes how we collect, use, store, and protect your personal information when you use our services.',
    'privacidad_intro_p2' => 'By using OriginalisDoc, you accept the practices described in this policy. If you do not agree, do not use our services.',

    'privacidad_seccion1_titulo' => '1. Information We Collect',
    'privacidad_seccion1_sub1_titulo' => '1.1 Account Information',
    'privacidad_seccion1_sub1_p1' => 'When you create an account, we collect:',
    'privacidad_seccion1_sub1_li1' => 'Full name and contact information (email, phone)',
    'privacidad_seccion1_sub1_li2' => 'Name of the institution, organization or independent professional',
    'privacidad_seccion1_sub1_li3' => 'Physical and tax address',
    'privacidad_seccion1_sub1_li4' => 'Billing and payment information',
    'privacidad_seccion1_sub1_li5' => 'Access credentials (encrypted username/password)',
    'privacidad_seccion1_sub2_titulo' => '1.2 Document and Beneficiary Data',
    'privacidad_seccion1_sub2_p1' => 'When issuing documents, we collect data from beneficiaries (students, clients, employees, members, etc.):',
    'privacidad_seccion1_sub2_li1' => 'Full name and identification number (ID, SSN, etc.)',
    'privacidad_seccion1_sub2_li2' => 'Email and phone (for notifications)',
    'privacidad_seccion1_sub2_li3' => 'Academic, professional or employment data related to the issued document',
    'privacidad_seccion1_sub2_li4' => 'Photography (optional, if included in the document)',
    'privacidad_seccion1_sub3_titulo' => '1.3 Usage and Technical Data',
    'privacidad_seccion1_sub3_li1' => 'IP address, browser, operating system',
    'privacidad_seccion1_sub3_li2' => 'Pages visited, session time, clicks',
    'privacidad_seccion1_sub3_li3' => 'Document validation logs (who validated, when, from where)',
    'privacidad_seccion1_sub3_li4' => 'Portal usage metrics (downloads, accesses, etc.)',

    'privacidad_seccion2_titulo' => '2. How We Use Your Information',
    'privacidad_seccion2_p1' => 'We use the collected data for:',
    'privacidad_seccion2_li1_strong' => 'Provide the Service:',
    'privacidad_seccion2_li1_texto' => 'Generate, store and manage digital documents',
    'privacidad_seccion2_li2_strong' => 'Validation:',
    'privacidad_seccion2_li2_texto' => 'Verify document authenticity using QR codes',
    'privacidad_seccion2_li3_strong' => 'Notifications:',
    'privacidad_seccion2_li3_texto' => 'Send emails about issued documents, service updates',
    'privacidad_seccion2_li4_strong' => 'Billing:',
    'privacidad_seccion2_li4_texto' => 'Process payments and issue invoices',
    'privacidad_seccion2_li5_strong' => 'Service Improvement:',
    'privacidad_seccion2_li5_texto' => 'Analyze usage metrics to optimize functionalities',
    'privacidad_seccion2_li6_strong' => 'Technical Support:',
    'privacidad_seccion2_li6_texto' => 'Resolve queries and technical problems',
    'privacidad_seccion2_li7_strong' => 'Legal Compliance:',
    'privacidad_seccion2_li7_texto' => 'Comply with legal and regulatory obligations',

    'privacidad_seccion3_titulo' => '3. Sharing Information with Third Parties',
    'privacidad_seccion3_p1_strong' => 'We do not sell or rent',
    'privacidad_seccion3_p1_normal' => 'your personal data to third parties. We only share information in these limited cases:',
    'privacidad_seccion3_sub1_titulo' => '3.1 Service Providers',
    'privacidad_seccion3_sub1_p1' => 'We work with trusted providers who help us operate the Service:',
    'privacidad_seccion3_sub1_li1' => 'Hosting and cloud storage (secure servers)',
    'privacidad_seccion3_sub1_li2' => 'Payment processors (with PCI-DSS certification)',
    'privacidad_seccion3_sub1_li3' => 'Transactional email services',
    'privacidad_seccion3_sub1_li4' => 'Printing and shipping services (only for requested physical documents)',
    'privacidad_seccion3_sub1_p2' => 'All providers are contractually obligated to protect your data and cannot use it for other purposes.',
    'privacidad_seccion3_sub2_titulo' => '3.2 Legal Requirements',
    'privacidad_seccion3_sub2_p1' => 'We may disclose information if required by law (court order, legal proceeding) or to protect our legal rights.',
    'privacidad_seccion3_sub3_titulo' => '3.3 Public Validation',
    'privacidad_seccion3_sub3_p1' => 'Issued documents are publicly verifiable via QR code. The information shown in validation (beneficiary name, issuing institution, document data) is visible to whoever scans the code.',

    'privacidad_seccion4_titulo' => '4. Data Security',
    'privacidad_seccion4_p1' => 'We implement enterprise-level security measures:',
    'privacidad_seccion4_li1_strong' => 'SSL/TLS 256-bit encryption:',
    'privacidad_seccion4_li1_texto' => 'All communications are encrypted',
    'privacidad_seccion4_li2_strong' => 'Protected passwords:',
    'privacidad_seccion4_li2_texto' => 'Stored with hash and salt (bcrypt)',
    'privacidad_seccion4_li3_strong' => 'Automatic daily backups:',
    'privacidad_seccion4_li3_texto' => 'With encryption and redundant storage',
    'privacidad_seccion4_li4_strong' => 'Firewall and 24/7 monitoring:',
    'privacidad_seccion4_li4_texto' => 'Protection against unauthorized access',
    'privacidad_seccion4_li5_strong' => 'Security audits:',
    'privacidad_seccion4_li5_texto' => 'Periodic vulnerability reviews',
    'privacidad_seccion4_li6_strong' => 'Restricted access:',
    'privacidad_seccion4_li6_texto' => 'Only authorized personnel can access sensitive data',
    'privacidad_seccion4_p2' => 'Despite these measures, no system is 100% secure. We recommend using strong passwords and not sharing your credentials.',

    'privacidad_seccion5_titulo' => '5. Data Retention',
    'privacidad_seccion5_p1' => 'We retain your data while you maintain an active account or as required by law:',
    'privacidad_seccion5_li1_strong' => 'Account data:',
    'privacidad_seccion5_li1_texto' => 'Until you cancel your account + minimum legal period (generally 10 years for tax purposes)',
    'privacidad_seccion5_li2_strong' => 'Issued documents:',
    'privacidad_seccion5_li2_texto' => 'Permanently, since they serve as historical record and validation',
    'privacidad_seccion5_li3_strong' => 'Validation logs:',
    'privacidad_seccion5_li3_texto' => '5 years for auditing and fraud prevention',
    'privacidad_seccion5_li4_strong' => 'Billing data:',
    'privacidad_seccion5_li4_texto' => '10 years according to accounting regulations',
    'privacidad_seccion5_p2' => 'When you cancel your account, we securely delete unnecessary data, but retain historical records as required by law.',

    'privacidad_seccion6_titulo' => '6. Your Rights',
    'privacidad_seccion6_p1' => 'According to personal data protection laws, you have the right to:',
    'privacidad_seccion6_li1_strong' => 'Access:',
    'privacidad_seccion6_li1_texto' => 'Request a copy of your personal data that we store',
    'privacidad_seccion6_li2_strong' => 'Rectification:',
    'privacidad_seccion6_li2_texto' => 'Correct inaccurate or incomplete data',
    'privacidad_seccion6_li3_strong' => 'Erasure:',
    'privacidad_seccion6_li3_texto' => 'Request deletion of your data (subject to legal obligations)',
    'privacidad_seccion6_li4_strong' => 'Limitation:',
    'privacidad_seccion6_li4_texto' => 'Restrict certain uses of your data',
    'privacidad_seccion6_li5_strong' => 'Portability:',
    'privacidad_seccion6_li5_texto' => 'Receive your data in a structured, transferable format',
    'privacidad_seccion6_li6_strong' => 'Opposition:',
    'privacidad_seccion6_li6_texto' => 'Object to processing of your data in certain circumstances',
    'privacidad_seccion6_li7_strong' => 'Consent withdrawal:',
    'privacidad_seccion6_li7_texto' => 'Withdraw consent granted at any time',
    'privacidad_seccion6_p2_antes_link' => 'To exercise these rights, contact us at',
    'privacidad_seccion6_p2_link_texto' => 'privacidad@validarcert.com',
    'privacidad_seccion6_p2_normal' => 'We will respond within 15 business days.',

    'privacidad_seccion7_titulo' => '7. Cookies and Similar Technologies',
    'privacidad_seccion7_p1' => 'We use cookies and similar technologies for:',
    'privacidad_seccion7_li1_strong' => 'Essential cookies:',
    'privacidad_seccion7_li1_texto' => 'For portal operation (session, authentication)',
    'privacidad_seccion7_li2_strong' => 'Analytics cookies:',
    'privacidad_seccion7_li2_texto' => 'To understand how you use the service and improve it (anonymous)',
    'privacidad_seccion7_li3_strong' => 'Preference cookies:',
    'privacidad_seccion7_li3_texto' => 'To remember your settings (language, theme, etc.)',
    'privacidad_seccion7_p2' => 'You can configure your browser to reject cookies, but this may affect Service functionality.',

    'privacidad_seccion8_titulo' => '8. International Transfers',
    'privacidad_seccion8_p1' => 'Your data is primarily stored on servers located in Argentina. In some cases, service providers may process data in other countries with adequate levels of data protection (e.g., United States under Privacy Shield, European Union under GDPR).',

    'privacidad_seccion9_titulo' => '9. Children\'s Privacy',
    'privacidad_seccion9_p1' => 'Our Service is not intended for children under 13. If we discover we have collected data from a minor without parental consent, we will immediately delete that information.',
    'privacidad_seccion9_p2' => 'For minor beneficiaries whose documents are issued by educational institutions, consent is assumed to be granted by the institution acting as legal representative.',

    'privacidad_seccion10_titulo' => '10. Changes to this Policy',
    'privacidad_seccion10_p1' => 'We may update this Privacy Policy occasionally. Significant changes will be notified by email or through a prominent notice on the portal. The "Last Updated" date at the top indicates when the last modification was made.',

    'privacidad_seccion11_titulo' => '11. Contact',
    'privacidad_seccion11_p1' => 'For inquiries, to exercise your rights, or report privacy issues:',
    'privacidad_seccion11_email_privacidad' => 'privacidad@validarcert.com',
    'privacidad_seccion11_email_general_label' => 'General email:',
    'privacidad_seccion11_email_general' => 'contacto@validarcert.com',

    'privacidad_seccion12_titulo' => '12. Enforcement Authority',
    'privacidad_seccion12_p1_antes_strong' => 'In Argentina, the enforcement authority for personal data protection matters is the',
    'privacidad_seccion12_p1_strong' => 'Agency for Access to Public Information (AAIP)',
    'privacidad_seccion12_p1_normal' => '. If you believe your rights have been violated, you can file a complaint with this agency.',
    'privacidad_seccion12_aaip_label' => 'AAIP:',
    'privacidad_seccion12_aaip_url' => 'www.argentina.gob.ar/aaip',

    // === ACADÉMICO PAGE ===

    // Navigation
    'acad_nav_benefits' => 'Benefits',
    'acad_nav_features' => 'Features',
    'acad_nav_success_stories' => 'Success Stories',
    'acad_nav_faq' => 'FAQ',
    'acad_nav_request_demo' => 'Request Demo',
    'acad_nav_academic' => 'Academic',

    'acad_hero_badge' => '✓ Complete Academic Solution',
    'acad_hero_title' => 'Academic Certifications',
    'acad_hero_title_highlight' => 'Professional Digital',
    'acad_hero_subtitle' => 'Complete solution for',
    'acad_hero_institutions' => 'educational institutions',
    'acad_hero_training_centers' => 'training centers',
    'acad_hero_academies' => 'academies',
    'acad_hero_independent_trainers' => 'independent trainers',
    'acad_cta_request_custom_demo' => 'Request Custom Demo',
    'acad_cta_see_how_it_works' => 'See How It Works',

    'acad_hero_stat_time' => 'Less administrative time',
    'acad_hero_stat_portal' => 'Student portal',
    'acad_hero_stat_fraud' => 'Fraud prevention',

    'acad_problems_title' => 'Does this sound familiar?',
    'acad_problems_subtitle' => 'These are the headaches that OriginalisDoc eliminates',
    'acad_problem_manual_work' => 'Hours of Manual Work',
    'acad_problem_manual_work_desc' => 'Designing and issuing each certificate individually consumes valuable time you could spend on teaching.',
    'acad_problem_lost' => 'Lost Certificates',
    'acad_problem_lost_desc' => 'Students who lose or damage documents and constantly request reissuances.',
    'acad_problem_fraud' => 'Fraud',
    'acad_problem_fraud_desc' => 'Fake degrees and certificates circulating without effective means to verify authenticity.',
    'acad_problem_traceability' => 'No Traceability',
    'acad_problem_traceability_desc' => 'Lack of complete, verifiable academic history for each student.',
    'acad_problem_costs' => 'Printing Costs',
    'acad_problem_costs_desc' => 'High expenses on special paper, printing, toner, and physical storage.',
    'acad_problem_files' => 'Chaotic Physical Files',
    'acad_problem_files_desc' => 'Piles of papers occupying valuable space and making information retrieval difficult.',

    'acad_how_it_works_title' => 'As simple as 1, 2, 3',
    'acad_how_it_works_subtitle' => 'Immediate implementation, no technical complications',
    'acad_how_it_works_step1_title' => 'Configure your Institution',
    'acad_how_it_works_step1_desc' => 'Customize with your logo, institutional colors, and define the types of certificates you will issue.',
    'acad_how_it_works_step2_title' => 'Upload Students and Courses',
    'acad_how_it_works_step2_desc' => 'Import data in bulk from Excel or CSV. You can also upload one by one.',
    'acad_how_it_works_step3_title' => 'Issue and Validate',
    'acad_how_it_works_step3_desc' => 'Automatic generation with unique QR code. Email notification and immediate access for students.',

    'acad_documents_title' => 'Academic Document Types',
    'acad_documents_subtitle' => 'All the documents your institution needs to issue',
    'acad_documents_main' => 'Main Documents',
    'acad_doc_completion_certificate' => 'Completion Certificates',
    'acad_doc_completion_certificate_desc' => 'Official certificate certifying the completion of a course, subject, or complete program.',
    'acad_doc_diplomas' => 'Completion Diplomas',
    'acad_doc_diplomas_desc' => 'Formal degree or diploma certifying successful completion of a complete academic program.',
    'acad_doc_analytics' => 'Analytics / Academic Records',
    'acad_doc_analytics_desc' => 'Complete history with all subjects taken, grades, attendance, and acquired competencies.',
    'acad_doc_regular_student' => 'Regular Student Certificates',
    'acad_doc_regular_student_desc' => 'Document certifying the student is currently enrolled in the institution.',
    'acad_doc_registration_certificates' => 'Registration Certificates',
    'acad_doc_registration_certificates_desc' => 'Proof of registration for a specific course, subject, or academic program.',
    'acad_doc_completion_certificates' => 'Course Completion Certificates',
    'acad_doc_completion_certificates_desc' => 'Certificate certifying completion of the course, prior to final evaluation.',

    'acad_documents_supplementary' => 'Supplementary Documents',
    'acad_doc_attendance' => 'Attendance Certificates',
    'acad_doc_attendance_desc' => 'For workshops, seminars, webinars, or specific educational events.',
    'acad_doc_recognitions' => 'Recognition and Honors',
    'acad_doc_recognitions_desc' => 'Special awards, honors, or recognition for outstanding performance.',
    'acad_doc_competency' => 'Competency Certificates',
    'acad_doc_competency_desc' => 'Certify specific skills and competencies acquired during training.',
    'acad_doc_practice' => 'Professional Practice Certificates',
    'acad_doc_practice_desc' => 'Document internships, professional practice, or supervised work experience.',
    'acad_doc_conferences' => 'Conference Participation Certificates',
    'acad_doc_conferences_desc' => 'For attendance or presentations at conferences, academic sessions, and lectures.',

    'acad_portal_badge' => '★ Featured Feature',
    'acad_portal_title' => '24/7 Student Portal',
    'acad_portal_subtitle' => 'Each student has access to their own customized portal with your institution\'s branding.',
    'acad_portal_access_title' => '24/7 Access to Complete Academic Journey',
    'acad_portal_access_desc' => 'Students access from any device, at any time.',
    'acad_portal_download_title' => 'Download all their documents',
    'acad_portal_download_desc' => 'Diplomas, certificates, academic records - all in one place.',
    'acad_portal_timeline_title' => 'Academic timeline view',
    'acad_portal_timeline_desc' => 'Chronological visualization of entire educational journey.',
    'acad_portal_qr_title' => 'Individual QR code per document',
    'acad_portal_qr_desc' => 'Each document has its unique validation code.',
    'acad_portal_linkedin_title' => 'Share on LinkedIn with one click',
    'acad_portal_linkedin_desc' => 'Direct integration to post academic achievements.',

    'acad_portal_demo_name' => 'John Doe',
    'acad_portal_demo_id' => 'ID: 12,345,678',
    'acad_portal_demo_progress' => 'of 4 courses completed',
    'acad_portal_demo_diploma' => 'Diploma - Restorative Justice',
    'acad_portal_demo_diploma_date' => 'Completed: March 15, 2024',
    'acad_portal_demo_certificate' => 'Certificate - Mediation',
    'acad_portal_demo_certificate_date' => 'Completed: January 20, 2024',
    'acad_portal_demo_course_progress' => 'Course in Progress',
    'acad_portal_demo_course_name' => 'Conflict Resolution',

    'acad_use_cases_title' => 'Who is OriginalisDoc Academic for?',
    'acad_use_cases_subtitle' => 'Institutions and professionals who trust our platform',
    'acad_case_universities' => 'Universities and Higher Education',
    'acad_case_universities_desc' => 'Mass management of degrees, diplomas, and academic records for hundreds of graduates.',
    'acad_case_centers' => 'Training Centers',
    'acad_case_centers_desc' => 'Institutions like SAJuR and Liberté that issue professional certifications.',
    'acad_case_language' => 'Language Academies',
    'acad_case_language_desc' => 'Level completion certificates with international validation.',
    'acad_case_technical' => 'Technical Institutes',
    'acad_case_technical_desc' => 'Technical certifications and trades with complete traceability.',
    'acad_case_corporate' => 'Corporate Training',
    'acad_case_corporate_desc' => 'Continuing education and professional development centers.',
    'acad_case_continuing' => 'Continuing Education',
    'acad_case_continuing_desc' => 'Professional update programs and postgraduate courses.',
    'acad_case_course_organizers' => 'Course Organizers',
    'acad_case_course_organizers_desc' => 'Diplomas and certificates for courses, workshops, and special programs.',
    'acad_case_independent' => 'Independent Trainers',
    'acad_case_independent_desc' => 'Independent educators who issue professional certifications.',

    'acad_features_title' => 'Features Designed for Institutions',
    'acad_features_subtitle' => 'Everything you need to manage academic certifications',
    'acad_features_cohorts' => 'Cohort Management',
    'acad_features_cohorts_desc' => 'Organize students by class, year, or group. Issue documents in bulk by complete cohort.',
    'acad_features_bulk_issuance' => 'Bulk Issuance',
    'acad_features_bulk_issuance_desc' => 'Generate certificates for 100+ students in minutes. One click for an entire class.',
    'acad_features_notifications' => 'Automatic Email Notifications',
    'acad_features_notifications_desc' => 'Each student receives automatic notification when a document is issued.',
    'acad_features_branding' => 'Institutional Branding Portal',
    'acad_features_branding_desc' => 'Your logo, colors, and domain. Each institution projects its own identity.',
    'acad_features_academic_journey' => 'Complete Academic Journey',
    'acad_features_academic_journey_desc' => 'Verifiable history with all courses, grades, and student achievements.',
    'acad_features_validation' => 'Instant Public Validation',
    'acad_features_validation_desc' => 'Employers scan the QR code and verify authenticity instantly.',

    'acad_benefits_title' => 'Measurable Results',
    'acad_benefits_subtitle' => 'Real impact on your institution from day one',
    'acad_benefit_time_title' => 'Less Administrative Time',
    'acad_benefit_time_desc' => 'What used to take hours now takes minutes',
    'acad_benefit_savings_title' => 'Cost Savings',
    'acad_benefit_savings_desc' => 'Drastic reduction in printing and paperwork',
    'acad_benefit_fraud_title' => 'Fraud Prevention',
    'acad_benefit_fraud_desc' => 'Impossible to clone unique QR codes',
    'acad_benefit_access_title' => 'Student Access',
    'acad_benefit_access_desc' => 'Portal available at all times',
    'acad_benefit_traceability_title' => '100% Traceability and Audit',
    'acad_benefit_traceability_desc' => 'Every action is recorded. You know exactly who issued what document, when, and to whom. Ideal for audits and regulatory compliance.',

    'acad_success_stories_title' => 'Success Stories',
    'acad_success_stories_subtitle' => 'Institutions that transformed their academic management',
    'acad_case_sajur_name' => 'Argentine Society of Restorative Justice',
    'acad_case_sajur_type' => 'Specialized training center',
    'acad_case_sajur_testimonial' => '\"We went from processing each certificate manually to issuing dozens in minutes. Our students appreciate being able to access their complete academic journey 24/7, and employers trust the QR validation. Administrative time savings were 90%.\"',
    'acad_case_liberte_name' => 'Liberté Workers Cooperative',
    'acad_case_liberte_type' => 'Professional training and education',
    'acad_case_liberte_testimonial' => '\"Implementation was immediate. In less than 24 hours we were issuing certificates with our brand. The custom portal projects a professional image that our students share with pride. The premium printing option is the perfect finishing touch.\"',

    'acad_before_after_title' => 'Before vs After OriginalisDoc',
    'acad_before_after_subtitle' => 'Digital transformation of your academic management',
    'acad_before_title' => 'Before (Traditional)',
    'acad_before_manual_work' => 'Hours of manual work for each certificate',
    'acad_before_costs' => 'High printing and paperwork costs',
    'acad_before_fraud' => 'Forgery risk without verification means',
    'acad_before_in_person' => 'Students must come in person to collect',
    'acad_before_storage' => 'Chaotic physical storage and occupied space',
    'acad_before_statistics' => 'No issuance statistics or metrics',
    'acad_after_title' => 'After (OriginalisDoc)',
    'acad_after_issuance' => 'Bulk issuance in seconds',
    'acad_after_issuance_highlight' => 'with one click',
    'acad_after_savings' => '85% savings',
    'acad_after_savings_highlight' => 'in operational costs',
    'acad_after_validation' => 'QR validation impossible to forge',
    'acad_after_access' => '24/7 access',
    'acad_after_access_highlight' => 'from any device',
    'acad_after_digital' => 'All digital and cloud-based,',
    'acad_after_digital_highlight' => 'no papers or space needed',
    'acad_after_dashboards' => 'Real-time dashboards and reports',

    'acad_integrations_title' => 'Integrations and Compatibility',
    'acad_integrations_subtitle' => 'Adapts to your existing workflow',
    'acad_integration_excel' => 'Excel / CSV',
    'acad_integration_excel_desc' => 'Mass import of students and courses from Excel files.',
    'acad_integration_api' => 'REST API',
    'acad_integration_api_desc' => 'Integration with SIU systems, Moodle, and academic platforms.',
    'acad_integration_email' => 'Institutional Email',
    'acad_integration_email_desc' => 'Notifications from your institutional domain (@yourinstitution.edu).',
    'acad_integration_subdomains' => 'Subdomains',
    'acad_integration_subdomains_desc' => 'Portal on your own domain: certificates.yourinstitution.edu',

    'acad_faq_title' => 'Frequently Asked Questions',
    'acad_faq_subtitle' => 'Everything you need to know about OriginalisDoc Academic',
    'acad_faq_upload_title' => 'How do I upload my students\' information?',
    'acad_faq_upload_resp' => 'You can upload students in two ways: individually from the admin panel, or in bulk by importing an Excel/CSV file with all data. We provide a template to facilitate the process.',
    'acad_faq_validity_title' => 'Do digital certificates have legal validity?',
    'acad_faq_validity_resp' => 'Yes, digital certificates have the same legal validity as physical ones in Argentina. Additionally, we offer a premium printing option with special paper and security features for institutions that require it.',
    'acad_faq_design_title' => 'Can I completely customize the design?',
    'acad_faq_design_resp' => 'Absolutely. You can configure your logo, institutional colors, digital signatures, and all branding. Each certificate is generated with your visual identity.',
    'acad_faq_access_title' => 'What happens if a student loses access to their portal?',
    'acad_faq_access_resp' => 'The student can recover access using their ID and an email verification process. Additionally, as the institution administrator, you can regenerate access at any time.',
    'acad_faq_validation_title' => 'How does an employer validate the certificate?',
    'acad_faq_validation_resp' => 'The employer simply scans the QR code on the certificate with their mobile phone. They will be redirected automatically to a validation page that displays all certificate data and the student\'s academic journey.',
    'acad_faq_retroactive_title' => 'Can I issue retroactive certificates?',
    'acad_faq_retroactive_resp' => 'Yes, you can upload and issue certificates for previous classes without any problem. The system allows indicating past issuance dates.',
    'acad_faq_limit_title' => 'Is there a limit on issuances?',
    'acad_faq_limit_resp' => 'There is no limit on issuances. You can generate as many certificates as you need. Plans are adjusted according to the number of active students at your institution.',

    'acad_cta_final_title' => 'Transform Your Institution\'s Academic Management',
    'acad_cta_final_desc' => 'Join the institutions that have already saved thousands of administrative hours and project a professional image with digital certifications.',
    'acad_cta_final_demo' => 'Request Custom Demo',
    'acad_cta_final_contact_sales' => 'Contact Sales',
    'acad_cta_final_implementation' => 'Implementation',
    'acad_cta_final_less_time' => 'Less time',
    'acad_cta_final_certificates' => 'Certificates',

    'acad_footer_tagline' => 'Professional Digital Certifications',
    'acad_footer_copyright' => '© 2025 OriginalisDoc. All rights reserved.',
    'acad_footer_home' => 'Home',
    'acad_footer_terms' => 'Terms',
    'acad_footer_privacy' => 'Privacy',

    'acad_meta_title' => 'OriginalisDoc Academic - Digital Certifications for Educational Institutions',
    'acad_meta_description' => 'Complete solution for digital certifications for educational institutions, training centers, and independent trainers. Bulk issuance, QR validation, and student portal.',
    'acad_meta_keywords' => 'academic certificates, digital diplomas, digital academic records, educational institutions, professional training',
    'acad_meta_og_title' => 'OriginalisDoc Academic - Certifications for Educational Institutions',
    'acad_meta_og_description' => 'Issue certificates, diplomas, and digital academic records with QR validation. 24/7 student portal and automated bulk issuance.',
    'acad_meta_twitter_title' => 'OriginalisDoc Academic - Certifications for Educational Institutions',
    'acad_meta_twitter_description' => 'Issue certificates, diplomas, and digital academic records with QR validation. 24/7 student portal and automated bulk issuance.',
];