<?php
// Traducciones adicionales para la página profesional (tarjeta digital) en Chile
$profesional_cl = [
    // Navegación
    'prof_nav_perfiles' => 'Tarjeta Digital',
    'prof_nav_como_funciona' => 'Cómo Funciona',
    'prof_nav_caracteristicas' => 'Características',
    'prof_nav_planes' => 'Planes',
    'prof_nav_empezar' => 'Crear Mi Tarjeta',

    // Hero
    'prof_hero_badge' => '✓ La Tarjeta de Visita del Siglo XXI',
    'prof_hero_title' => 'Tu Tarjeta Digital Profesional',
    'prof_hero_title_highlight' => 'Con QR Infalsificable',
    'prof_hero_subtitle' => 'Olvídese del papel. Una tarjeta digital en formato JPG con QR dinámico que lleva a su página web personalizada. Actualice sus datos al instante desde un panel seguro.',
    'prof_hero_url_ejemplo' => 'Tu URL personalizada:',
    'prof_hero_url_ejemplo_subdomain' => 'tunombre',
    'prof_hero_url_ejemplo_domain' => '.originalisdoc.com',
    'prof_cta_empezar' => 'Ver Planes y Crear Mi Tarjeta',
    'prof_cta_secundario' => 'Ver Cómo Funciona',

    // Características Hero
    'prof_stat_qr' => 'QR Infalsificable',
    'prof_stat_qr_desc' => 'Tecnología blockchain',
    'prof_stat_actualizacion' => 'Actualización',
    'prof_stat_actualizacion_desc' => 'En tiempo real',
    'prof_stat_landing' => 'Tu Página Web',
    'prof_stat_landing_desc' => 'Incluida en todos los planes',

    // Sección: ¿Qué es la Tarjeta Digital?
    'prof_que_es_titulo' => '¿Qué es la Tarjeta Digital?',
    'prof_que_es_subtitulo' => 'La evolución definitiva de la tarjeta de visita tradicional',
    'prof_que_es_desc' => 'Una imagen JPG de alta calidad (formato tarjeta de visita) con un código QR único e infalsificable. Al escanear el QR, sus contactos acceden a su página web personalizada con toda su información profesional: foto, datos de contacto, servicios, horarios y mucho más.',

    'prof_tarjeta_feature1_titulo' => 'Imagen JPG Lista para Usar',
    'prof_tarjeta_feature1_desc' => 'Descargue su tarjeta en alta resolución y compártala por WhatsApp, email, redes sociales o imprímala en papel de calidad.',
    'prof_tarjeta_feature2_titulo' => 'QR Dinámico e Infalsificable',
    'prof_tarjeta_feature2_desc' => 'El QR no se puede clonar ni copiar. Si alguien intenta replicar su tarjeta, el código no funcionará. Tecnología de verificación única.',
    'prof_tarjeta_feature3_titulo' => 'Página Web Incluida',
    'prof_tarjeta_feature3_desc' => 'Tu URL personalizada (ej: juanperez.originalisdoc.com) con diseño profesional, tu foto, datos de contacto, servicios, horarios y más.',
    'prof_tarjeta_feature4_titulo' => 'Panel de Administración',
    'prof_tarjeta_feature4_desc' => 'Actualice su información al instante. Cambios en tiempo real sin necesidad de reimprimir o reenviar su tarjeta.',

    // Sección: Cómo Funciona
    'prof_como_titulo' => 'Cómo Funciona en 3 Pasos',
    'prof_como_subtitulo' => 'De la contratación a tu tarjeta digital en minutos',
    'prof_como_paso1' => 'Elija su Plan y Personalice',
    'prof_como_paso1_desc' => 'Seleccione el plan que mejor se adapte a usted. Cargue sus datos (nombre, foto, contacto, servicios) y elija su paleta de colores entre nuestras opciones preestablecidas.',
    'prof_como_paso2' => 'Descargue su Tarjeta JPG',
    'prof_como_paso2_desc' => 'Su tarjeta digital está lista en alta resolución con su QR único e infalsificable. Descárguela y compártala por donde quiera: WhatsApp, email, LinkedIn o imprímala.',
    'prof_como_paso3' => 'Actualice Cuando Deseé',
    'prof_como_paso3_desc' => 'Desde su panel de administración seguro, modifique sus datos las veces que necesite. Los cambios son instantáneos y su QR siempre apunta a la información actualizada.',

    // Características Estrella
    'prof_caracteristicas_titulo' => 'Por Qué Nuestra Tarjeta Digital es Única',
    'prof_caracteristicas_subtitulo' => 'Tecnología y diseño pensados para profesionales exigentes',

    'prof_caract_qr_titulo' => 'QR Infalsificable y Dinámico',
    'prof_caract_qr_desc' => 'No es un QR estático común. Es un código verificable que no puede ser clonado. Si alguien copia su tarjeta, el QR no funcionará. Además, puede cambiar el destino del QR sin necesidad de regenerar la imagen.',
    'prof_caract_panel_titulo' => 'Panel de Administración Intuitivo',
    'prof_caract_panel_desc' => 'Acceda desde cualquier dispositivo a su panel seguro. Actualice su foto, datos de contacto, servicios, horarios y más. Sin conocimientos técnicos, 100% visual y amigable.',
    'prof_caract_paletas_titulo' => 'Paletas de Colores Profesionales',
    'prof_caract_paletas_desc' => 'Elija entre 12 combinaciones de colores preestablecidas diseñadas por profesionales. Desde elegantes y minimalistas hasta vibrantes y creativas. Su marca, su estilo.',
    'prof_caract_landing_titulo' => 'Página Web Profesional Incluida',
    'prof_caract_landing_desc' => 'Su subdominio personalizado (tunombre.originalisdoc.com) con diseño responsivo, optimizado para móviles. Foto de perfil, información de contacto, descripción de servicios, horarios de atención y botones de acción directa (WhatsApp, email, teléfono).',
    'prof_caract_formatos_titulo' => 'Múltiples Formatos de Uso',
    'prof_caract_formatos_desc' => 'JPG en alta resolución para imprimir, PDF para enviar por email, y versión optimizada para redes sociales. Una sola tarjeta, todos los usos que necesite.',
    'prof_caract_seguridad_titulo' => 'Seguridad y Respaldo 24/7',
    'prof_caract_seguridad_desc' => 'Sus datos están protegidos con encriptación de nivel bancario. Respaldo automático diario. Su información siempre segura y disponible.',

    // Casos de Uso
    'prof_casos_titulo' => '¿Para Quién es la Tarjeta Digital?',
    'prof_casos_subtitulo' => 'Profesionales de todas las industrias que valoran la primera impresión',

    'prof_caso_abogados' => 'Abogados y Consultores',
    'prof_caso_abogados_desc' => 'Entrege su tarjeta con QR a sus clientes. Ellos escanean y acceden a sus áreas de práctica, horarios de atención y formulario de consulta.',
    'prof_caso_medicos' => 'Médicos y Profesionales de la Salud',
    'prof_caso_medicos_desc' => 'Su tarjeta con especialidades, horarios de consultorio, seguros de salud que acepta y botón directo para agendar turnos.',
    'prof_caso_arquitectos' => 'Arquitectos y Diseñadores',
    'prof_caso_arquitectos_desc' => 'Comparta su tarjeta y que sus prospectos vean su portafolio visual en su página web personalizada.',
    'prof_caso_comercios' => 'Comercios y Emprendedores',
    'prof_caso_comercios_desc' => 'Su tarjeta comercial con horarios, ubicación, catálogo de productos/servicios y botón de WhatsApp para consultas.',
    'prof_caso_coaches' => 'Coaches y Capacitadores',
    'prof_caso_coaches_desc' => 'Muestre sus servicios, testimonios, y permita a sus clientes agendar sesiones directamente desde su página web.',
    'prof_caso_freelancers' => 'Trabajadores Freelance y Creativos',
    'prof_caso_freelancers_desc' => 'Su tarjeta digital con enlaces a su portafolio, redes sociales y tarifas. Impresión profesional garantizada.',
    'prof_caso_productores' => 'Productores de Alimentos',
    'prof_caso_productores_desc' => 'Comparta su tarjeta con certificaciones de calidad, trazabilidad de productos y catálogo. El QR lleva a sus clientes a toda su información verificada.',
    'prof_caso_artesanos' => 'Artesanos y Manualidades',
    'prof_caso_artesanos_desc' => 'Muestre su trabajo artesanal con galería de fotos, precios y contacto directo. Perfecta para ferias, mercados y clientes particulares.',
    'prof_caso_trainers' => 'Entrenadores Personales y Nutricionistas',
    'prof_caso_trainers_desc' => 'Su tarjeta con especialidades, planes disponibles, horarios y sistema de agendamiento. Sus clientes reservan turnos directamente desde su página web.',

    // Planes y Precios
    'prof_planes_titulo' => 'Elija el Plan que Mejor se Adapta a Usted',
    'prof_planes_subtitulo' => 'Todos los planes incluyen tu Tarjeta Digital con QR infalsificable y página web personalizada',

    'prof_plan_esencial_titulo' => 'Basicum',
    'prof_plan_esencial_desc' => 'Tu tarjeta digital profesional con lo esencial para comenzar a impresionar.',
    'prof_plan_esencial_precio' => '$9 USD',
    'prof_plan_esencial_periodo' => '/ Anual',
    'prof_plan_esencial_feat1' => 'Tarjeta Digital JPG con QR Infalsificable',
    'prof_plan_esencial_feat2' => 'Subdominio Personalizado (tunombre.originalisdoc.com)',
    'prof_plan_esencial_feat3' => 'Panel de Administración Seguro',
    'prof_plan_esencial_feat4' => '5 Paletas de Colores Preestablecidas',
    'prof_plan_esencial_feat5' => 'Datos de Contacto y Horarios',
    'prof_plan_esencial_feat6' => 'Botones de Acción Directa (WhatsApp, Email, Tel)',
    'prof_plan_esencial_feat7' => 'Actualización Ilimitada de Información',
    'prof_plan_esencial_cta' => 'Comenzar con Esencial',

    'prof_plan_plus_badge' => 'Más Popular',
    'prof_plan_plus_titulo' => 'Premium',
    'prof_plan_plus_desc' => 'Todo lo del plan Basicum más herramientas avanzadas para destacar y vender más.',
    'prof_plan_plus_precio' => '$19 USD',
    'prof_plan_plus_periodo' => '/ Anual',
    'prof_plan_plus_feat1_strong' => 'Todo lo del plan Basicum, más:',
    'prof_plan_plus_feat2' => '12 Paletas de Colores Premium',
    'prof_plan_plus_feat3' => 'Galería de Fotos de Servicios (hasta 100 imágenes HD)',
    'prof_plan_plus_feat4' => 'Sección de Servicios Detallada',
    'prof_plan_plus_feat5' => 'Video de Presentación Personal',
    'prof_plan_plus_feat6' => 'Formulario de Contacto Integrado',
    'prof_plan_plus_feat7' => 'Estadísticas de Escaneos del QR',
    'prof_plan_plus_feat8' => 'Generador de Currículum Inteligente (PDF y Web)',
    'prof_plan_plus_feat9' => 'Sistema de Agendamiento de Citas (Calendly)',
    'prof_plan_plus_feat10' => 'Integración con Credenciales Verificadas',
    'prof_plan_plus_cta' => 'Obtener Plan Premium',

    'prof_plan_pro_badge' => 'Profesional',
    'prof_plan_pro_titulo' => 'Excellens',
    'prof_plan_pro_desc' => 'Para profesionales que necesitan herramientas completas de gestión y presencia digital.',
    'prof_plan_pro_precio' => '$49 USD',
    'prof_plan_pro_periodo' => '/ Anual',
    'prof_plan_pro_feat1_strong' => 'Todo lo del plan Premium, más:',
    'prof_plan_pro_feat2' => 'Portafolio de Proyectos Ilimitado',
    'prof_plan_pro_feat3' => 'Múltiples Páginas Personalizadas',
    'prof_plan_pro_feat4' => 'Analíticas Avanzadas y Reportes',
    'prof_plan_pro_feat5' => 'Exportación de Contactos',
    'prof_plan_pro_feat6' => 'Integraciones API Personalizadas',
    'prof_plan_pro_feat7' => 'Soporte Prioritario 24/7',
    'prof_plan_pro_feat8' => 'Estadísticas y Métricas Avanzadas',
    'prof_plan_pro_cta' => 'Obtener Plan Excellens',

    'prof_plan_elite_badge' => 'Empresarial',
    'prof_plan_elite_titulo' => 'Supremus',
    'prof_plan_elite_desc' => 'La solución definitiva con dominio propio y personalización total para su marca.',
    'prof_plan_elite_precio' => '$99 USD',
    'prof_plan_elite_periodo' => '/ Anual',
    'prof_plan_elite_feat1_strong' => 'Todo lo del plan Excellens, más:',
    'prof_plan_elite_feat2' => 'Dominio Propio Incluido (tunombre.com)',
    'prof_plan_elite_feat3' => 'SSL Premium y Certificados de Seguridad',
    'prof_plan_elite_feat4' => 'Diseño 100% Personalizado a Medida',
    'prof_plan_elite_feat5' => 'Integración con Tu Identidad Corporativa',
    'prof_plan_elite_feat6' => 'Subdominios Ilimitados para Tu Equipo',
    'prof_plan_elite_feat7' => 'Sistema de Roles y Permisos Avanzado',
    'prof_plan_elite_feat8' => 'Gerente de Cuenta Dedicado',
    'prof_plan_elite_cta' => 'Obtener Plan Supremus',

    // CTA Final
    'prof_cta_final_titulo' => 'Dejé Atrás las Tarjetas de Papel',
    'prof_cta_final_desc' => 'Únase a miles de profesionales que ya impresionan con su Tarjeta Digital infalsificable.',
    'prof_cta_final_btn' => 'Crear Mi Tarjeta Ahora',
    'prof_cta_final_garantia' => '✓ Sin costos ocultos  •  ✓ Cancelación en cualquier momento  •  ✓ Soporte incluido',

    // Formas de Pago
    'prof_pagos_titulo' => 'Formas de Pago',
    'prof_pagos_subtitulo' => 'Métodos seguros y convenientes para tu país',
    'prof_pagos_argentina' => 'Métodos de Pago en Argentina',
    'prof_pagos_internacional' => 'Pago Internacional',
    'prof_pago_mercadopago' => 'MercadoPago',
    'prof_pago_mercadopago_desc' => 'Tarjeta de crédito, débito y efectivo',
    'prof_pago_pagofacil' => 'PagoFácil',
    'prof_pago_pagofacil_desc' => 'Pago en efectivo en cualquier sucursal',
    'prof_pago_transferencia' => 'Transferencia Bancaria',
    'prof_pago_transferencia_desc' => 'CBU/CVU para pesos argentinos',
    'prof_pago_paypal' => 'PayPal',
    'prof_pago_paypal_desc' => 'Tarjetas y moneda local en todo el mundo',
    
    // Meta tags para la página profesional
    'prof_meta_title' => 'Tarjeta Digital Profesional con QR Infalsificable | OriginalisDoc',
    'prof_meta_description' => 'Tu tarjeta de contacto digital profesional con QR dinámico e infalsificable. Página web personalizada, panel de administración seguro y actualización instantánea.',
    'prof_meta_keywords' => 'tarjeta digital, qr infalsificable, tarjeta de contacto digital, página web profesional, networking digital',
    'prof_meta_og_title' => 'Tarjeta Digital: La Evolución de tu Tarjeta de Visita',
    'prof_meta_og_description' => 'Olvídese de las tarjetas de papel. Tu identidad profesional en una tarjeta digital con QR verificable, página web personalizada y gestión en tiempo real.',
    'prof_meta_twitter_title' => 'Tarjeta Digital Profesional by OriginalisDoc',
    'prof_meta_twitter_description' => 'La tarjeta de visita del futuro. QR infalsificable, página web incluida y actualización instantánea.',
];
?>