<?php
// Español Uruguay - es_UY
$lang = [
    // Meta
    'meta_title' => 'Verumax - Crea, Gestiona y Valida tu Prestigio Digital',
    'meta_description' => 'Ecosistema de herramientas para emitir credenciales infalsificables, construir tu marca personal verificada e implementar asistentes de IA especializados.',
    'meta_keywords' => 'credenciales digitales, validación QR, marca personal verificada, asistentes IA, prestigio digital, certificaciones infalsificables',
    'meta_author' => 'Verumax',
    'meta_og_title' => 'Verumax - Crea, Gestiona y Valida tu Prestigio Digital',
    'meta_og_description' => 'Ecosistema de herramientas para emitir credenciales infalsificables, construir tu marca personal verificada e implementar asistentes de IA especializados.',
    'meta_twitter_title' => 'Verumax - Tu Prestigio Digital Verificado',
    'meta_twitter_description' => 'Herramientas para emitir credenciales infalsificables, construir tu marca personal y asistentes IA especializados.',

    // Header/Navigation
    'nav_inicio' => 'Inicio',
    'nav_volver_inicio' => 'Volver al Inicio',
    'nav_tema_claro' => 'Cambiar a modo claro',
    'nav_tema_oscuro' => 'Cambiar a modo oscuro',
    'nav_soluciones' => 'Soluciones Especializadas por Sector',
    'nav_soluciones_academico' => 'Académico',
    'nav_soluciones_profesional' => 'Profesional',
    'nav_soluciones_eventos' => 'Eventos',
    'nav_soluciones_empresarial' => 'Empresarial',
    'nav_soluciones_cooperativas' => 'Cooperativas',
    'nav_soluciones_mutuales' => 'Mutuales',
    'nav_productos' => 'Productos',
    'nav_productos_tarjeta_digital' => 'Tarjeta Digital',
    'nav_productos_certificados' => 'Certificados Académicos',
    'nav_categorias' => 'Categorías',
    'nav_beneficios' => 'Beneficios',
    'nav_faq' => 'Preguntas Frecuentes',
    'nav_validar' => 'Validar',
    'nav_demo' => 'Solicitar Demo',

    // Hero Section
    'hero_badge' => 'Confiado por instituciones y profesionales globalmente',
    'hero_title' => 'Crea, Gestiona y Valida tu Prestigio Digital',
    'hero_subtitle' => 'Un ecosistema de herramientas para emitir credenciales infalsificables, construir tu marca personal verificada e implementar asistentes de IA especializados.',
    'hero_cta_primary' => 'Explorar Soluciones',
    'hero_cta_secondary' => 'Validar Documento',

    // Hero Mockup Mobile
    'hero_mockup_certificado' => 'Certificado',
    'hero_mockup_curso' => 'Justicia Restaurativa',
    'hero_mockup_estudiante' => 'Juan Pérez - CI 12345678',
    'hero_mockup_verificado' => '✓ Verificado',
    'hero_mockup_valido' => 'Válido hasta 2026',
    'hero_mockup_ver_detalles' => 'Ver Detalles',
    'hero_mockup_certificados' => 'Certificados',
    'hero_mockup_en_curso' => 'En Curso',

    // Categorías Section
    'cat_title' => 'Soluciones por Sector',
    'cat_subtitle' => 'Elegí tu sector para descubrir la solución perfecta diseñada para tus necesidades específicas',

    'cat_academico' => 'Académico',
    'cat_academico_1' => 'Instituciones Educativas',
    'cat_academico_2' => 'Centros de Formación',
    'cat_academico_3' => 'Formadores Particulares',
    'cat_academico_cta' => 'Ver Solución →',

    'cat_profesional' => 'Profesional',
    'cat_profesional_1' => 'Salud y Bienestar',
    'cat_profesional_2' => 'Ingeniería y Arquitectura',
    'cat_profesional_3' => 'Todos los Profesionales',

    'cat_eventos' => 'Eventos',
    'cat_eventos_1' => 'Congresos y Conferencias',
    'cat_eventos_2' => 'Festivales y Conciertos',
    'cat_eventos_3' => 'Control de Acceso',

    'cat_empresarial' => 'Empresarial',
    'cat_empresarial_1' => 'Garantías y Autenticidad',
    'cat_empresarial_2' => 'Certificados de Calidad',
    'cat_empresarial_3' => 'Recibos Validados',

    'cat_cooperativas' => 'Cooperativas',
    'cat_cooperativas_1' => 'Credenciales de Socios',
    'cat_cooperativas_2' => 'Certificados de Participación',
    'cat_cooperativas_3' => 'Constancias de Actividades',

    'cat_mutuales' => 'Mutuales',
    'cat_mutuales_1' => 'Credenciales de Asociados',
    'cat_mutuales_2' => 'Comprobantes de Servicios',
    'cat_mutuales_3' => 'Cartillas de Beneficios',

    'cat_artistas' => 'Artistas',
    'cat_artistas_1' => 'Pintores',
    'cat_artistas_2' => 'Artesanos',
    'cat_artistas_3' => 'Fotógrafos',

    'cat_tarjeta_digital' => 'Tarjeta Digital',
    'cat_tarjeta_digital_1' => 'QR Infalsificable',
    'cat_tarjeta_digital_2' => 'Landing Page Incluida',
    'cat_tarjeta_digital_3' => 'Actualización Instantánea',
    'cat_tarjeta_digital_cta' => 'Ver Planes →',

    'cat_proximamente' => 'Próximamente',
    'cat_footer' => 'Más categorías próximamente.',
    'cat_footer_link' => 'Consultanos',
    'cat_footer_text' => 'si tu sector no está listado.',

    // Productos Section
    'productos_title' => 'Un Ecosistema de Herramientas a tu Disposición',
    'productos_subtitle' => 'Descubre nuestros productos individuales. Cada uno construido sobre nuestra tecnología de validación inalterable.',

    // Servicios Principales
    'servicios_title' => 'Nuestros Servicios Principales',
    'servicios_subtitle' => 'Funcionalidades esenciales que todas nuestras organizaciones disfrutan, sin importar su sector',

    'serv_antifraude' => 'Seguridad Anti-Fraude Total',
    'serv_antifraude_desc' => 'Códigos QR únicos e imposibles de falsificar que garantizan la autenticidad de cada documento.',

    'serv_portal' => 'Portal 24/7',
    'serv_portal_desc' => 'Acceso permanente para estudiantes, clientes, socios o empleados desde cualquier dispositivo.',

    'serv_impresion' => 'Impresión Premium',
    'serv_impresion_desc' => 'Documentos físicos de alta calidad con hologramas y laminado, enviados a domicilio.',

    'serv_branding' => 'Branding Personalizado',
    'serv_branding_desc' => 'Portal y documentos con tu logo, colores y diseño institucional único.',

    'serv_emision' => 'Emisión Masiva',
    'serv_emision_desc' => 'Genera cientos de documentos automáticamente con notificación instantánea.',

    'serv_validacion' => 'Portal de Validación',
    'serv_validacion_desc' => 'Cualquier persona puede verificar la autenticidad de tus documentos al instante.',

    // Casos de Éxito
    'casos_title' => 'Casos de Éxito',
    'casos_subtitle' => 'Instituciones y profesionales que confían en Verumax',

    'caso_sajur_org' => 'Sociedad Argentina de Justicia Restaurativa',
    'caso_sajur_tipo' => 'Organización educativa especializada',
    'caso_sajur_texto' => '"Pasamos de procesar manualmente cada certificado a emitir decenas en minutos. Nuestros estudiantes valoran poder acceder a su trayectoria completa 24/7, y los empleadores confían en la validación QR. El ahorro en tiempo administrativo fue del 90%."',


    'caso_liberte_org' => 'Cooperativa de Trabajo Liberté',
    'caso_liberte_tipo' => 'Formación profesional y capacitación',
    'caso_liberte_texto' => '"La implementación fue instantánea. En menos de 24 horas ya estábamos emitiendo certificados con nuestra marca. El portal personalizado proyecta una imagen profesional que nuestros estudiantes comparten con orgullo. La opción de impresión premium es el toque final perfecto."',


    'caso_nutricion_org' => 'Lic. María González',
    'caso_nutricion_tipo' => 'Nutricionista profesional independiente',
    'caso_nutricion_texto' => '"Mis planes nutricionales ahora tienen un código QR que mis pacientes pueden validar. Esto aumentó significativamente la confianza y redujo las consultas sobre autenticidad. Además, el envío físico premium es perfecto para quienes quieren tenerlo impreso."',


    'caso_empresa_org' => 'TechVision S.A.',
    'caso_empresa_tipo' => 'Empresa de tecnología',
    'caso_empresa_texto' => '"Usamos Verumax para emitir garantías de nuestros productos con QR verificable. Nuestros clientes pueden validar la autenticidad al instante y acceder a toda la información técnica. La reducción en reclamos por falsificaciones fue del 95%."',


    // FAQ
    'faq_title' => 'Preguntas Frecuentes',
    'faq_subtitle' => 'Todo lo que necesitas saber sobre Verumax',

    'faq_1_q' => '¿Cuánto tiempo lleva implementar Verumax?',
    'faq_1_a' => 'Menos de 24 horas. Solo necesitas configurar tu marca (logo y colores), cargar tus datos, y comenzar a emitir. Incluimos onboarding guiado paso a paso.',

    'faq_2_q' => '¿Los documentos digitales tienen la misma validez que los físicos?',
    'faq_2_a' => 'Sí. Los documentos digitales tienen plena validez legal. Además, nuestro sistema QR permite verificar la autenticidad al instante, algo imposible con documentos físicos tradicionales.',

    'faq_3_q' => '¿Qué pasa si necesito una versión física del documento?',
    'faq_3_a' => 'Ofrecemos un servicio premium de impresión HD con hologramas de seguridad y laminado, enviado por correo rastreado a toda Argentina. Puedes solicitarlo directamente desde tu portal y recibir seguimiento del envío.',

    'faq_4_q' => '¿Cómo funciona la validación con QR?',
    'faq_4_a' => 'Cada documento incluye un código QR único que redirige a un portal de validación personalizado con tu marca. Allí se muestra toda la información del documento y su trayectoria completa. Es imposible de falsificar o alterar.',

    'faq_5_q' => '¿Puedo personalizar el diseño de los documentos?',
    'faq_5_a' => 'Sí, 100%. Cada institución o profesional tiene su portal completamente personalizado con su logo, colores y diseño de marca. Los documentos reflejan tu identidad visual única.',

    'faq_6_q' => '¿Necesito conocimientos técnicos para usar la plataforma?',
    'faq_6_a' => 'No. La plataforma está diseñada para ser extremadamente intuitiva. Si sabes navegar internet, puedes gestionar Verumax sin problemas. Además, ofrecemos soporte técnico completo.',

    'faq_7_q' => '¿Qué pasa con mis datos? ¿Son seguros?',
    'faq_7_a' => 'Absoluta seguridad. Usamos encriptación de nivel bancario, backups automáticos diarios, y cumplimos con las normativas de protección de datos personales. Tus datos están más seguros que en un archivo físico.',

    // Validar Documento Section
    'validar_title' => 'Validar un Documento',
    'validar_subtitle' => 'Ingresá el código de validación que aparece en el documento (formato: VALID-XXXXXXXXXXXX)',
    'validar_placeholder' => 'VALID-XXXXXXXXXXXX',
    'validar_btn' => 'Validar Ahora',
    'validar_ejemplo' => 'Ejemplo: VALID-A1B2C3D4E5F6',

    // Contacto Section
    'contacto_title' => 'Comenzá a Emitir Documentos Profesionales Hoy',
    'contacto_subtitle' => 'Contactanos para una demostración personalizada y descubrí cómo Verumax puede transformar tu gestión documental.',
    'contacto_nombre' => 'Nombre Completo',
    'contacto_email' => 'Email',
    'contacto_institucion' => 'Institución/Organización',
    'contacto_mensaje' => 'Contanos sobre tu necesidad...',
    'contacto_btn' => 'Solicitar Demostración',
    'contacto_info' => 'O escribinos directamente:',

    // Footer
    'footer_descripcion' => 'La plataforma definitiva para documentos digitales y físicos seguros con validación QR.',
    'footer_enlaces' => 'Enlaces Rápidos',
    'footer_caracteristicas' => 'Características',
    'footer_contacto' => 'Contacto',
    'footer_seguridad' => 'Tecnología y Seguridad de Nivel Empresarial',
    'footer_copyright' => '© 2025 Verumax. Todos los derechos reservados.',
    'footer_terminos' => 'Términos de Servicio',
    'footer_privacidad' => 'Política de Privacidad',

    // Badges de Seguridad
    'badge_ssl' => 'SSL',
    'badge_ssl_desc' => 'Encriptación 256-bit',
    'badge_https' => 'HTTPS',
    'badge_https_desc' => 'Conexión Segura',
    'badge_privacidad' => 'Privacidad',
    'badge_privacidad_desc' => 'Datos Protegidos',
    'badge_backup' => 'Backup',
    'badge_backup_desc' => 'Automático Diario',
    'badge_uptime' => 'Uptime 99.9%',
    'badge_uptime_desc' => 'Disponibilidad',
    'badge_soporte' => 'Soporte',
    'badge_soporte_desc' => 'Técnico 24/7',

    // Estadísticas Hero
    'stat_uptime' => 'Disponibilidad',
    'stat_documentos' => 'Documentos emitidos',
    'stat_acceso' => 'Acceso disponible',
    'stat_ahorro' => 'Ahorro en costos administrativos',

    // Social Proof Contacto
    'social_confianza' => 'Instituciones y profesionales que ya confían en Verumax',
    'social_mas' => '+ más organizaciones y profesionales',

    // Beneficios Contacto
    'benefit_demo' => 'Demo gratis sin compromiso',
    'benefit_demo_desc' => 'Prueba todas las funciones',
    'benefit_implementacion' => 'Implementación en 24hs',
    'benefit_implementacion_desc' => 'Comenzá a emitir mañana',
    'benefit_soporte' => 'Soporte técnico incluido',
    'benefit_soporte_desc' => 'Asistencia completa',

    // CTA Contacto
    'contacto_cta_btn' => 'Solicitar Demo Gratis',
    'contacto_cta_email' => 'O escríbenos a',

    // Footer - Enlaces rápidos
    'footer_link_beneficios' => 'Beneficios',
    'footer_link_como' => 'Cómo Funciona',
    'footer_link_validar' => 'Validar Documento',
    'footer_link_demo' => 'Solicitar Demo',

    // Footer - Características
    'footer_feat_qr' => 'Validación QR',
    'footer_feat_portal' => 'Portal 24/7',
    'footer_feat_impresion' => 'Impresión Premium',
    'footer_feat_personalizable' => '100% Personalizable',

    // Footer - Contacto
    'footer_horario' => 'Lun - Vie: 9:00 - 18:00',

    // Página de Privacidad
    'privacidad_title' => 'Política de Privacidad',
    'privacidad_updated' => 'Última actualización',

    // Página de Términos de Servicio
    'terminos_title' => 'Términos de Servicio',
    'terminos_updated' => 'Última actualización',

    // Términos de Servicio - Contenido
    'terminos_seccion1_titulo' => '1. Aceptación de los Términos',
    'terminos_seccion1_p1' => 'Al acceder y utilizar la plataforma Verumax ("el Servicio"), usted acepta estar legalmente vinculado por estos Términos de Servicio. Si no está de acuerdo con estos términos, no utilice el Servicio.',
    'terminos_seccion1_p2' => 'Verumax se reserva el derecho de modificar estos términos en cualquier momento. Los cambios entrarán en vigor inmediatamente después de su publicación en el sitio web.',

    'terminos_seccion2_titulo' => '2. Descripción del Servicio',
    'terminos_seccion2_p1' => 'Verumax es una plataforma que permite a instituciones educativas, profesionales independientes, organizadores de eventos, empresas, cooperativas y mutuales emitir, gestionar y validar documentos digitales con códigos QR de verificación.',
    'terminos_seccion2_p2' => 'Los servicios incluyen, pero no se limitan a:',
    'terminos_seccion2_li1' => 'Emisión de documentos digitales personalizados',
    'terminos_seccion2_li2' => 'Portal personalizado para cada institución/profesional',
    'terminos_seccion2_li3' => 'Sistema de validación con códigos QR únicos',
    'terminos_seccion2_li4' => 'Almacenamiento seguro en la nube',
    'terminos_seccion2_li5' => 'Opción de impresión premium de documentos físicos',
    'terminos_seccion2_li6' => 'Emisión masiva de documentos',
    'terminos_seccion2_li7' => 'Integración con sistemas académicos (SIU, Moodle, etc.)',
    'terminos_seccion2_li8' => 'Generación de reportes y estadísticas',
    'terminos_seccion2_li9' => 'API REST para integraciones personalizadas',
    'terminos_seccion2_li10' => 'Soporte técnico especializado 24/7',

    'terminos_seccion3_titulo' => '3. Registro y Cuenta de Usuario',
    'terminos_seccion3_p1' => 'Para utilizar el Servicio, debe crear una cuenta proporcionando información precisa, completa y actualizada. Usted es responsable de:',
    'terminos_seccion3_li1' => 'Mantener la confidencialidad de su contraseña y credenciales de acceso',
    'terminos_seccion3_li2' => 'Todas las actividades que ocurran bajo su cuenta',
    'terminos_seccion3_li3' => 'Notificar inmediatamente cualquier uso no autorizado de su cuenta',
    'terminos_seccion3_li4' => 'Proporcionar datos veraces de su institución u organización',
    'terminos_seccion3_p2' => 'Verumax se reserva el derecho de suspender o cancelar cuentas que violen estos términos o que proporcionen información falsa.',

    'terminos_seccion4_titulo' => '4. Uso Permitido',
    'terminos_seccion4_p1' => 'El Servicio solo puede utilizarse con fines legítimos y de acuerdo con estos Términos. No está permitido utilizar Verumax para actividades fraudulentas, ilegales o que infrinjan derechos de terceros.',

    'terminos_seccion5_titulo' => '5. Propiedad Intelectual',
    'terminos_seccion5_p1' => 'Todo el contenido, diseño, logos y tecnología de Verumax son propiedad exclusiva de la plataforma y están protegidos por leyes de propiedad intelectual.',

    'terminos_seccion6_titulo' => '6. Limitación de Responsabilidad',
    'terminos_seccion6_p1' => 'Verumax no será responsable de daños indirectos, incidentales o consecuentes derivados del uso o imposibilidad de uso del Servicio.',

    'terminos_seccion7_titulo' => '7. Contacto',
    'terminos_seccion7_p1' => 'Para consultas sobre estos Términos de Servicio, contáctenos en:',

    // Política de Privacidad - Contenido
    'privacidad_intro_titulo' => 'Introducción',
    'privacidad_intro_p1' => 'En Verumax, la privacidad y seguridad de sus datos es nuestra máxima prioridad. Esta Política de Privacidad describe cómo recopilamos, usamos, almacenamos y protegemos su información personal cuando utiliza nuestros servicios.',
    'privacidad_intro_p2' => 'Al utilizar Verumax, usted acepta las prácticas descritas en esta política. Si no está de acuerdo, no utilice nuestros servicios.',

    'privacidad_seccion1_titulo' => '1. Información que Recopilamos',
    'privacidad_seccion1_sub1_titulo' => '1.1 Información de Cuenta',
    'privacidad_seccion1_sub1_p1' => 'Cuando crea una cuenta, recopilamos:',
    'privacidad_seccion1_sub1_li1' => 'Nombre completo y datos de contacto (email, teléfono)',
    'privacidad_seccion1_sub1_li2' => 'Nombre de la institución, organización o profesional independiente',
    'privacidad_seccion1_sub1_li3' => 'Dirección física y fiscal',
    'privacidad_seccion1_sub1_li4' => 'Información de facturación y pago',
    'privacidad_seccion1_sub1_li5' => 'Credenciales de acceso (usuario/contraseña encriptada)',
    'privacidad_seccion1_sub2_titulo' => '1.2 Datos de Documentos y Beneficiarios',
    'privacidad_seccion1_sub2_p1' => 'Al emitir documentos, recopilamos datos de los beneficiarios (estudiantes, clientes, empleados, socios, etc.):',
    'privacidad_seccion1_sub2_li1' => 'Nombre completo y número de identificación (CI, DNI, etc.)',
    'privacidad_seccion1_sub2_li2' => 'Email y teléfono (para notificaciones)',
    'privacidad_seccion1_sub2_li3' => 'Datos académicos, profesionales o laborales relacionados con el documento emitido',
    'privacidad_seccion1_sub2_li4' => 'Fotografía (opcional, si se incluye en el documento)',
    'privacidad_seccion1_sub3_titulo' => '1.3 Datos de Uso y Técnicos',
    'privacidad_seccion1_sub3_li1' => 'Dirección IP, navegador, sistema operativo',
    'privacidad_seccion1_sub3_li2' => 'Páginas visitadas, tiempo de sesión, clics',
    'privacidad_seccion1_sub3_li3' => 'Logs de validación de documentos (quién validó, cuándo, desde dónde)',
    'privacidad_seccion1_sub3_li4' => 'Métricas de uso del portal (descargas, accesos, etc.)',

    'privacidad_seccion2_titulo' => '2. Cómo Usamos su Información',
    'privacidad_seccion2_p1' => 'Utilizamos los datos recopilados para:',
    'privacidad_seccion2_li1_strong' => 'Proveer el Servicio:',
    'privacidad_seccion2_li1_texto' => 'Generar, almacenar y gestionar documentos digitales',
    'privacidad_seccion2_li2_strong' => 'Validación:',
    'privacidad_seccion2_li2_texto' => 'Verificar la autenticidad de documentos mediante códigos QR',
    'privacidad_seccion2_li3_strong' => 'Notificaciones:',
    'privacidad_seccion2_li3_texto' => 'Enviar emails sobre documentos emitidos, actualizaciones del servicio',
    'privacidad_seccion2_li4_strong' => 'Facturación:',
    'privacidad_seccion2_li4_texto' => 'Procesar pagos y emitir facturas',
    'privacidad_seccion2_li5_strong' => 'Mejora del Servicio:',
    'privacidad_seccion2_li5_texto' => 'Analizar métricas de uso para optimizar funcionalidades',
    'privacidad_seccion2_li6_strong' => 'Soporte Técnico:',
    'privacidad_seccion2_li6_texto' => 'Resolver consultas y problemas técnicos',
    'privacidad_seccion2_li7_strong' => 'Cumplimiento Legal:',
    'privacidad_seccion2_li7_texto' => 'Cumplir con obligaciones legales y regulatorias',

    'privacidad_seccion3_titulo' => '3. Compartir Información con Terceros',
    'privacidad_seccion3_p1_strong' => 'No vendemos ni alquilamos',
    'privacidad_seccion3_p1_normal' => 'sus datos personales a terceros. Solo compartimos información en estos casos limitados:',
    'privacidad_seccion3_sub1_titulo' => '3.1 Proveedores de Servicios',
    'privacidad_seccion3_sub1_p1' => 'Trabajamos con proveedores confiables que nos ayudan a operar el Servicio:',
    'privacidad_seccion3_sub1_li1' => 'Hosting y almacenamiento en la nube (servidores seguros)',
    'privacidad_seccion3_sub1_li2' => 'Procesadores de pagos (con certificación PCI-DSS)',
    'privacidad_seccion3_sub1_li3' => 'Servicios de email transaccional',
    'privacidad_seccion3_sub1_li4' => 'Servicios de impresión y envío (solo para documentos físicos solicitados)',
    'privacidad_seccion3_sub1_p2' => 'Todos los proveedores están contractualmente obligados a proteger sus datos y no pueden usarlos para otros fines.',
    'privacidad_seccion3_sub2_titulo' => '3.2 Requerimientos Legales',
    'privacidad_seccion3_sub2_p1' => 'Podemos divulgar información si la ley lo requiere (orden judicial, proceso legal) o para proteger nuestros derechos legales.',
    'privacidad_seccion3_sub3_titulo' => '3.3 Validación Pública',
    'privacidad_seccion3_sub3_p1' => 'Los documentos emitidos son validables públicamente mediante código QR. La información mostrada en la validación (nombre del beneficiario, institución emisora, datos del documento) será visible para cualquier persona que escanee el código.',

    'privacidad_seccion4_titulo' => '4. Seguridad de los Datos',
    'privacidad_seccion4_p1' => 'Implementamos medidas de seguridad de nivel empresarial:',
    'privacidad_seccion4_li1_strong' => 'Encriptación SSL/TLS 256-bit:',
    'privacidad_seccion4_li1_texto' => 'Todas las comunicaciones están encriptadas',
    'privacidad_seccion4_li2_strong' => 'Contraseñas protegidas:',
    'privacidad_seccion4_li2_texto' => 'Almacenadas con hash y salt (bcrypt)',
    'privacidad_seccion4_li3_strong' => 'Backups automáticos diarios:',
    'privacidad_seccion4_li3_texto' => 'Con encriptación y almacenamiento redundante',
    'privacidad_seccion4_li4_strong' => 'Firewall y monitoreo 24/7:',
    'privacidad_seccion4_li4_texto' => 'Protección contra accesos no autorizados',
    'privacidad_seccion4_li5_strong' => 'Auditorías de seguridad:',
    'privacidad_seccion4_li5_texto' => 'Revisiones periódicas de vulnerabilidades',
    'privacidad_seccion4_li6_strong' => 'Acceso restringido:',
    'privacidad_seccion4_li6_texto' => 'Solo personal autorizado puede acceder a datos sensibles',
    'privacidad_seccion4_p2' => 'A pesar de estas medidas, ningún sistema es 100% seguro. Le recomendamos usar contraseñas fuertes y no compartir sus credenciales.',

    'privacidad_seccion5_titulo' => '5. Retención de Datos',
    'privacidad_seccion5_p1' => 'Conservamos sus datos mientras mantenga una cuenta activa o según lo requiera la ley:',
    'privacidad_seccion5_li1_strong' => 'Datos de cuenta:',
    'privacidad_seccion5_li1_texto' => 'Hasta que cancele su cuenta + período legal mínimo (generalmente 10 años para fines fiscales)',
    'privacidad_seccion5_li2_strong' => 'Documentos emitidos:',
    'privacidad_seccion5_li2_texto' => 'Permanentemente, ya que sirven como registro histórico y validación',
    'privacidad_seccion5_li3_strong' => 'Logs de validación:',
    'privacidad_seccion5_li3_texto' => '5 años para auditoría y prevención de fraude',
    'privacidad_seccion5_li4_strong' => 'Datos de facturación:',
    'privacidad_seccion5_li4_texto' => '10 años según normativas contables',
    'privacidad_seccion5_p2' => 'Al cancelar su cuenta, eliminamos datos innecesarios de forma segura, pero conservamos registros históricos según obligaciones legales.',

    'privacidad_seccion6_titulo' => '6. Sus Derechos',
    'privacidad_seccion6_p1' => 'Según las leyes de protección de datos personales, usted tiene derecho a:',
    'privacidad_seccion6_li1_strong' => 'Acceso:',
    'privacidad_seccion6_li1_texto' => 'Solicitar una copia de sus datos personales que tenemos almacenados',
    'privacidad_seccion6_li2_strong' => 'Rectificación:',
    'privacidad_seccion6_li2_texto' => 'Corregir datos inexactos o incompletos',
    'privacidad_seccion6_li3_strong' => 'Supresión:',
    'privacidad_seccion6_li3_texto' => 'Solicitar la eliminación de sus datos (sujeto a obligaciones legales)',
    'privacidad_seccion6_li4_strong' => 'Limitación:',
    'privacidad_seccion6_li4_texto' => 'Restringir ciertos usos de sus datos',
    'privacidad_seccion6_li5_strong' => 'Portabilidad:',
    'privacidad_seccion6_li5_texto' => 'Recibir sus datos en formato estructurado y transferible',
    'privacidad_seccion6_li6_strong' => 'Oposición:',
    'privacidad_seccion6_li6_texto' => 'Oponerse al procesamiento de sus datos en ciertas circunstancias',
    'privacidad_seccion6_li7_strong' => 'Revocación de consentimiento:',
    'privacidad_seccion6_li7_texto' => 'Retirar el consentimiento otorgado en cualquier momento',
    'privacidad_seccion6_p2_antes_link' => 'Para ejercer estos derechos, contáctenos en',
    'privacidad_seccion6_p2_link_texto' => 'privacidad@validarcert.com',
    'privacidad_seccion6_p2_normal' => 'Responderemos dentro de 15 días hábiles.',

    'privacidad_seccion7_titulo' => '7. Cookies y Tecnologías Similares',
    'privacidad_seccion7_p1' => 'Utilizamos cookies y tecnologías similares para:',
    'privacidad_seccion7_li1_strong' => 'Cookies esenciales:',
    'privacidad_seccion7_li1_texto' => 'Para el funcionamiento del portal (sesión, autenticación)',
    'privacidad_seccion7_li2_strong' => 'Cookies analíticas:',
    'privacidad_seccion7_li2_texto' => 'Para entender cómo usa el servicio y mejorarlo (anónimas)',
    'privacidad_seccion7_li3_strong' => 'Cookies de preferencias:',
    'privacidad_seccion7_li3_texto' => 'Para recordar sus configuraciones (idioma, tema, etc.)',
    'privacidad_seccion7_p2' => 'Usted puede configurar su navegador para rechazar cookies, aunque esto podría afectar la funcionalidad del Servicio.',

    'privacidad_seccion8_titulo' => '8. Transferencias Internacionales',
    'privacidad_seccion8_p1' => 'Sus datos se almacenan principalmente en servidores ubicados en Argentina. En algunos casos, proveedores de servicios pueden procesar datos en otros países con niveles adecuados de protección de datos (por ejemplo: Estados Unidos bajo el Data Privacy Framework, Unión Europea bajo GDPR).',

    'privacidad_seccion9_titulo' => '9. Privacidad de Menores',
    'privacidad_seccion9_p1' => 'Nuestro Servicio no está dirigido a menores de 13 años. Si descubrimos que hemos recopilado datos de un menor sin consentimiento parental, eliminaremos esa información inmediatamente.',
    'privacidad_seccion9_p2' => 'Para beneficiarios menores de edad cuyos documentos son emitidos por instituciones educativas, el consentimiento se presume otorgado por la institución que actúa en ejercicio de la patria potestad delegada o tutela académica.',

    'privacidad_seccion10_titulo' => '10. Cambios a esta Política',
    'privacidad_seccion10_p1' => 'Podemos actualizar esta Política de Privacidad ocasionalmente. Los cambios significativos serán notificados por email o mediante aviso destacado en el portal. La fecha de "Última actualización" en la parte superior indica cuándo se realizó la última modificación.',

    'privacidad_seccion11_titulo' => '11. Contacto',
    'privacidad_seccion11_p1' => 'Para consultas, ejercer sus derechos, o reportar problemas de privacidad:',
    'privacidad_seccion11_email_privacidad' => 'privacidad@validarcert.com',
    'privacidad_seccion11_email_general_label' => 'Email general:',
    'privacidad_seccion11_email_general' => 'contacto@validarcert.com',

    'privacidad_seccion12_titulo' => '12. Autoridad de Aplicación',
    'privacidad_seccion12_p1_antes_strong' => 'En Argentina, la autoridad de aplicación en materia de protección de datos personales es la',
    'privacidad_seccion12_p1_strong' => 'Agencia de Acceso a la Información Pública (AAIP)',
    'privacidad_seccion12_p1_normal' => '. Si considerás que tus derechos han sido vulnerados, podés presentar una denuncia ante este organismo.',
    'privacidad_seccion12_aaip_label' => 'AAIP:',
    'privacidad_seccion12_aaip_url' => 'www.argentina.gob.ar/aaip',

    // === ACADÉMICO PAGE ===

    // Navigation
    'acad_nav_beneficios' => 'Beneficios',
    'acad_nav_funcionalidades' => 'Funcionalidades',
    'acad_nav_casos_exito' => 'Casos de Éxito',
    'acad_nav_faq' => 'Preguntas Frecuentes',
    'acad_nav_solicitar_demo' => 'Solicitar Demo',
    'acad_nav_academico' => 'Académico',

    'acad_hero_badge' => '✓ Solución Académica Completa',
    'acad_hero_title' => 'Certificaciones Académicas',
    'acad_hero_title_highlight' => 'Digitales Profesionales',
    'acad_hero_subtitle' => 'Solución completa para',
    'acad_hero_instituciones' => 'instituciones educativas',
    'acad_hero_centros_formacion' => 'centros de formación',
    'acad_hero_academias' => 'academias',
    'acad_hero_formadores' => 'formadores particulares',
    'acad_cta_solicitar_demo' => 'Solicitar Demo Personalizada',
    'acad_cta_ver_como_funciona' => 'Ver Cómo Funciona',

    // Hero Stats
    'acad_hero_stat_tiempo' => 'Menos tiempo administrativo',
    'acad_hero_stat_portal' => 'Portal del estudiante',
    'acad_hero_stat_falsificaciones' => 'Falsificaciones posibles',

    // Problemas Section
    'acad_problemas_titulo' => '¿Te suena familiar?',
    'acad_problemas_subtitulo' => 'Estos son los dolores de cabeza que Verumax elimina',
    'acad_problema_trabajo_manual' => 'Horas de Trabajo Manual',
    'acad_problema_trabajo_manual_desc' => 'Diseñar y emitir cada certificado individualmente consume tiempo valioso que podrías dedicar a la enseñanza.',
    'acad_problema_perdidos' => 'Certificados Perdidos',
    'acad_problema_perdidos_desc' => 'Alumnos que pierden o dañan documentos y solicitan reemisiones constantemente.',
    'acad_problema_falsificaciones' => 'Falsificaciones',
    'acad_problema_falsificaciones_desc' => 'Títulos y certificados falsos circulando sin forma efectiva de verificar su autenticidad.',
    'acad_problema_trazabilidad' => 'Sin Trazabilidad',
    'acad_problema_trazabilidad_desc' => 'Falta de historial académico completo y verificable de cada estudiante.',
    'acad_problema_costos' => 'Costos de Impresión',
    'acad_problema_costos_desc' => 'Gastos elevados en papel especial, impresión, tóner y almacenamiento físico.',
    'acad_problema_archivos' => 'Archivos Físicos Caóticos',
    'acad_problema_archivos_desc' => 'Montañas de papeles ocupando espacio valioso y dificultando la búsqueda de información.',

    // Cómo Funciona Section
    'acad_como_funciona_titulo' => 'Tan simple como 1, 2, 3',
    'acad_como_funciona_subtitulo' => 'Implementación inmediata, sin complicaciones técnicas',
    'acad_como_funciona_paso1_titulo' => 'Configure su Institución',
    'acad_como_funciona_paso1_desc' => 'Personalice con tu logo, colores institucionales y defina los tipos de certificados que emitirá.',
    'acad_como_funciona_paso2_titulo' => 'Cargue Estudiantes y Cursos',
    'acad_como_funciona_paso2_desc' => 'Importe datos masivamente desde Excel o CSV. También puedes cargar uno por uno.',
    'acad_como_funciona_paso3_titulo' => 'Emita y Valide',
    'acad_como_funciona_paso3_desc' => 'Generación automática con QR único. Notificación por email y acceso inmediato para estudiantes.',

    // Tipos de Documentos
    'acad_documentos_titulo' => 'Tipos de Documentos Académicos',
    'acad_documentos_subtitulo' => 'Todos los documentos que tu institución necesita emitir',
    'acad_documentos_principales' => 'Documentos Principales',
    'acad_doc_certificado_aprobacion' => 'Certificados de Aprobación',
    'acad_doc_certificado_aprobacion_desc' => 'Certificado oficial que acredita la aprobación de un curso, materia o programa completo.',
    'acad_doc_diplomas' => 'Diplomas de Finalización',
    'acad_doc_diplomas_desc' => 'Título o diploma formal que certifica la culminación exitosa de un programa académico completo.',
    'acad_doc_analiticos' => 'Analíticos / Registros Académicos',
    'acad_doc_analiticos_desc' => 'Historial completo con todas las materias cursadas, calificaciones, asistencias y competencias adquiridas.',
    'acad_doc_constancia_regular' => 'Constancias de Alumno Regular',
    'acad_doc_constancia_regular_desc' => 'Documento que acredita que el estudiante está actualmente cursando en la institución.',
    'acad_doc_constancia_inscripcion' => 'Constancias de Inscripción',
    'acad_doc_constancia_inscripcion_desc' => 'Comprobante de inscripción a un curso, materia o programa académico específico.',
    'acad_doc_constancia_finalizacion' => 'Constancias de Finalización de Cursada',
    'acad_doc_constancia_finalizacion_desc' => 'Certificado que acredita haber completado la cursada, previo a la evaluación final.',

    // Documentos Complementarios
    'acad_documentos_complementarios' => 'Documentos Complementarios',
    'acad_doc_asistencia' => 'Certificados de Asistencia',
    'acad_doc_asistencia_desc' => 'Para talleres, seminarios, webinars o eventos educativos puntuales.',
    'acad_doc_reconocimientos' => 'Reconocimientos y Menciones',
    'acad_doc_reconocimientos_desc' => 'Premios especiales, menciones honoríficas o reconocimientos por desempeño destacado.',
    'acad_doc_competencias' => 'Certificados de Competencias',
    'acad_doc_competencias_desc' => 'Acreditan habilidades y competencias específicas adquiridas durante la formación.',
    'acad_doc_practica' => 'Constancias de Práctica Profesional',
    'acad_doc_practica_desc' => 'Documentan pasantías, prácticas profesionales o experiencia laboral supervisada.',
    'acad_doc_congresos' => 'Certificados de Participación en Congresos',
    'acad_doc_congresos_desc' => 'Para asistencia o ponencias en congresos, jornadas académicas y conferencias.',

    // Portal del Estudiante
    'acad_portal_badge' => '★ Feature Destacado',
    'acad_portal_titulo' => 'Portal del Estudiante 24/7',
    'acad_portal_subtitulo' => 'Cada estudiante tiene acceso a su propio portal, personalizado con la identidad visual y el logo de su institución. Desde allí, pueden ver su progreso y descargar todos sus documentos.',
    'acad_portal_acceso_titulo' => 'Acceso 24/7 a su trayectoria completa',
    'acad_portal_acceso_desc' => 'Estudiantes acceden desde cualquier dispositivo, en cualquier momento.',
    'acad_portal_descarga_titulo' => 'Descarga de todos sus documentos',
    'acad_portal_descarga_desc' => 'Diplomas, constancias, certificados, analíticos - todo en un solo lugar.',
    'acad_portal_timeline_titulo' => 'Vista de timeline académico',
    'acad_portal_timeline_desc' => 'Visualización cronológica de toda su trayectoria educativa.',
    'acad_portal_qr_titulo' => 'QR individual por documento',
    'acad_portal_qr_desc' => 'Cada documento tiene su código único de validación.',
    'acad_portal_linkedin_titulo' => 'Compartir en LinkedIn con un clic',
    'acad_portal_linkedin_desc' => 'Integración directa para publicar logros académicos.',

    // Portal Demo Data
    'acad_portal_demo_nombre' => 'Juan Pérez',
    'acad_portal_demo_ci' => 'CI: 12.345.678',
    'acad_portal_demo_progreso' => 'de 4 cursos completados',
    'acad_portal_demo_diploma' => 'Diploma - Justicia Restaurativa',
    'acad_portal_demo_diploma_fecha' => 'Finalizado: 15/03/2024',
    'acad_portal_demo_certificado' => 'Certificado - Mediación',
    'acad_portal_demo_certificado_fecha' => 'Finalizado: 20/01/2024',
    'acad_portal_demo_curso_progreso' => 'Curso en Progreso',
    'acad_portal_demo_curso_nombre' => 'Resolución de Conflictos',

    // Casos de Uso
    'acad_casos_uso_titulo' => '¿Para Quién es Verumax Académico?',
    'acad_casos_uso_subtitulo' => 'Instituciones y profesionales que confían en nuestra plataforma',
    'acad_caso_universidades' => 'Universidades y Terciarios',
    'acad_caso_universidades_desc' => 'Gestión masiva de títulos, diplomas y analíticos para cientos de graduados.',
    'acad_caso_centros' => 'Centros de Formación',
    'acad_caso_centros_desc' => 'Instituciones como SAJuR y Liberté que emiten certificaciones profesionales.',
    'acad_caso_idiomas' => 'Academias de Idiomas',
    'acad_caso_idiomas_desc' => 'Certificados de niveles completados con validación internacional.',
    'acad_caso_tecnicos' => 'Institutos Técnicos',
    'acad_caso_tecnicos_desc' => 'Certificaciones técnicas y oficios con trazabilidad completa.',
    'acad_caso_laboral' => 'Capacitación Laboral',
    'acad_caso_laboral_desc' => 'Centros de formación continua y desarrollo profesional.',
    'acad_caso_continua' => 'Educación Continua',
    'acad_caso_continua_desc' => 'Programas de actualización profesional y posgrados.',
    'acad_caso_organizadores' => 'Organizadores de Cursos',
    'acad_caso_organizadores_desc' => 'Diplomas y certificados para cursos, talleres y programas especiales.',
    'acad_caso_particulares' => 'Formadores Particulares',
    'acad_caso_particulares_desc' => 'Docentes independientes que emiten certificaciones profesionales.',

    // Funcionalidades
    'acad_func_titulo' => 'Funcionalidades Pensadas para Instituciones',
    'acad_func_subtitulo' => 'Todo lo que necesitas para gestionar certificaciones académicas',
    'acad_func_cohortes' => 'Gestión de Cohortes',
    'acad_func_cohortes_desc' => 'Organiza estudiantes por camada, año o grupo. Emite documentos masivamente por cohorte completa.',
    'acad_func_emision_masiva' => 'Emisión Masiva',
    'acad_func_emision_masiva_desc' => 'Genera certificados para 100+ alumnos en minutos. Un solo clic para toda una promoción.',
    'acad_func_notificaciones' => 'Notificaciones Automáticas por Email',
    'acad_func_notificaciones_desc' => 'Cada estudiante recibe notificación automática cuando se emite un documento.',
    'acad_func_branding' => 'Portal con Branding Institucional',
    'acad_func_branding_desc' => 'Tu logo, colores y dominio. Cada institución proyecta su propia identidad.',
    'acad_func_trayectoria' => 'Trayectoria Académica Completa',
    'acad_func_trayectoria_desc' => 'Historial verificable con todos los cursos, calificaciones y logros del estudiante.',
    'acad_func_validacion' => 'Validación Pública Instantánea',
    'acad_func_validacion_desc' => 'Empleadores escanean el QR y verifican autenticidad al instante.',

    // Beneficios
    'acad_beneficios_titulo' => 'Resultados Medibles',
    'acad_beneficios_subtitulo' => 'Impacto real en tu institución desde el primer día',
    'acad_beneficio_tiempo_titulo' => 'Menos Tiempo Administrativo',
    'acad_beneficio_tiempo_desc' => 'Lo que tomaba horas ahora toma minutos',
    'acad_beneficio_ahorro_titulo' => 'Ahorro en Costos',
    'acad_beneficio_ahorro_desc' => 'Reducción drástica en impresión y papelería',
    'acad_beneficio_falsificaciones_titulo' => 'Falsificaciones Posibles',
    'acad_beneficio_falsificaciones_desc' => 'Imposible clonar códigos QR únicos',
    'acad_beneficio_acceso_titulo' => 'Acceso para Estudiantes',
    'acad_beneficio_acceso_desc' => 'Portal disponible en todo momento',
    'acad_beneficio_trazabilidad_titulo' => '100% Trazabilidad y Auditoría',
    'acad_beneficio_trazabilidad_desc' => 'Cada acción queda registrada. Sabés exactamente quién emitió qué documento, cuándo y para quién. Ideal para auditorías y cumplimiento normativo.',

    // Casos de Éxito
    'acad_casos_exito_titulo' => 'Casos de Éxito',
    'acad_casos_exito_subtitulo' => 'Instituciones que transformaron su gestión académica',
    'acad_caso_sajur_nombre' => 'Sociedad Argentina de Justicia Restaurativa',
    'acad_caso_sajur_tipo' => 'Centro de formación especializada',
    'acad_caso_sajur_testimonio' => '"Pasamos de procesar manualmente cada certificado a emitir decenas en minutos. Nuestros estudiantes valoran poder acceder a su trayectoria completa 24/7, y los empleadores confían en la validación QR. El ahorro en tiempo administrativo fue del 90%."',
    'acad_caso_liberte_nombre' => 'Cooperativa de Trabajo Liberté',
    'acad_caso_liberte_tipo' => 'Formación profesional y capacitación',
    'acad_caso_liberte_testimonio' => '"La implementación fue instantánea. En menos de 24 horas ya estábamos emitiendo certificados con nuestra marca. El portal personalizado proyecta una imagen profesional que nuestros estudiantes comparten con orgullo. La opción de impresión premium es el toque final perfecto."',

    // Antes vs Después
    'acad_antes_despues_titulo' => 'Antes vs Después de Verumax',
    'acad_antes_despues_subtitulo' => 'La transformación digital de tu gestión académica',
    'acad_antes_titulo' => 'Antes (Tradicional)',
    'acad_antes_trabajo_manual' => 'Horas de trabajo manual por cada certificado',
    'acad_antes_costos' => 'Costos elevados de impresión y papelería',
    'acad_antes_falsificacion' => 'Riesgo de falsificación sin forma de verificar',
    'acad_antes_presencial' => 'Estudiantes deben venir presencialmente a retirar',
    'acad_antes_almacenamiento' => 'Almacenamiento físico caótico y espacio ocupado',
    'acad_antes_estadisticas' => 'Sin estadísticas ni métricas de emisión',
    'acad_despues_titulo' => 'Después (Verumax)',
    'acad_despues_emision' => 'Emisión masiva en segundos',
    'acad_despues_emision_highlight' => 'con un solo clic',
    'acad_despues_ahorro' => 'Ahorro del 85%',
    'acad_despues_ahorro_highlight' => 'en costos operativos',
    'acad_despues_validacion' => 'Validación QR imposible de falsificar',
    'acad_despues_acceso' => 'Acceso 24/7',
    'acad_despues_acceso_highlight' => 'desde cualquier dispositivo',
    'acad_despues_digital' => 'Todo digital y en la nube,',
    'acad_despues_digital_highlight' => 'sin papeles ni espacio',
    'acad_despues_dashboards' => 'Dashboards y reportes en tiempo real',

    // Integraciones
    'acad_integraciones_titulo' => 'Integraciones y Compatibilidad',
    'acad_integraciones_subtitulo' => 'Se adapta a tu flujo de trabajo existente',
    'acad_integ_excel' => 'Excel / CSV',
    'acad_integ_excel_desc' => 'Importación masiva de estudiantes y cursos desde archivos Excel.',
    'acad_integ_api' => 'API REST',
    'acad_integ_api_desc' => 'Integración con sistemas SIU, Moodle y plataformas académicas.',
    'acad_integ_email' => 'Email Institucional',
    'acad_integ_email_desc' => 'Notificaciones desde tu dominio institucional (@tuinstituto.edu).',
    'acad_integ_subdominios' => 'Subdominios',
    'acad_integ_subdominios_desc' => 'Portal en tu propio dominio: certificados.tuinstituto.edu',

    // FAQ
    'acad_faq_titulo' => 'Preguntas Frecuentes',
    'acad_faq_subtitulo' => 'Todo lo que necesitas saber sobre Verumax Académico',
    'acad_faq_cargo_titulo' => '¿Cómo cargo la información de mis estudiantes?',
    'acad_faq_cargo_resp' => 'Podés cargar estudiantes de dos formas: individualmente desde el panel de administración, o masivamente importando un archivo Excel/CSV con todos los datos. Te proporcionamos una plantilla para facilitar el proceso.',
    'acad_faq_validez_titulo' => '¿Los certificados digitales tienen validez legal?',
    'acad_faq_validez_resp' => 'Sí, los certificados digitales tienen la misma validez legal que los físicos en Argentina. Además, ofrecemos opción de impresión premium con papel especial y elementos de seguridad para instituciones que lo requieran.',
    'acad_faq_diseno_titulo' => '¿Puedo personalizar completamente el diseño?',
    'acad_faq_diseno_resp' => 'Absolutamente. Podés configurar tu logo, colores institucionales, firmas digitales y todo el branding. Cada certificado se genera con tu identidad visual.',
    'acad_faq_acceso_titulo' => '¿Qué pasa si un estudiante pierde el acceso a su portal?',
    'acad_faq_acceso_resp' => 'El estudiante puede recuperar su acceso usando su CI y un proceso de verificación por email. Además, como administrador de la institución, podés regenerar el acceso en cualquier momento.',
    'acad_faq_validacion_titulo' => '¿Cómo valida un empleador el certificado?',
    'acad_faq_validacion_resp' => 'El empleador simplemente escanea el código QR del certificado con su celular. Será redirigido automáticamente a una página de validación que muestra todos los datos del certificado y la trayectoria académica del estudiante.',
    'acad_faq_retroactivos_titulo' => '¿Puedo emitir certificados retroactivos?',
    'acad_faq_retroactivos_resp' => 'Sí, podés cargar y emitir certificados de promociones anteriores sin ningún problema. El sistema permite indicar fechas pasadas de emisión.',
    'acad_faq_limite_titulo' => '¿Hay límite de emisiones?',
    'acad_faq_limite_resp' => 'No hay límite de emisiones. Podés generar tantos certificados como necesites. Los planes se ajustan según la cantidad de estudiantes activos en tu institución.',

    // CTA Final
    'acad_cta_final_titulo' => 'Transforma la Gestión Académica de tu Institución',
    'acad_cta_final_desc' => 'Unite a las instituciones que ya ahorraron miles de horas administrativas y proyectan una imagen profesional con certificaciones digitales.',
    'acad_cta_final_demo' => 'Solicitar Demo Personalizada',
    'acad_cta_final_contactar' => 'Contactar Ventas',
    'acad_cta_final_implementacion' => 'Implementación',
    'acad_cta_final_menos_tiempo' => 'Menos tiempo',
    'acad_cta_final_certificados' => 'Certificados',

    // Footer
    'acad_footer_tagline' => 'Certificaciones Digitales Profesionales',
    'acad_footer_derechos' => '© 2025 Verumax. Todos los derechos reservados.',
    'acad_footer_inicio' => 'Inicio',
    'acad_footer_terminos' => 'Términos',
    'acad_footer_privacidad' => 'Privacidad',

    'acad_meta_title' => 'Verumax Académico - Certificaciones Digitales para Instituciones Educativas',
    'acad_meta_description' => 'Solución completa de certificaciones digitales para instituciones educativas, centros de formación y formadores particulares. Emisión masiva, validación QR y portal del estudiante.',
    'acad_meta_keywords' => 'certificados académicos, diplomas digitales, analíticos digitales, instituciones educativas, formación profesional',
    'acad_meta_og_title' => 'Verumax Académico - Certificaciones para Instituciones Educativas',
    'acad_meta_og_description' => 'Emití certificados, diplomas y analíticos digitales con validación QR. Portal del estudiante 24/7 y emisión masiva automatizada.',
    'acad_meta_twitter_title' => 'Verumax Académico - Certificaciones para Instituciones Educativas',
    'acad_meta_twitter_description' => 'Emití certificados, diplomas y analíticos digitales con validación QR. Portal del estudiante 24/7 y emisión masiva automatizada.',

    // ===== PÁGINA PERFILES PRO (VERSIÓN TARJETA DIGITAL PROTAGONISTA) =====
    'prof_meta_title' => 'Tarjeta Digital Profesional con QR Infalsificable | Verumax',
    'prof_meta_description' => 'Tu tarjeta de contacto digital profesional con QR dinámico e infalsificable. Landing page personalizada, panel de administración seguro y actualización instantánea.',
    'prof_meta_keywords' => 'tarjeta digital, qr infalsificable, tarjeta de contacto digital, landing page profesional, networking digital',
    'prof_meta_og_title' => 'Tarjeta Digital: La Evolución de tu Tarjeta de Visita',
    'prof_meta_og_description' => 'Olvidate de las tarjetas de papel. Tu identidad profesional en una tarjeta digital con QR verificable, landing page personalizada y gestión en tiempo real.',
    'prof_meta_twitter_title' => 'Tarjeta Digital Profesional by Verumax',
    'prof_meta_twitter_description' => 'La tarjeta de visita del futuro. QR infalsificable, landing page incluida y actualización instantánea.',

    'prof_nav_perfiles' => 'Tarjeta Digital',
    'prof_nav_como_funciona' => 'Cómo Funciona',
    'prof_nav_caracteristicas' => 'Características',
    'prof_nav_planes' => 'Planes',
    'prof_nav_empezar' => 'Crear Mi Tarjeta',

    'prof_hero_badge' => '✓ La Tarjeta de Visita del Siglo XXI',
    'prof_hero_title' => 'Tu Tarjeta Digital Profesional',
    'prof_hero_title_highlight' => 'Con QR Infalsificable',
    'prof_hero_subtitle' => 'Olvidate del papel. Una tarjeta digital en formato JPG con QR dinámico que lleva a tu landing page personalizada. Actualizá tus datos al instante desde un panel seguro.',
    'prof_hero_url_ejemplo' => 'Tu URL personalizada:',
    'prof_hero_url_ejemplo_subdomain' => 'tunombre',
    'prof_hero_url_ejemplo_domain' => '.verumax.com',
    'prof_cta_empezar' => 'Ver Planes y Crear Mi Tarjeta',
    'prof_cta_secundario' => 'Ver Cómo Funciona',

    // Sección Hero - Estadísticas
    'prof_stat_qr' => 'QR Infalsificable',
    'prof_stat_qr_desc' => 'Tecnología blockchain',
    'prof_stat_actualizacion' => 'Actualización',
    'prof_stat_actualizacion_desc' => 'En tiempo real',
    'prof_stat_landing' => 'Tu Landing Page',
    'prof_stat_landing_desc' => 'Incluida en todos los planes',

    // Sección: ¿Qué es la Tarjeta Digital?
    'prof_que_es_titulo' => '¿Qué es la Tarjeta Digital?',
    'prof_que_es_subtitulo' => 'La evolución definitiva de la tarjeta de visita tradicional',
    'prof_que_es_desc' => 'Una imagen JPG de alta calidad (formato tarjeta de visita) con un código QR único e infalsificable. Al escanear el QR, tus contactos acceden a tu landing page personalizada con toda tu información profesional: foto, datos de contacto, servicios, horarios y mucho más.',

    'prof_tarjeta_feature1_titulo' => 'Imagen JPG Lista para Usar',
    'prof_tarjeta_feature1_desc' => 'Descargá tu tarjeta en alta resolución y compartila por WhatsApp, email, redes sociales o imprimila en papel de calidad.',
    'prof_tarjeta_feature2_titulo' => 'QR Dinámico e Infalsificable',
    'prof_tarjeta_feature2_desc' => 'El QR no se puede clonar ni copiar. Si alguien intenta replicar tu tarjeta, el código no funcionará. Tecnología de verificación única.',
    'prof_tarjeta_feature3_titulo' => 'Landing Page Incluida',
    'prof_tarjeta_feature3_desc' => 'Tu URL personalizada (ej: juanperez.verumax.com) con diseño profesional, tu foto, datos de contacto, servicios, horarios y más.',
    'prof_tarjeta_feature4_titulo' => 'Panel de Administración',
    'prof_tarjeta_feature4_desc' => 'Actualizá tu información al instante. Cambios en tiempo real sin necesidad de reimprimir o reenviar tu tarjeta.',

    // Sección: Cómo Funciona
    'prof_como_titulo' => 'Cómo Funciona en 3 Pasos',
    'prof_como_subtitulo' => 'De la contratación a tu tarjeta digital en minutos',
    'prof_como_paso1' => 'Elegí tu Plan y Personalizá',
    'prof_como_paso1_desc' => 'Seleccioná el plan que mejor se adapte a vos. Cargá tus datos (nombre, foto, contacto, servicios) y elegí tu paleta de colores entre nuestras opciones preestablecidas.',
    'prof_como_paso2' => 'Descargá tu Tarjeta JPG',
    'prof_como_paso2_desc' => 'Tu tarjeta digital está lista en alta resolución con tu QR único e infalsificable. Descargala y compartila por donde quieras: WhatsApp, email, LinkedIn o imprimila.',
    'prof_como_paso3' => 'Actualizá Cuando Deseé',
    'prof_como_paso3_desc' => 'Desde tu panel de administración seguro, modificá tus datos las veces que necesites. Los cambios son instantáneos y tu QR siempre apunta a la información actualizada.',

    // Sección: Características Estrella
    'prof_caracteristicas_titulo' => 'Por Qué Nuestra Tarjeta Digital es Única',
    'prof_caracteristicas_subtitulo' => 'Tecnología y diseño pensados para profesionales exigentes',

    'prof_caract_qr_titulo' => 'QR Infalsificable y Dinámico',
    'prof_caract_qr_desc' => 'No es un QR estático común. Es un código verificable que no puede ser clonado. Si alguien copia tu tarjeta, el QR no funcionará. Además, podés cambiar el destino del QR sin necesidad de regenerar la imagen.',
    'prof_caract_panel_titulo' => 'Panel de Administración Intuitivo',
    'prof_caract_panel_desc' => 'Accedé desde cualquier dispositivo a tu panel seguro. Actualizá tu foto, datos de contacto, servicios, horarios y más. Sin conocimientos técnicos, 100% visual y amigable.',
    'prof_caract_paletas_titulo' => 'Paletas de Colores Profesionales',
    'prof_caract_paletas_desc' => 'Elegí entre 12 combinaciones de colores preestablecidas diseñadas por profesionales. Desde elegantes y minimalistas hasta vibrantes y creativas. Tu marca, tu estilo.',
    'prof_caract_landing_titulo' => 'Landing Page Profesional Incluida',
    'prof_caract_landing_desc' => 'Tu subdominio personalizado (tunombre.verumax.com) con diseño responsivo, optimizado para móviles. Foto de perfil, información de contacto, descripción de servicios, horarios de atención y botones de acción directa (WhatsApp, email, teléfono).',
    'prof_caract_formatos_titulo' => 'Múltiples Formatos de Uso',
    'prof_caract_formatos_desc' => 'JPG en alta resolución para imprimir, PDF para enviar por email, y versión optimizada para redes sociales. Una sola tarjeta, todos los usos que necesites.',
    'prof_caract_seguridad_titulo' => 'Seguridad y Respaldo 24/7',
    'prof_caract_seguridad_desc' => 'Tus datos están protegidos con encriptación de nivel bancario. Backups automáticos diarios. Tu información siempre segura y disponible.',

    // Sección: Casos de Uso
    'prof_casos_titulo' => '¿Para Quién es la Tarjeta Digital?',
    'prof_casos_subtitulo' => 'Profesionales de todas las industrias que valoran la primera impresión',

    'prof_caso_abogados' => 'Abogados y Consultores',
    'prof_caso_abogados_desc' => 'Entregá tu tarjeta con QR a tus clientes. Ellos escanean y acceden a tus áreas de práctica, horarios de atención y formulario de consulta.',
    'prof_caso_medicos' => 'Médicos y Profesionales de la Salud',
    'prof_caso_medicos_desc' => 'Tu tarjeta con especialidades, horarios de consultorio, obras sociales que aceptás y botón directo para agendar turnos.',
    'prof_caso_arquitectos' => 'Arquitectos y Diseñadores',
    'prof_caso_arquitectos_desc' => 'Compartí tu tarjeta y que tus prospectos vean tu portfolio visual en tu landing page personalizada.',
    'prof_caso_comercios' => 'Comercios y Emprendedores',
    'prof_caso_comercios_desc' => 'Tu tarjeta comercial con horarios, ubicación, catálogo de productos/servicios y botón de WhatsApp para consultas.',
    'prof_caso_coaches' => 'Coaches y Capacitadores',
    'prof_caso_coaches_desc' => 'Mostrá tus servicios, testimonios, y permitiles a tus clientes agendar sesiones directamente desde tu landing.',
    'prof_caso_freelancers' => 'Trabajadores Freelance y Creativos',
    'prof_caso_freelancers_desc' => 'Tu tarjeta digital con enlaces a tu portfolio, redes sociales y tarifas. Impresión profesional garantizada.',
    'prof_caso_productores' => 'Productores de Alimentos',
    'prof_caso_productores_desc' => 'Compartí tu tarjeta con certificaciones de calidad, trazabilidad de productos y catálogo. El QR lleva a tus clientes a toda tu información verificada.',
    'prof_caso_artesanos' => 'Artesanos y Manualidades',
    'prof_caso_artesanos_desc' => 'Mostrá tu trabajo artesanal con galería de fotos, precios y contacto directo. Perfecta para ferias, mercados y clientes particulares.',
    'prof_caso_trainers' => 'Personal Trainers y Nutricionistas',
    'prof_caso_trainers_desc' => 'Tu tarjeta con especialidades, planes disponibles, horarios y sistema de agendamiento. Tus clientes reservan turnos directamente desde tu landing.',

    // Sección: Planes y Precios
    'prof_planes_titulo' => 'Elegí el Plan que Mejor se Adapta a Vos',
    'prof_planes_subtitulo' => 'Todos los planes incluyen tu Tarjeta Digital con QR infalsificable y landing page personalizada',

    'prof_plan_esencial_titulo' => 'Basicum',
    'prof_plan_esencial_desc' => 'Tu tarjeta digital profesional con lo esencial para comenzar a impresionar.',
    'prof_plan_esencial_precio' => '$9 USD',
    'prof_plan_esencial_periodo' => '/ Anual',
    'prof_plan_esencial_feat1' => 'Tarjeta Digital JPG con QR Infalsificable',
    'prof_plan_esencial_feat2' => 'Subdominio Personalizado (tunombre.verumax.com)',
    'prof_plan_esencial_feat3' => 'Panel de Administración Seguro',
    'prof_plan_esencial_feat4' => '5 Paletas de Colores Preestablecidas',
    'prof_plan_esencial_feat5' => 'Datos de Contacto y Horarios',
    'prof_plan_esencial_feat6' => 'Botones de Acción Directa (WhatsApp, Email, Tel)',
    'prof_plan_esencial_feat7' => 'Actualización Ilimitada de Información',
    'prof_plan_esencial_cta' => 'Comenzar con Esencial',

    'prof_plan_plus_badge' => 'Más Popular',
    'prof_plan_plus_titulo' => 'Premium',
    'prof_plan_plus_desc' => 'Todo lo del plan Basicum más herramientas avanzadas para destacar y vender más.',
    'prof_plan_plus_precio' => '$19 USD',
    'prof_plan_plus_periodo' => '/ Anual',
    'prof_plan_plus_feat1_strong' => 'Todo lo del plan Basicum, más:',
    'prof_plan_plus_feat2' => '12 Paletas de Colores Premium',
    'prof_plan_plus_feat3' => 'Galería de Fotos de Servicios (hasta 100 imágenes HD)',
    'prof_plan_plus_feat4' => 'Sección de Servicios Detallada',
    'prof_plan_plus_feat5' => 'Video de Presentación Personal',
    'prof_plan_plus_feat6' => 'Formulario de Contacto Integrado',
    'prof_plan_plus_feat7' => 'Estadísticas de Escaneos del QR',
    'prof_plan_plus_feat8' => 'Generador de CV Inteligente (PDF y Web)',
    'prof_plan_plus_feat9' => 'Sistema de Agendamiento de Citas (Calendly)',
    'prof_plan_plus_feat10' => 'Integración con Credenciales Verificadas',
    'prof_plan_plus_cta' => 'Obtener Plan Premium',

    'prof_plan_pro_badge' => 'Profesional',
    'prof_plan_pro_titulo' => 'Excellens',
    'prof_plan_pro_desc' => 'Para profesionales que necesitan herramientas completas de gestión y presencia digital.',
    'prof_plan_pro_precio' => '$49 USD',
    'prof_plan_pro_periodo' => '/ Anual',
    'prof_plan_pro_feat1_strong' => 'Todo lo del plan Premium, más:',
    'prof_plan_pro_feat2' => 'Portfolio de Proyectos Ilimitado',
    'prof_plan_pro_feat3' => 'Múltiples Páginas Personalizadas',
    'prof_plan_pro_feat4' => 'Analíticas Avanzadas y Reportes',
    'prof_plan_pro_feat5' => 'Exportación de Contactos',
    'prof_plan_pro_feat6' => 'Integraciones API Personalizadas',
    'prof_plan_pro_feat7' => 'Soporte Prioritario 24/7',
    'prof_plan_pro_feat8' => 'Estadísticas y Métricas Avanzadas',
    'prof_plan_pro_cta' => 'Obtener Plan Excellens',

    'prof_plan_elite_badge' => 'Empresarial',
    'prof_plan_elite_titulo' => 'Supremus',
    'prof_plan_elite_desc' => 'La solución definitiva con dominio propio y personalización total para tu marca.',
    'prof_plan_elite_precio' => '$99 USD',
    'prof_plan_elite_periodo' => '/ Anual',
    'prof_plan_elite_feat1_strong' => 'Todo lo del plan Excellens, más:',
    'prof_plan_elite_feat2' => 'Dominio Propio Incluido (tunombre.com)',
    'prof_plan_elite_feat3' => 'SSL Premium y Certificados de Seguridad',
    'prof_plan_elite_feat4' => 'Diseño 100% Personalizado a Medida',
    'prof_plan_elite_feat5' => 'Integración con Tu Identidad Corporativa',
    'prof_plan_elite_feat6' => 'Subdominios Ilimitados para Tu Equipo',
    'prof_plan_elite_feat7' => 'Sistema de Roles y Permisos Avanzado',
    'prof_plan_elite_feat8' => 'Gerente de Cuenta Dedicado',
    'prof_plan_elite_cta' => 'Obtener Plan Supremus',

    // Sección: CTA Final
    'prof_cta_final_titulo' => 'Dejá Atrás las Tarjetas de Papel',
    'prof_cta_final_desc' => 'Unite a miles de profesionales que ya impresionan con su Tarjeta Digital infalsificable.',
    'prof_cta_final_btn' => 'Crear Mi Tarjeta Ahora',
    'prof_cta_final_garantia' => '✓ Sin costos ocultos  •  ✓ Cancelación en cualquier momento  •  ✓ Soporte incluido',

    // Sección: Formas de Pago
    'prof_pagos_titulo' => 'Formas de Pago',
    'prof_pagos_subtitulo' => 'Métodos seguros y convenientes para tu país',
    'prof_pagos_argentina' => 'Métodos de Pago en Argentina',
    'prof_pagos_internacional' => 'Pago Internacional',
    'prof_pago_mercadopago' => 'MercadoPago',
    'prof_pago_mercadopago_desc' => 'Tarjeta de crédito, débito y efectivo',
    'prof_pago_pagofacil' => 'PagoFácil',
    'prof_pago_pagofacil_desc' => 'Pago en efectivo en cualquier sucursal',
    'prof_pago_transferencia' => 'Transferencia Bancaria',
    'prof_pago_transferencia_desc' => 'CBU/CVU para pesos argentinos',
    'prof_pago_paypal' => 'PayPal',
    'prof_pago_paypal_desc' => 'Tarjetas y moneda local en todo el mundo',

    // === META TAGS === //

    // Index.php Meta Tags
    'meta_keywords' => 'credenciales digitales, validación QR, marca personal verificada, asistentes IA, prestigio digital, certificaciones infalsificables',
    'meta_author' => 'Verumax',
    'meta_og_title' => 'Verumax - Crea, Gestiona y Valida tu Prestigio Digital',
    'meta_og_description' => 'Ecosistema de herramientas para emitir credenciales infalsificables, construir tu marca personal verificada e implementar asistentes de IA especializados.',
    'meta_twitter_title' => 'Verumax - Tu Prestigio Digital Verificado',
    'meta_twitter_description' => 'Herramientas para emitir credenciales infalsificables, construir tu marca personal y asistentes IA especializados.',

    // Academico.php Meta Tags
    'acad_meta_title' => 'Verumax Académico - Certificaciones Digitales para Instituciones Educativas',
    'acad_meta_description' => 'Solución completa de certificaciones digitales para instituciones educativas, centros de formación y formadores particulares. Emisión masiva, validación QR y portal del estudiante.',
    'acad_meta_keywords' => 'certificados académicos, diplomas digitales, analíticos digitales, instituciones educativas, formación profesional',
    'acad_meta_og_title' => 'Verumax Académico - Certificaciones para Instituciones Educativas',
    'acad_meta_og_description' => 'Emite certificados, diplomas y analíticos digitales con validación QR. Portal del estudiante 24/7 y emisión masiva automatizada.',
    'acad_meta_twitter_title' => 'Verumax Académico - Certificaciones para Instituciones Educativas',
    'acad_meta_twitter_description' => 'Emite certificados, diplomas y analíticos digitales con validación QR. Portal del estudiante 24/7 y emisión masiva automatizada.',

    // Privacidad.php Meta Tags
    'privacidad_meta_description' => 'Política de Privacidad de Verumax. Conocé cómo recopilamos, usamos y protegemos tus datos personales.',
    'privacidad_meta_og_title' => 'Política de Privacidad - Verumax',
    'privacidad_meta_og_description' => 'Información detallada sobre cómo Verumax protege tu privacidad y maneja tus datos personales.',
    'privacidad_meta_twitter_title' => 'Política de Privacidad - Verumax',
    'privacidad_meta_twitter_description' => 'Información detallada sobre cómo Verumax protege tu privacidad y maneja tus datos personales.',

    // Terminos.php Meta Tags
    'terminos_meta_description' => 'Términos de Servicio de Verumax. Conocé las condiciones de uso de nuestra plataforma de certificaciones digitales.',
    'terminos_meta_og_title' => 'Términos de Servicio - Verumax',
    'terminos_meta_og_description' => 'Condiciones legales para el uso de la plataforma Verumax y sus servicios de certificación digital.',
    'terminos_meta_twitter_title' => 'Términos de Servicio - Verumax',
    'terminos_meta_twitter_description' => 'Condiciones legales para el uso de la plataforma Verumax y sus servicios de certificación digital.',

];
?>