<?php
declare(encoding='UTF-8');
// Euskera - eu_ES
$lang = [
    // Meta
    'meta_title' => 'Verumax - QR Balidazioarekin Dokumentazioa Sektorerako',
    'meta_description' => 'Hezkuntza-erakundeentzat, profesionalentzat, ekitaldientzat, enpresentzat, kooperatibentzat eta elkarteentzat dokumentu digitalak emititzeko eta balidatzeko soluzioak.',

    // Header/Navigation
    'nav_inicio' => 'Hasiera',
    'nav_categorias' => 'Kategoriak',
    'nav_beneficios' => 'Abantailak',
    'nav_faq' => 'FAQ',
    'nav_validar' => 'Balidatu',
    'nav_demo' => 'Eskatu Demoa',

    // Hero Section
    'hero_badge' => 'Mundu osoko erakunde eta profesionalen konfiantza irabazita',
    'hero_title' => 'QR Balidazioa duen Dokumentazioa',
    'hero_subtitle' => 'Hezkuntza-erakundeentzat, profesional independenteentzat, ekitaldi-antolatzaileentzat, enpresentzat, kooperatibentzat eta elkarteentzat dokumentu digitalak emititzeko eta balidatzeko soluzioak. QR balidazio faltsutegaitza eta atari pertsonalizatua.',
    'hero_cta_primary' => 'Arakatu Soluzioak',
    'hero_cta_secondary' => 'Balidatu Dokumentua',

    // Hero Mockup Mobile
    'hero_mockup_certificado' => 'Ziurtagiria',
    'hero_mockup_curso' => 'Justizia Berrezartzailea',
    'hero_mockup_estudiante' => 'Juan Pérez - DI 12345678',
    'hero_mockup_verificado' => '✓ Egiaztatua',
    'hero_mockup_valido' => '2026 arte baliozkoa',
    'hero_mockup_ver_detalles' => 'Xehetasunak Ikusi',
    'hero_mockup_certificados' => 'Ziurtagiriak',
    'hero_mockup_en_curso' => 'Ikasten',

    // Categorías Section
    'cat_title' => 'Industriarako Soluzioak',
    'cat_subtitle' => 'Aukeratu zure sektorea bere beharretarako egokitutako soluzio perfektua aurkitzeko',

    'cat_academico' => 'Akademikoa',
    'cat_academico_1' => 'Hezkuntza-Erakundeak',
    'cat_academico_2' => 'Formazio-Zentroak',
    'cat_academico_3' => 'Irakasle Partikularrak',
    'cat_academico_cta' => 'Ikusi Soluzioa →',

    'cat_profesional' => 'Profesionala',
    'cat_profesional_1' => 'Osasuna eta Ongizatea',
    'cat_profesional_2' => 'Ingeniaritza eta Arkitektura',
    'cat_profesional_3' => 'Profesional Guztiak',

    'cat_eventos' => 'Ekitaldiak',
    'cat_eventos_1' => 'Kongresuak eta Hitzaldiak',
    'cat_eventos_2' => 'Jaleginak eta Kontzertuak',
    'cat_eventos_3' => 'Sarrera-Kontrola',

    'cat_empresarial' => 'Enpresariala',
    'cat_empresarial_1' => 'Bermeak eta Egiaztagiriak',
    'cat_empresarial_2' => 'Kalitate-Ziurtagiriak',
    'cat_empresarial_3' => 'Ordainagiriak',

    'cat_cooperativas' => 'Kooperatibak',
    'cat_cooperativas_1' => 'Kideen Kredentzialak',
    'cat_cooperativas_2' => 'Partaidetzaren Ziurtagiriak',
    'cat_cooperativas_3' => 'Jardueren Agiriak',

    'cat_mutuales' => 'Elkarteak',
    'cat_mutuales_1' => 'Elkartekideen Kredentzialak',
    'cat_mutuales_2' => 'Zerbitzuen Agiriak',
    'cat_mutuales_3' => 'Onurak dituzten Txartelak',

    'cat_proximamente' => 'Laster',
    'cat_footer' => 'Kategoria gehiago laster.',
    'cat_footer_link' => 'Galdetu iezaguzu',
    'cat_footer_text' => 'zure sektorea zerrendan ez badago.',

    'cat_artistas' => 'Artistak',
    'cat_artistas_1' => 'Margolariak',
    'cat_artistas_2' => 'Artesanuak',
    'cat_artistas_3' => 'Argazkilariak',

    // Servicios Principales
    'servicios_title' => 'Gure Zerbitzu Nagusiak',
    'servicios_subtitle' => 'Gure erakunde guztiek dituzten funtzionalitate esentzialak, zein sektoretan dauden ez du axola',

    'serv_antifraude' => 'Segurtasun Anti-Frode Osoa',
    'serv_antifraude_desc' => 'QR kode bakunak eta faltsutu ezinak zeinak dokumentu bakoitzaren egiazkotasuna bermatzen dutenak.',

    'serv_portal' => '24/7 Ataria',
    'serv_portal_desc' => 'Sarbide iraunkorra ikasleentzat, bezeroentzat, kideentzat edo langileentzat edozein gailutik.',

    'serv_impresion' => 'Premium Inprimaketa',
    'serv_impresion_desc' => 'Kalitate handiko dokumentu fisikoak hologramak eta laminazioa dituztenak, etxera bidalia.',

    'serv_branding' => 'Pertsonalizatuko Branding-a',
    'serv_branding_desc' => 'Ataria eta dokumentuak zure logoa, koloreak eta diseinu instituzional bakana dituztenak.',

    'serv_emision' => 'Emate Masiboa',
    'serv_emision_desc' => 'Egin ehunka dokumentu bat-batean jakinarazpen berehalakoa izanda.',

    'serv_validacion' => 'Balidazio-Ataria',
    'serv_validacion_desc' => 'Edonor balioztatu dezake zure dokumentuen egiazkotasuna berehala.',

    // Casos de Éxito
    'casos_title' => 'Arrakasten Kasuak',
    'casos_subtitle' => 'Verumax-en konfiantza duten erakundeak eta profesionalak',

    'caso_sajur_org' => 'Justizia Berrezartzaileko Gizarte Elkartea',
    'caso_sajur_tipo' => 'Hezkuntza-espezializatuko erakundea',
    'caso_sajur_texto' => '"Eskuz ziurtagiri bakoitza prozesatzetik hamarreka ematera pasatu ginen minutu gutxitan. Gure ikasleek euren ibilbide osoa 24/7 atzitu ahal izatea baloratzen dute, eta enpleatzaileek QR balidazioan konfiantza dute. Administrazio-denboraren aurreztea %90koa izan da."',

    'caso_liberte_org' => 'Liberté Lan Taldeko Kooperatiba',
    'caso_liberte_tipo' => 'Hezkuntza profesionala eta prestakuntza',
    'caso_liberte_texto' => '"Inplementazioa berehalakoa izan zen. 24 ordur baino gutxiagoan ziurtagiriak jada gure markarekin ari ginen ematen. Pertsonalizatuko atariak irudi profesionala ematen dio gure irteerari, ikasleek harrotziaz partekatzen dutena. Premium inprimaketa aukera bikaina da."',

    'caso_nutricion_org' => 'Maria Gonzalez Lizentziatua',
    'caso_nutricion_tipo' => 'Nutrizionista profesional independentea',
    'caso_nutricion_texto' => '"Orain nire nutrizio-planek QR kodea dute nire pazienteek balioztatu ahal izateko. Honek konfiantza handiagoa sortu du eta autentifikazioari buruzko galderak murriztu ditu. Gainera, bidalketa fisikoa premiuma bikaina da nahi izaten dutenentzat inprimatuta izateko."',

    'caso_empresa_org' => 'TechVision S.A.',
    'caso_empresa_tipo' => 'Teknologia-enpresa',
    'caso_empresa_texto' => '"Verumax erabiltzen dugu gure produktuen bermeak QR bidez egiaztatu daitezkeelarik. Gure bezeroek egiazkotasuna berehala baliozta dezakete eta informazio teknikoa guztia atzitu. Faltsutzeen inguruko erreklamazioen murrizketa %95ekoa izan da."',

    // FAQ
    'faq_title' => 'Galdera Ohikoak',
    'faq_subtitle' => 'Verumax-i buruz jakin beharreko guztia',

    'faq_1_q' => 'Zenbat denboratan behar du Verumax inplementatzeko?',
    'faq_1_a' => '24 ordur baino gutxiago. Zure marka (logoa eta koloreak) konfiguratu besterik ez duzu egin behar, zure datuak kargatu eta ematen hasteko. Urratsez urrats gidatutako onboardinga dakar.',

    'faq_2_q' => 'Dokumentu digitalak benetako balio juridikoa dute?',
    'faq_2_a' => 'Bai. Dokumentu digitalak balio juridiko osoa dute. Gainera, gure QR sistemak egiazkotasuna berehala egiaztatzeko aukera ematen du, dokumentu fisiko ohikoei ezinezkoa dena.',

    'faq_3_q' => 'Eta dokumentu fisiko bertsioa behar badut?',
    'faq_3_a' => 'Premium inprimaketa zerbitzua eskaintzen dugu hologramen eta laminazio segurua duten HD inprimaketarekin, posta arrastreagarrian bidalia. Zuzenean zure ataletik eskatu dezakezu eta bidalketaren jarraipena egingo dizu.',

    'faq_4_q' => 'Nola funtzionatzen du QR bidezko balidazioak?',
    'faq_4_a' => 'Dokumentu bakoitzak QR kode bakarra dauka zeinak zure markarekin pertsonalizatutako balidazio-atarira bidaltzen duen. Hor bertan dokumentuaren informazio osoa eta bere ibilbidea erakusten da. Ezin da faltsutu edo aldatu.',

    'faq_5_q' => 'Dokumentuen diseinua pertsonalizatu dezaket?',
    'faq_5_a' => 'Bai, %100ean. Erakunde edo profesional bakoitzak markaren logoa, koloreak eta diseinua erabat pertsonalizatutako ataria dauka. Dokumentuek zure ikus-identitate bakana islatzen dute.',

    'faq_6_q' => 'Plataforma erabiltzeko ezagutza teknikorik behar dut?',
    'faq_6_a' => 'Ez. Plataforma estremez intuitiboa da. Interneten nabigatzeko gai bazara, arazorik gabe kudeatu ahal izango duzu Verumax. Gainera, laguntza tekniko osoa eskaintzen dugu.',

    'faq_7_q' => 'Eta nire datuei buruz? Seguruak al dira?',
    'faq_7_a' => 'Segurtasun absolutua. Banku-mailako enkriptazioa erabiltzen dugu, eguneroko babeskopia automatikoak eta datu-pribatutasunaren arauak betetzen ditugu. Zure datuak artxibo fisiko batean baino seguruago daude.',

    // Validar Documento Section
    'validar_title' => 'Dokumentu bat balidatu',
    'validar_subtitle' => 'Sartu dokumentuan agertzen den balidazio-kodea (formatua: VALID-XXXXXXXXXXXX)',
    'validar_placeholder' => 'VALID-XXXXXXXXXXXX',
    'validar_btn' => 'Balidatu Orain',
    'validar_ejemplo' => 'Adibidea: VALID-A1B2C3D4E5F6',

    // Contacto Section
    'contacto_title' => 'Hasi Gaur Bertan Dokumentu Profesionalak Erosten',
    'contacto_subtitle' => 'Jar zaitez gurekin harremanetan demo pertsonalizatu batengatik eta ikusi nola alda dezakeen Verumax-ek zure dokumentuen kudeaketa.',
    'contacto_nombre' => 'Izen Osoa',
    'contacto_email' => 'Posta elektronikoa',
    'contacto_institucion' => 'Erakundea/Antolaketa',
    'contacto_mensaje' => 'Esaiguzu zure beharrari buruz...',
    'contacto_btn' => 'Eskatu Demoa',
    'contacto_info' => 'Edo idatzi iezaguzu zuzenean:',

    // Footer
    'footer_descripcion' => 'QR balidazioa duten dokumentu digital eta fisikoen plataforma definitiboa.',
    'footer_enlaces' => 'Esteka Azkarrak',
    'footer_caracteristicas' => 'Ezaugarriak',
    'footer_contacto' => 'Harremana',
    'footer_seguridad' => 'Enpresa Mailako Teknologia eta Segurtasuna',
    'footer_copyright' => '© 2025 Verumax. Eskubide guztiak erreserbatuta.',
    'footer_terminos' => 'Zerbitzu-baldintzak',
    'footer_privacidad' => 'Pribatutasun-politika',

    // Badges de Seguridad
    'badge_ssl' => 'SSL',
    'badge_ssl_desc' => '256-bit Enkriptazioa',
    'badge_https' => 'HTTPS',
    'badge_https_desc' => 'Konexio Segurua',
    'badge_privacidad' => 'Pribatutasuna',
    'badge_privacidad_desc' => 'Babestutako Datuak',
    'badge_backup' => 'Babeskopia',
    'badge_backup_desc' => 'Eguneroko Automatikoa',
    'badge_uptime' => 'Erabilgarritasuna %99,9',
    'badge_uptime_desc' => 'Erabilgarritasuna',
    'badge_soporte' => 'Laguntza',
    'badge_soporte_desc' => 'Laguntza 24/7',

    // Estadísticas Hero
    'stat_uptime' => 'Erabilgarritasuna',
    'stat_documentos' => 'Emititako dokumentuak',
    'stat_acceso' => 'Sarrera erabilgarri',
    'stat_ahorro' => 'Administrazio-kostenetan aurreztea',

    // Social Proof Contacto
    'social_confianza' => 'Verumax-en konfiantza duten erakunde eta profesionalak',
    'social_mas' => '+ erakunde eta profesional gehiago',

    // Beneficios Contacto
    'benefit_demo' => 'Doako demoa konpromisorik gabe',
    'benefit_demo_desc' => 'Probatu funtzio guztiak',
    'benefit_implementacion' => '24 orduko inplementazioa',
    'benefit_implementacion_desc' => 'Hasi bihar ematen',
    'benefit_soporte' => 'Sartutako laguntza teknikoa',
    'benefit_soporte_desc' => 'Laguntza osoa',

    // CTA Contacto
    'contacto_cta_btn' => 'Eskatu Doako Demoa',
    'contacto_cta_email' => 'Edo idatzi iezaguzu hona',

    // Footer - Enlaces rápidos
    'footer_link_beneficios' => 'Abantailak',
    'footer_link_como' => 'Nola Funtzionatzen Du',
    'footer_link_validar' => 'Balidatu Dokumentua',
    'footer_link_demo' => 'Eskatu Demoa',

    // Footer - Características
    'footer_feat_qr' => 'QR Balidazioa',
    'footer_feat_portal' => '24/7 Ataria',
    'footer_feat_impresion' => 'Premium Inprimaketa',
    'footer_feat_personalizable' => '%100 Pertsonalizagarria',

    // Footer - Contacto
    'footer_horario' => 'Al - Ol: 9:00 - 18:00',

    // Página de Privacidad
    'privacidad_title' => 'Pribatutasun-politika',
    'privacidad_updated' => 'Azken eguneraketa',

    // Términos de Servicio
    'terminos_title' => 'Zerbitzu-baldintzak',
    'terminos_updated' => 'Azken eguneraketa',

    // Términos de Servicio - Contenido
    'terminos_seccion1_titulo' => '1. Baldintzak Onartzea',
    'terminos_seccion1_p1' => 'Verumax plataformara sartzen eta erabiltzen duzunean (\"Zerbitzua\"), baldintza horiek juridikoki lotzen zaituela onartzen duzu. Baldintza horiekin ados ez bazaude, ez erabili Zerbitzua.',
    'terminos_seccion1_p2' => 'Verumax-ek eskubidea gordetzen du baldintza horiek edozein unetan aldatzeko. Aldaketak webgunean argitaratzen diren bezain laster sartzen dira indarrean.',

    'terminos_seccion2_titulo' => '2. Zerbitzuaren Deskribapena',
    'terminos_seccion2_p1' => 'Verumax hezkuntza-erakundeek, profesional independenteek, ekitaldi-antolatzaileek, enpresek, kooperatibek eta elkarteek QR berrespen-kodeak dituzten dokumentu digitalak igorri, kudeatu eta balidatzeko aukera ematen duen plataforma da.',
    'terminos_seccion2_p2' => 'Zerbitzuak hauek ditu, besteak beste:',
    'terminos_seccion2_li1' => 'Pertsonalizatutako dokumentu digitalen igorpena',
    'terminos_seccion2_li2' => 'Erakunde/profesional bakoitzerako pertsonalizatutako ataria',
    'terminos_seccion2_li3' => 'QR kode bakunak dituen balidazio-sistema',
    'terminos_seccion2_li4' => 'Hodeian biltegiratze segurua',
    'terminos_seccion2_li5' => 'Dokumentu fisikoen premium inprimaketa-aukera',
    'terminos_seccion2_li6' => 'Dokumentuen igorpen masiboa',

    'terminos_seccion3_titulo' => '3. Erregistroa eta Erabiltzaile-Kontua',
    'terminos_seccion3_p1' => 'Zerbitzua erabiltzeko, informazio zehatza, osoa eta eguneratua emanez kontu bat sortu behar duzu. Honakoak dira zure erantzukizunak:',
    'terminos_seccion3_li1' => 'Zure pasahitza eta sarbide-kredentzialak isilik mantentzea',
    'terminos_seccion3_li2' => 'Zure kontuaren pean gertatzen diren jarduera guztiak',
    'terminos_seccion3_li3' => 'Zure kontuaren baimenik gabeko erabilera berehalako jakinaraztea',
    'terminos_seccion3_li4' => 'Zure erakundeari edo antolaketari buruzko datu zuzenak ematea',
    'terminos_seccion3_p2' => 'Verumax-ek eskubidea gordetzen du baldintza horiek hausten dituzten kontuak etenda edo bertan behera uzteko edo informazio faltsua ematen dutenak.',

    'terminos_seccion4_titulo' => '4. Baimendutako Erabilpena',
    'terminos_seccion4_p1' => 'Zerbitzua helburu legitimoekin eta baldintza horiekin bat etortzeko soilik erabil daiteke. Debekatuta dago Verumax jarduera iruzurtarako, ilegalentzat jo direnak edo hirugarrenen eskubideak hausteko erabiltzea.',

    'terminos_seccion5_titulo' => '5. Jabetza Intelektuala',
    'terminos_seccion5_p1' => 'Verumax-en eduki, diseinu, logo eta teknologia guztiak plataformaren jabetza esklusiboa dira eta jabetza intelektualaren legeek babesten dituzte.',

    'terminos_seccion6_titulo' => '6. Erantzukizunaren Mugaketa',
    'terminos_seccion6_p1' => 'Verumax ez da erantzule izango Zerbitzuaren erabileraren ondorioz edo erabil ezinezkoagatik eragindako kalte zeharkariei, fortuitoei edo ondorioei buruz.',

    'terminos_seccion7_titulo' => '7. Harremana',
    'terminos_seccion7_p1' => 'Zerbitzu-baldintzei buruzko kontsultak egiteko, jar zaitez gurekin harremanetan:',

    // Política de Privacidad - Contenido
    'privacidad_intro_titulo' => 'Sarrera',
    'privacidad_intro_p1' => 'Verumax-en, zure datuen pribatutasuna eta segurtasuna dira gure lehentasun nagusia. Pribatutasun-politika honek deskribatzen du nola bildu, erabili, gorde eta babesten ditugun zure informazio pertsonala gure zerbitzuak erabiltzen dituzunean.',
    'privacidad_intro_p2' => 'Verumax erabiltzen duzunean, politika horretan deskribatutako praktikak onartzen dituzu. Ez bazaude ados, ez erabili gure zerbitzurik.',

    'privacidad_seccion1_titulo' => '1. Bildutako Informazioa',
    'privacidad_seccion1_sub1_titulo' => '1.1 Kontuari Buruzko Informazioa',
    'privacidad_seccion1_sub1_p1' => 'Kontu bat sortzen duzunean, hauxe biltzen dugu:',
    'privacidad_seccion1_sub1_li1' => 'Izen osoa eta harremanetarako datuak (posta elektronikoa, telefonoa)',
    'privacidad_seccion1_sub1_li2' => 'Erakundearen, antolaketaren edo profesional independentearen izena',
    'privacidad_seccion1_sub1_li3' => 'Helbide fisikoa eta fiskala',
    'privacidad_seccion1_sub1_li4' => 'Fakturazio eta ordainketari buruzko informazioa',
    'privacidad_seccion1_sub1_li5' => 'Sarbide-kredentzialak (enkriptatutako erabiltzaile/pasahitza)',

    'privacidad_seccion1_sub2_titulo' => '1.2 Dokumentuei eta Onbenefiziariei Buruzko Datuak',
    'privacidad_seccion1_sub2_p1' => 'Dokumentuak igortzean, onbenefizarien datuak biltzen ditugu (ikasleak, bezeroak, langileak, kideak, etab.):',
    'privacidad_seccion1_sub2_li1' => 'Izen osoa eta identifikazio-zenbakia (DNI, CUIT, etab.)',
    'privacidad_seccion1_sub2_li2' => 'Posta elektronikoa eta telefonoa (jakinarazpenetarako)',
    'privacidad_seccion1_sub2_li3' => 'Dokumentuaren igorpenarekin lotutako datu akademikoak, profesionalak edo lanekoak',
    'privacidad_seccion1_sub2_li4' => 'Argazkia (hautazkoa, dokumentuan sartzen bada)',

    'privacidad_seccion1_sub3_titulo' => '1.3 Erabilpen eta Datu Teknikoak',
    'privacidad_seccion1_sub3_li1' => 'IP helbidea, nabigatzailea, sistema eragilea',
    'privacidad_seccion1_sub3_li2' => 'Bisitatutako orrialdeak, saioaren iraupena, klikak',
    'privacidad_seccion1_sub3_li3' => 'Dokumentuen balidazio-erregistroak (nork balidatu duen, noiz eta nondik)',
    'privacidad_seccion1_sub3_li4' => 'Atariaren erabilpen-metriak (deskargak, sarrerak, etab.)',

    'privacidad_seccion2_titulo' => '2. Nola Erabiltzen Dugun Zure Informazioa',
    'privacidad_seccion2_p1' => 'Bildutako datuak honetarako erabiltzen ditugu:',
    'privacidad_seccion2_li1_strong' => 'Zerbitzua Hornitzea:',
    'privacidad_seccion2_li1_texto' => 'Dokumentu digitalak sortu, gorde eta kudeatzea',
    'privacidad_seccion2_li2_strong' => 'Balidazioa:',
    'privacidad_seccion2_li2_texto' => 'QR kodeen bidez dokumentuen egiazkotasuna egiaztatzea',
    'privacidad_seccion2_li3_strong' => 'Jakinarazpenak:',
    'privacidad_seccion2_li3_texto' => 'Igorritako dokumentuei buruzko posta elektronikoak bidaltzea, zerbitzuaren eguneraketak',
    'privacidad_seccion2_li4_strong' => 'Fakturazioa:',
    'privacidad_seccion2_li4_texto' => 'Ordainketak prozesatzea eta fakturak igortzea',
    'privacidad_seccion2_li5_strong' => 'Zerbitzuaren Hobekuntza:',
    'privacidad_seccion2_li5_texto' => 'Erabilpen-metriak aztertzea funtzionalitateak hobetzeko',
    'privacidad_seccion2_li6_strong' => 'Laguntza Teknikoa:',
    'privacidad_seccion2_li6_texto' => 'Kontsultak eta arazo teknikoak ebaztea',
    'privacidad_seccion2_li7_strong' => 'Betekoa Legez:',
    'privacidad_seccion2_li7_texto' => 'Legezko eta erregulatzaile-beteketak betetzea',

    'privacidad_seccion3_titulo' => '3. Hirugarrenekin Partekatutako Informazioa',
    'privacidad_seccion3_p1_antes_strong' => '',
    'privacidad_seccion3_p1_strong' => 'Ez dugu salten ezta alokatzen',
    'privacidad_seccion3_p1_despues_strong' => ' zure datu pertsonalak hirugarrenei. Soilik kasu mugatuetan partekatzen dugu informazioa:',
    'privacidad_seccion3_sub1_titulo' => '3.1 Zerbitzu-Hornitzaileak',
    'privacidad_seccion3_sub1_p1' => 'Zerbitzua funtzionatzeko laguntzen diguten hornitzaile fidagarriekin lan egiten dugu:',
    'privacidad_seccion3_sub1_li1' => 'Hodeiko ostatua eta biltegia (zerbitzari seguruak)',
    'privacidad_seccion3_sub1_li2' => 'Ordainketa-prozesatzaileak (PCI-DSS ziurtagiria)',
    'privacidad_seccion3_sub1_li3' => 'Transakzio-posta elektroniko zerbitzuak',
    'privacidad_seccion3_sub1_li4' => 'Inprimatze eta bidalketa-zerbitzuak (eskatutako dokumentu fisikoentzat soilik)',
    'privacidad_seccion3_sub1_p2' => 'Hornitzaile guztiak kontratuzko moduan derrigorrezkoak dira zure datuak babesteko eta ezin dituzte beste helburuetarako erabili.',

    'privacidad_seccion3_sub2_titulo' => '3.2 Legezko Beteketak',
    'privacidad_seccion3_sub2_p1' => 'Norbaitek eskatzen badu (epaiketa-agondua, prozedura legala) edo gure eskubide legalak babesteko behar izanez gero, informazioa eztabaidatu dezakegu.',

    'privacidad_seccion3_sub3_titulo' => '3.3 Balidazio Publikoa',
    'privacidad_seccion3_sub3_p1' => 'Igorritako dokumentuak publikoki balidatu daitezke QR kodearen bidez. Balidazioan erakutsitako informazioa (onbenefizariaren izena, igorleen erakundea, dokumentuaren datuak) kodea eskaneatzen duen edonorentzat ikusgai egongo da.',

    'privacidad_seccion4_titulo' => '4. Datuen Segurtasuna',
    'privacidad_seccion4_p1' => 'Enpresa-mailako segurtasun-neurriak inplementatzen ditugu:',
    'privacidad_seccion4_li1_strong' => 'SSL/TLS 256-bit Enkriptazioa:',
    'privacidad_seccion4_li1_texto' => 'Komunikazio guztiak enkriptatuak daude',
    'privacidad_seccion4_li2_strong' => 'Pasahitzak babestuta:',
    'privacidad_seccion4_li2_texto' => 'Hash eta salt (bcrypt) bidez gordeta',
    'privacidad_seccion4_li3_strong' => 'Eguneroko babeskopia automatikoak:',
    'privacidad_seccion4_li3_texto' => 'Enkriptatzea eta biltegi erredundantea erabilita',
    'privacidad_seccion4_li4_strong' => 'Suebakia eta 24/7 monitorizazioa:',
    'privacidad_seccion4_li4_texto' => 'Baimenik gabeko sarbideetatik babestea',
    'privacidad_seccion4_li5_strong' => 'Segurtasun-auditoretzak:',
    'privacidad_seccion4_li5_texto' => 'Ahultasunen ebaluazio periodikoak',
    'privacidad_seccion4_li6_strong' => 'Sarbide mugatua:',
    'privacidad_seccion4_li6_texto' => 'Langile baimenduek soilik atzitu ditzakete datu sentikorrak',
    'privacidad_seccion4_p2' => 'Neurri horiek ere badira ere, ez dago %100 segurua den sistamarik. Pasahitz sendoak erabiltzea gomendatzen dizugu eta ez dituzu zure kredentzialak partekatu behar.',

    'privacidad_seccion5_titulo' => '5. Datuen Atxikapena',
    'privacidad_seccion5_p1' => 'Zure datuak kontu aktibo bat mantentzen duzun bitartean edo legez beharrezkoa den artean biltzen ditugu:',
    'privacidad_seccion5_li1_strong' => 'Kontuaren datuak:',
    'privacidad_seccion5_li1_texto' => 'Zure kontua bertan behera utzi arte + gutxieneko epe legala (normalean 10 urte zerga-helburuetarako)',
    'privacidad_seccion5_li2_strong' => 'Igorritako dokumentuak:',
    'privacidad_seccion5_li2_texto' => 'Betirako, erregistro historikoa eta balidazio gisa zerbitzari guztietan',
    'privacidad_seccion5_li3_strong' => 'Balidazio-erregistroak:',
    'privacidad_seccion5_li3_texto' => '5 urte auditoretarako eta iruzurren prebentziorako',
    'privacidad_seccion5_li4_strong' => 'Fakturazioko datuak:',
    'privacidad_seccion5_li4_texto' => '10 urte kontabilitate-arauen arabera',
    'privacidad_seccion5_p2' => 'Zure kontua bertan behera uztean, behar ez diren datuak modu seguruan ezabatzen ditugu, baina betiere legezko beteketak diren bitartean historiako erregistroak mantentzen ditugu.',

    'privacidad_seccion6_titulo' => '6. Zure Eskubideak',
    'privacidad_seccion6_p1' => 'Datuen babesari buruzko legeen arabera, honako eskubide hauek dituzu:',
    'privacidad_seccion6_li1_strong' => 'Sarbidea:',
    'privacidad_seccion6_li1_texto' => 'Gurekin gordeta daukazun zure datu pertsonalen kopia bat eskatzea',
    'privacidad_seccion6_li2_strong' => 'Zuzenketa:',
    'privacidad_seccion6_li2_texto' => 'Baliogabeak edo osatu gabeak dauden datuak zuzentzea',
    'privacidad_seccion6_li3_strong' => 'Ezabaketa:',
    'privacidad_seccion6_li3_texto' => 'Zure datuak ezabatzea eskatzea (legezko beteketen mende)',
    'privacidad_seccion6_li4_strong' => 'Mugaketa:',
    'privacidad_seccion6_li4_texto' => 'Zure datuen erabilera jakin batzuk mugatzea',
    'privacidad_seccion6_li5_strong' => 'Eramangarritasuna:',
    'privacidad_seccion6_li5_texto' => 'Zure datuak formatu egituratuan eta transferigarrian jasotzea',
    'privacidad_seccion6_li6_strong' => 'Auzipena:',
    'privacidad_seccion6_li6_texto' => 'Zure datuen tratamenduari dagokionez auzitea egin ahal izatea egoera jakin batzuetan',
    'privacidad_seccion6_li7_strong' => 'Baimenaren ezeztapena:',
    'privacidad_seccion6_li7_texto' => 'Emandako baimena edozein unetan kentzea',
    'privacidad_seccion6_p2_antes_email' => 'Eskubide horiek arikatzeko, jar zaitez gurekin harremanetan',
    'privacidad_seccion6_p2_despues_email' => '15 egun baino lehenago erantzuten dizugu',

    'privacidad_seccion7_titulo' => '7. Cookie-ak eta Antzeko Teknologiak',
    'privacidad_seccion7_p1' => 'Cookie-ak eta antzeko teknologiak erabiltzen ditugu honetarako:',
    'privacidad_seccion7_li1_strong' => 'Beharrezko cookie-ak:',
    'privacidad_seccion7_li1_texto' => 'Atariaren funtzionamendurako (saioa, autentifikazioa)',
    'privacidad_seccion7_li2_strong' => 'Analitikako cookie-ak:',
    'privacidad_seccion7_li2_texto' => 'Zerbitzua nola erabiltzen den ulertzeko eta hobetzeko (anonimoak)',
    'privacidad_seccion7_li3_strong' => 'Hobespenetarako cookie-ak:',
    'privacidad_seccion7_li3_texto' => 'Zure konfigurazioak gogoratzeko (hizkuntza, gaia, etab.)',
    'privacidad_seccion7_p2' => 'Zure nabigatzailea konfiguratu dezakezu cookie-ak ukatzeko, nahiz eta horrek Zerbitzuaren funtzionalitatea eragina izan dezakeen.',

    'privacidad_seccion8_titulo' => '8. Nazioarteko Transferentziak',
    'privacidad_seccion8_p1' => 'Zure datuak, normalean, Espainiako zerbitzarietan gordetzen dira. Zenbait kasutan, zerbitzu-hornitzaileek datuak beste herrialdeetan prozesatu ditzakete datu-babes maila egokia duten tokietan (adibidez: Ameriketako Estatu Batuak Data Privacy Framework-en arabera, Europar Batasuna GDPR-ren arabera).',

    'privacidad_seccion9_titulo' => '9. Umeen Pribatutasuna',
    'privacidad_seccion9_p1' => 'Gure Zerbitzua ez dago 13 urte baino gazteagoak direnentzat pentsatuta. Haurrentzako baimenik gabe daturik bildu dugunean, berehalakoan ezabatuko dugu informazio hori.',
    'privacidad_seccion9_p2' => 'Hamahiru urte baino gazteagoak diren onbenefizarien dokumentuak hezkuntza-erakundeek igotzen dituztenean, baimena erakundeak emandakoan ulertzen da, zuzendaritza delegatuaren edo hezkuntza-tutelaren eraginez.',

    'privacidad_seccion10_titulo' => '10. Politika Honen Aldaketak',
    'privacidad_seccion10_p1' => 'Aldi baterako Pribatutasun-politika hau eguneratu dezakegu. Aldaketa esanguratsuak posta elektroniko bidez edo atarian ohar nabarmena jarrita jakinaraziko dizugu. Goiko \"Azken eguneraketa\" datak erakusten du noiz egin zen azken aldaketa.',

    'privacidad_seccion11_titulo' => '11. Harremana',
    'privacidad_seccion11_p1' => 'Kontsultak egiteko, eskubideak arikatzeko edo pribatutasun-arazoak salatzeko:',
    'privacidad_seccion11_email_label' => 'Posta elektroniko orokorra:',

    'privacidad_seccion12_titulo' => '12. Aplikazio-Erabaki Emateko Erakundea',
    'privacidad_seccion12_p1_antes_strong' => 'Espainian, datu pertsonalen babesari dagokionez',
    'privacidad_seccion12_p1_strong' => 'Aurreneko Erakundea Datuen Babesaren Esku-hartzearen',
    'privacidad_seccion12_p1_despues_strong' => 'Agenzia Estatuko Datu Pertsonalen Babeserako Erakundea (AEPD) da. Zure eskubideak urratu egin direla uste baduzu, erakunde horretan salatu ahal duzu.',
    'privacidad_seccion12_aaip_label' => 'AEPD:',
    'privacidad_seccion12_aaip_url' => 'www.aepd.es',

    // === ACADÉMICO PAGE ===

    // Navigation
    'acad_nav_beneficios' => 'Abantailak',
    'acad_nav_funcionalidades' => 'Funtzionalitateak',
    'acad_nav_casos_exito' => 'Arrakasten Kasuak',
    'acad_nav_faq' => 'FAQ',
    'acad_nav_solicitar_demo' => 'Eskatu Demoa',
    'acad_nav_academico' => 'Akademikoa',

    // Hero Section
    'acad_hero_badge' => '✓ Soluzio Akademiko Osoa',
    'acad_hero_title' => 'Akreditazio Akademikoak',
    'acad_hero_title_highlight' => 'Digital Profesionalak',
    'acad_hero_subtitle' => 'Soluzio osoa honentzat',
    'acad_hero_instituciones' => 'hezkuntza-erakundeak',
    'acad_hero_centros_formacion' => 'formazio-zentroak',
    'acad_hero_academias' => 'akademiatuak',
    'acad_hero_formadores' => 'irakasle partikularrak',
    'acad_cta_solicitar_demo' => 'Eskatu Demo Pertsonalizatua',
    'acad_cta_ver_como_funciona' => 'Ikusi Nola Funtzionatzen Duen',

    // Hero Stats
    'acad_hero_stat_tiempo' => 'Administrazio-denboraren murrizketa',
    'acad_hero_stat_portal' => 'Ikaslearen ataria',
    'acad_hero_stat_falsificaciones' => 'Posible diren faltsuketak',

    // Problemas Section
    'acad_problemas_titulo' => 'Ezaguna al zaizu?',
    'acad_problemas_subtitulo' => 'Hauek dira Verumax-ek konpontzen dituen buruhausteak',
    'acad_problema_trabajo_manual' => 'Eskuzko Lan-Orduak',
    'acad_problema_trabajo_manual_desc' => 'Ziurtagiri bakoitza banan-banan diseinatzeak eta igortzeak denbora baliotsua hartzen du, irakaskuntzarako dedikatu ahal zenukeena.',
    'acad_problema_perdidos' => 'Galdutako Ziurtagiriak',
    'acad_problema_perdidos_desc' => 'Dokumentuak galtzea edo hondatzea eta berriro emateko eskaerak etengabe egitea.',
    'acad_problema_falsificaciones' => 'Faltsuketak',
    'acad_problema_falsificaciones_desc' => 'Titulu eta ziurtagiri faltsuak zirkulatzen ari dira, haien autentikotasuna egiaztatzeko modurik ezarekin.',
    'acad_problema_trazabilidad' => 'Trazabilitaterik Ez',
    'acad_problema_trazabilidad_desc' => 'Ikasle bakoitzaren historia akademiko oso eta egiaztagarria falta da.',
    'acad_problema_costos' => 'Inprimaketa-Kostuak',
    'acad_problema_costos_desc' => 'Paper bereziaren, inprimaketaren, tonerrearen eta biltegiratze fisikoaren gastu handiak.',
    'acad_problema_archivos' => 'Kaotikoak diren Artxibo Fisikoak',
    'acad_problema_archivos_desc' => 'Paper pilak espazio baliotsua okupatzen ari dira eta informazioa bilatzea zailtzen dute.',

    // Cómo Funciona Section
    'acad_como_funciona_titulo' => 'Hain erraza nola 1, 2, 3',
    'acad_como_funciona_subtitulo' => 'Berehalako inplementazioa, burutia zailtasunik gabe',
    'acad_como_funciona_paso1_titulo' => 'Konfiguratu Zure Erakundea',
    'acad_como_funciona_paso1_desc' => 'Pertsonalizatu zure logoa, erakundearen koloreak eta zehaztu igorriko dituzun ziurtagiri motak.',
    'acad_como_funciona_paso2_titulo' => 'Kargatu Ikasleak eta Ikastaroak',
    'acad_como_funciona_paso2_desc' => 'Inportatu datuak pilaka Excel edo CSV bidez. Banan-banan kargatu dezakezu ere bai.',
    'acad_como_funciona_paso3_titulo' => 'Igorri eta Balidatu',
    'acad_como_funciona_paso3_desc' => 'QR bakuneko sortze automatikoa. Jakinarazpena posta elektroniko bidez eta ikasleentzako sarbide berehalakoa.',

    // Tipos de Documentos
    'acad_documentos_titulo' => 'Dokumentu Akademikoen Motak',
    'acad_documentos_subtitulo' => 'Zure erakundeak igorri behar dituen dokumentu guztiak',
    'acad_documentos_principales' => 'Dokumentu Nagusiak',
    'acad_doc_certificado_aprobacion' => 'Onarpen-Ziurtagiriak',
    'acad_doc_certificado_aprobacion_desc' => 'Ikastaro, gaia edo programa oso baten gaineko onarpena ziurtatzen duen ziurtagiri ofiziala.',
    'acad_doc_diplomas' => 'Bukaerako Diplomak',
    'acad_doc_diplomas_desc' => 'Programa akademiko oso baten ongi bukatutako titulu edo diploma formala.',
    'acad_doc_analiticos' => 'Akademikoen Analisiak / Erregistroak',
    'acad_doc_analiticos_desc' => 'Hartutako gai guztien historia osoa, kalifikazioak, asistentziak eta eskuratutako gaitasunak.',
    'acad_doc_constancia_regular' => 'Ikasle Arrunta dela frogatzen duten Egiaztagiriak',
    'acad_doc_constancia_regular_desc' => 'Dokumentu honek ikaslea une honetan erakundean ikasten ari dela frogatzen du.',
    'acad_doc_constancia_inscripcion' => 'Matrikulazio-Egiaztagiriak',
    'acad_doc_constancia_inscripcion_desc' => 'Ikastaro jakin batean, gai batean edo programa akademiko batean matrikulatuta zaudela frogatzen duen agiria.',
    'acad_doc_constancia_finalizacion' => 'Ikasturtea Bukatutako Egiaztagiriak',
    'acad_doc_constancia_finalizacion_desc' => 'Ebaluazio amaieran egin baino lehen ikasturtea bukatu duela frogatzen duen ziurtagiria.',

    // Documentos Complementarios
    'acad_documentos_complementarios' => 'Osagarritako Dokumentuak',
    'acad_doc_asistencia' => 'Asistentzia-Ziurtagiriak',
    'acad_doc_asistencia_desc' => 'Tailerrak, mintegiak, webinarrak edo ekitaldi hezigarri puntualekikoak.',
    'acad_doc_reconocimientos' => 'Sariak eta Aipamenak',
    'acad_doc_reconocimientos_desc' => 'Sari bereziak, aipamen ofizioak edo ebaluazio aparta izanaren aitortza.',
    'acad_doc_competencias' => 'Gaitasun-Ziurtagiriak',
    'acad_doc_competencias_desc' => 'Formazioan lortutako gaitasun eta ezaugarri zehatzak ziurtatzen dituzte.',
    'acad_doc_practica' => 'Lan-Praktiken Egiaztagiriak',
    'acad_doc_practica_desc' => 'Praktikak, lan-esperientzia edo zuzeneko gainbegiralekuak dokumentatzen ditu.',
    'acad_doc_congresos' => 'Kongresuetan Hartutako Partearen Ziurtagiriak',
    'acad_doc_congresos_desc' => 'Kongresuetan, ekitaldi akademikoetan eta hitzaldietan parte hartzeko edo mintzamendurako.',

    // Portal del Estudiante
    'acad_portal_badge' => '★ Nabarmendutako Ezaugarria',
    'acad_portal_titulo' => 'Ikaslearen 24/7 Ataria',
    'acad_portal_subtitulo' => 'Ikasle bakoitzak bere atari propioa du, bere erakundearen ikus-nortasunarekin eta logoarekin pertsonalizatua. Bertatik, beren aurrerapenak ikusi eta dokumentu guztiak deskargatu ditzakete.',
    'acad_portal_acceso_titulo' => 'Bere ibilbide osoa 24/7 atzitu',
    'acad_portal_acceso_desc' => 'Ikasleek edozein gailutik eta edozein unetan atzitu dezakete.',
    'acad_portal_descarga_titulo' => 'Dokumentu guztiak deskargatu',
    'acad_portal_descarga_desc' => 'Diplomak, egiaztagiriak, ziurtagiriak, analisiak - dena leku bakarrean.',
    'acad_portal_timeline_titulo' => 'Denbora-lerro akademikoa',
    'acad_portal_timeline_desc' => 'Bere hezkuntza-ibilbidearen kronologia osoa bistaratzen du.',
    'acad_portal_qr_titulo' => 'Dokumentu bakoitzeko QR indibiduala',
    'acad_portal_qr_desc' => 'Dokumentu bakoitzak bere balidazio-kode bakuna dauka.',
    'acad_portal_linkedin_titulo' => 'LinkedIn-en klik bakarreko partekatzea',
    'acad_portal_linkedin_desc' => 'Lorpen akademikoak argitaratzeko integrazio zuzena.',

    // Portal Demo Data
    'acad_portal_demo_nombre' => 'Juan Pérez',
    'acad_portal_demo_dni' => 'DNI: 12.345.678',
    'acad_portal_demo_progreso' => '4 ikastaritako 4 osatuta',
    'acad_portal_demo_diploma' => 'Justizia Berrezartzaileko Diploma',
    'acad_portal_demo_diploma_fecha' => 'Bukatuta: 2024ko martxoaren 15a',
    'acad_portal_demo_certificado' => 'Mediazioaren Ziurtagiria',
    'acad_portal_demo_certificado_fecha' => 'Bukatuta: 2024ko urtarrilaren 20a',
    'acad_portal_demo_curso_progreso' => 'Ikastaroa Abian',
    'acad_portal_demo_curso_nombre' => 'Gatazkak Ebaztea',

    // Casos de Uso
    'acad_casos_uso_titulo' => 'Norentzat da Verumax Akademikoa?',
    'acad_casos_uso_subtitulo' => 'Gure plataforman konfiantza duten erakunde eta profesionalak',
    'acad_caso_universidades' => 'Unibertsitateak eta Hezkuntza Hirugarren Mailakoak',
    'acad_caso_universidades_desc' => 'Gradu-hirune, diplomak eta analisiak ehunka ikaslerentzat banan-banan kudeatzea.',
    'acad_caso_centros' => 'Formazio-Zentroak',
    'acad_caso_centros_desc' => 'SAJuR eta Liberté bezalako erakundeak ziurtagiri profesionalak igortzen dituztenak.',
    'acad_caso_idiomas' => 'Hizkuntza-Akademiatuak',
    'acad_caso_idiomas_desc' => 'Osatutako mailen ziurtagiriak nazioarteko balidazioarekin.',
    'acad_caso_tecnicos' => 'Instituto Teknikoak',
    'acad_caso_tecnicos_desc' => 'Lanbide-heziketa eta trebetasunak trazabilitate osoarekin ziurtatzea.',
    'acad_caso_laboral' => 'Laneko Prestakuntza',
    'acad_caso_laboral_desc' => 'Etengabeko formazio-zentroak eta garapen profesionala.',
    'acad_caso_continua' => 'Hezkuntza Etengabea',
    'acad_caso_continua_desc' => 'Lanbide-eguneraketarako programak eta masterrekin loturikoak.',
    'acad_caso_organizadores' => 'Ikastaroen Antolatzaileak',
    'acad_caso_organizadores_desc' => 'Tailerrak, ikastaroak eta programa berezietarako diplomek eta ziurtagiriekin loturikoak.',
    'acad_caso_particulares' => 'Irakasle Partikularrak',
    'acad_caso_particulares_desc' => 'Doktore independenteak ziurtagiri profesionalak igortzen dituztenak.',

    // Funcionalidades
    'acad_func_titulo' => 'Erakundeentzat Pentsatutako Funtzionalitateak',
    'acad_func_subtitulo' => 'Akreditazio akademikoak kudeatzeko behar duzun guztia',
    'acad_func_cohortes' => 'Taldeen Kudeaketa',
    'acad_func_cohortes_desc' => 'Ikasleak taldekatu mailaren, urtearen edo taldearen arabera. Dokumentuak talde osoarentzat banan-banan igorri.',
    'acad_func_emision_masiva' => 'Emate Masiboa',
    'acad_func_emision_masiva_desc' => '100 ikasle baino gehiagorentzako ziurtagiriak minutuetan sortu. Klik bakarra promozio osoarentzat.',
    'acad_func_notificaciones' => 'Posta Elektroniko Bidezko Jakinarazpen Automatikoak',
    'acad_func_notificaciones_desc' => 'Ikasle bakoitzak dokumentu bat igortzen denean jakinarazpen automatikoa jasotzen du.',
    'acad_func_branding' => 'Erakundearen Marka duen Ataria',
    'acad_func_branding_desc' => 'Zure logoa, koloreak eta domeinua. Erakunde bakoitzak bere nortasuna proiektatzen du.',
    'acad_func_trayectoria' => 'Ibilbide Akademiko Osoa',
    'acad_func_trayectoria_desc' => 'Ikaslearen ikastetxe guztiak, kalifikazioak eta lorpenak dituen ibilbide egiaztagarria.',
    'acad_func_validacion' => 'Balidazio Publiko Berehalakoa',
    'acad_func_validacion_desc' => 'Enpleatzaileek QR kodea eskaneatu eta autentikotasuna berehalakoan egiaztatzen dute.',

    // Beneficios
    'acad_beneficios_titulo' => 'Neurtutako Emaitzak',
    'acad_beneficios_subtitulo' => 'Zure erakundean egiazko eragina zure erakundean egunero',
    'acad_beneficio_tiempo_titulo' => 'Administrazio-Denboraren Murrizketa',
    'acad_beneficio_tiempo_desc' => 'Orain orduak beharrean minutuak behar dira',
    'acad_beneficio_ahorro_titulo' => 'Kostu-Aurreztea',
    'acad_beneficio_ahorro_desc' => 'Inprimaketa eta paper-lanaren murrizketa handia',
    'acad_beneficio_falsificaciones_titulo' => 'Posible Diren Faltsuketak',
    'acad_beneficio_falsificaciones_desc' => 'Ezin dira QR kode bakunak klonatu',
    'acad_beneficio_acceso_titulo' => 'Ikasleentzako Sarbidea',
    'acad_beneficio_acceso_desc' => 'Ataria beti eskuragarri',
    'acad_beneficio_trazabilidad_titulo' => '%100 Trazabilitatea eta Auditoretza',
    'acad_beneficio_trazabilidad_desc' => 'Ekintza bakoitza erregistratzen da. Zein dokumentu, noiz eta norentzat igorri duen nor zehazki badakizu. Auditoretzarako eta betekin normatiborako aproposa.',

    // Casos de Éxito
    'acad_casos_exito_titulo' => 'Arrakasten Kasuak',
    'acad_casos_exito_subtitulo' => 'Bere kudeaketa akademikoa eraldatu zuten erakundeak',
    'acad_caso_sajur_nombre' => 'Justizia Berrezartzaileko Gizarte Elkartea',
    'acad_caso_sajur_tipo' => 'Hezkuntza-espezializatuko zentroa',
    'acad_caso_sajur_testimonio' => '"Eskuz ziurtagiri bakoitza prozesatzetik hamarreka ematera pasatu ginen minutu gutxitan. Gure ikasleek euren ibilbide osoa 24/7 atzitu ahal izatea baloratzen dute, eta enpleatzaileek QR balidazioan konfiantza dute. Administrazio-denboraren aurreztea %90koa izan da."',
    'acad_caso_liberte_nombre' => 'Liberté Lan Taldeko Kooperatiba',
    'acad_caso_liberte_tipo' => 'Hezkuntza profesionala eta prestakuntza',
    'acad_caso_liberte_testimonio' => '"Inplementazioa berehalakoa izan zen. 24 ordur baino gutxiagoan ziurtagiriak jada gure markarekin ari ginen ematen. Pertsonalizatuko atariak irudi profesionala ematen dio gure irteerari, ikasleek harrotziaz partekatzen dutena. Premium inprimaketa aukera bikaina da."',

    // Antes vs Después
    'acad_antes_despues_titulo' => 'Lehen vs Ondoren Verumax',
    'acad_antes_despues_subtitulo' => 'Zure kudeaketa akademikoaren eraldatze digitala',
    'acad_antes_titulo' => 'Lehen (Tradizionala)',
    'acad_antes_trabajo_manual' => 'Ziurtagiri bakoitzeko eskuzko lan-orduak',
    'acad_antes_costos' => 'Inprimaketa eta paper-lanaren kostu handiak',
    'acad_antes_falsificacion' => 'Balioztatzeko modurik ez duen faltsuketaren arriskua',
    'acad_antes_presencial' => 'Ikasleek bertara joan behar dute jasotzeko',
    'acad_antes_almacenamiento' => 'Desantolatutako biltegiratze fisikoa eta espazioa okupatzea',
    'acad_antes_estadisticas' => 'Ez dago emate-estatistikarik ez metrikarik',
    'acad_despues_titulo' => 'Ondoren (Verumax)',
    'acad_despues_emision' => 'Segundu gutxitan emate masiboa',
    'acad_despues_emision_highlight' => 'klik bakunarekin',
    'acad_despues_ahorro' => '%85eko aurreztea',
    'acad_despues_ahorro_highlight' => 'kostu operatiboetan',
    'acad_despues_validacion' => 'Ezin da faltsutu QR balidazioa',
    'acad_despues_acceso' => '24/7 Sarbidea',
    'acad_despues_acceso_highlight' => 'edozein gailutik',
    'acad_despues_digital' => 'Dena digitalean eta hodeian,',
    'acad_despues_digital_highlight' => 'paperik edo espaziorik gabe',
    'acad_despues_dashboards' => 'Denbora errealeko kontrol-panelak eta txostenak',

    // Integraciones
    'acad_integraciones_titulo' => 'Integrazioak eta Bateragarritasuna',
    'acad_integraciones_subtitulo' => 'Zure lan-fluxu existenteari moldatzen zaio',
    'acad_integ_excel' => 'Excel / CSV',
    'acad_integ_excel_desc' => 'Excel fitxategien bidez ikasleak eta ikastaroak pilaka inportatzea.',
    'acad_integ_api' => 'REST API',
    'acad_integ_api_desc' => 'SIU, Moodle eta platafoma akademikoekin integratzea.',
    'acad_integ_email' => 'Erakundearen Posta Elektronikoa',
    'acad_integ_email_desc' => 'Jakinarazpenak zure erakundearen domeinutik (@zureerakundea.edu).',
    'acad_integ_subdominios' => 'Azpidomeinuak',
    'acad_integ_subdominios_desc' => 'Zure domeinu propioan dagoen ataria: ziurtagiriak.zureerakundea.edu',

    // FAQ
    'acad_faq_titulo' => 'Galdera Ohikoak',
    'acad_faq_subtitulo' => 'Verumax Akademikoari buruz jakin beharreko guztia',
    'acad_faq_cargo_titulo' => 'Nola kargatu ditzaket nire ikasleen informazioa?',
    'acad_faq_cargo_resp' => 'Bi modutan karga ditzakezu ikasleak: administrazio-panelaren bidez banan-banan, edo Excel/CSV fitxategi bat inportatuz datu guztiekin. Txantiloi bat ematen dizugu prozesua errazteko.',
    'acad_faq_validez_titulo' => 'Ziurtagiri digitalak balio juridikoa al dute?',
    'acad_faq_validez_resp' => 'Bai, ziurtagiri digitalak balio juridiko bera dute Espainian ere bai. Gainera, paper bereziarekin eta segurtasun-elementuekin premium inprimaketa aukera eskaintzen dugu behar duten erakundeentzat.',
    'acad_faq_diseno_titulo' => 'Diseinua erabat pertsonalizatu al dezaket?',
    'acad_faq_diseno_resp' => 'Erabat. Konfiguratu ditzakezu zure logoa, erakundearen koloreak, sinadura digitalak eta marka guztia. Ziurtagiri bakoitza zure ikus-identitatearekin sortzen da.',
    'acad_faq_acceso_titulo' => 'Zein da ikasle batek atarirako sarbidea galtzen badu?',
    'acad_faq_acceso_resp' => 'Ikasleak bere DNIa erabiliz berreskuratu dezake sarbidea eta posta elektroniko bidezko egiaztaketa prozesuarekin. Gainera, erakundearen administratzaile bezala, edozein unetan birsortu ahal duzu sarbidea.',
    'acad_faq_validacion_titulo' => 'Nola balioztatzen du enpleatzaile batek ziurtagiria?',
    'acad_faq_validacion_resp' => 'Enpleatzaileak zihurtagiriaren QR kodea mugikorrean eskaneatzen du soilik. Orduan automatikoki birbidalia izango da ziurtagiriaren datu guztiak eta ikaslearen historia erakusten duen balidazio-orria.',
    'acad_faq_retroactivos_titulo' => 'Ziurtagiri atzerakoak igor ditzaket?',
    'acad_faq_retroactivos_resp' => 'Bai, aurreko promozioen ziurtagiriak karga eta igor ditzakezu arazo gabe. Sistemak aurreko datak adieraztea ahalbidetzen du.',
    'acad_faq_limite_titulo' => 'Emate-mugarik ba al dago?',
    'acad_faq_limite_resp' => 'Ez dago igorpen-mugarik. Behar adina ziurtagiri sor ditzakezu. Planean ikasle aktiboen kopuruaren arabera doitzen dira.',

    // CTA Final
    'acad_cta_final_titulo' => 'Bihurtu Zure Erakundearen Kudeaketa Akademikoa',
    'acad_cta_final_desc' => 'Bat egin hezkuntza-erakundeen artean milaka ordu administrazioa aurreztu dutenekin eta ziurtagiri digitalen bidez irudi profesionala proiektatzen dutenekin.',
    'acad_cta_final_demo' => 'Eskatu Demo Pertsonalizatua',
    'acad_cta_final_contactar' => 'Harremanetan Jarri Salmentak',
    'acad_cta_final_implementacion' => 'Inplementazioa',
    'acad_cta_final_menos_tiempo' => 'Denbora gutxiago',
    'acad_cta_final_certificados' => 'Ziurtagiriak',

    // Footer
    'acad_footer_tagline' => 'Ziurtagiri Digital Profesionalak',
    'acad_footer_derechos' => '© 2025 Verumax. Eskubide guztiak erreserbatuta.',
    'acad_footer_inicio' => 'Hasiera',
    'acad_footer_terminos' => 'Terminoak',
    'acad_footer_privacidad' => 'Pribatutasuna',

    // === META TAGS === //

    // Index.php Meta Tags
    'meta_keywords' => 'ziurtagiri digitalak, QR balidazioa, ziurtagiri hezigarriak, egiaztagiri akademikoak, diploma on-lineak',
    'meta_author' => 'Verumax',
    'meta_og_title' => 'Verumax - Ziurtagiri Digital eta Fisikoen Segurtasuna',
    'meta_og_description' => 'Faltsutu ezin diren ziurtagiriak igorri QR balidazioarekin eta ibilbide akademikoa osoa. Ikasleentzako 24/7 ataria eta premium inprimaketa aukera.',
    'meta_twitter_title' => 'Verumax - Ziurtagiri Digital eta Fisikoen Segurtasuna',
    'meta_twitter_description' => 'Faltsutu ezin diren ziurtagiriak igorri QR balidazioarekin eta ibilbide akademikoa osoa. Ikasleentzako 24/7 ataria eta premium inprimaketa aukera.',

    // Academico.php Meta Tags
    'acad_meta_title' => 'Verumax Akademikoa - Erakunde Hezigarrientzako Ziurtagiri Digitalak',
    'acad_meta_description' => 'Hezkuntza-erakundeentzako, formazio-zentroentzako eta irakasle partikuluentzako ziurtagiri digitalen soluzio osoa. Emate masiboa, QR balidazioa eta ikaslearen ataria.',
    'acad_meta_keywords' => 'ziurtagiri akademikoak, diploma digitalak, analisi digitalak, hezkuntza-erakundeak, prestakuntza profesionala',
    'acad_meta_og_title' => 'Verumax Akademikoa - Hezkuntza-Erakundeentzako Ziurtagiriak',
    'acad_meta_og_description' => 'Igorri ziurtagiriak, diplomek eta analitiko digitalak QR balidazioarekin. Ikaslearen 24/7 ataria eta automatizatutako emate masiboa.',
    'acad_meta_twitter_title' => 'Verumax Akademikoa - Hezkuntza-Erakundeentzako Ziurtagiriak',
    'acad_meta_twitter_description' => 'Igorri ziurtagiriak, diplomek eta analitiko digitalak QR balidazioarekin. Ikaslearen 24/7 ataria eta automatizatutako emate masiboa.',

    // Privacidad.php Meta Tags
    'privacidad_meta_description' => 'Verumax-en Pribatutasun-politika. Ikasi nola bildu, erabili eta babesten ditugun zure datu pertsonalak.',
    'privacidad_meta_og_title' => 'Pribatutasun-politika - Verumax',
    'privacidad_meta_og_description' => 'Xehetasunak nola Verumax-ek zure pribatutasuna babesten duen eta zure datu pertsonalak nola kudeatzen dituen.',
    'privacidad_meta_twitter_title' => 'Pribatutasun-politika - Verumax',
    'privacidad_meta_twitter_description' => 'Xehetasunak nola Verumax-ek zure pribatutasuna babesten duen eta zure datu pertsonalak nola kudeatzen dituen.',

    // Terminos.php Meta Tags
    'terminos_meta_description' => 'Verumax-en Zerbitzu-baldintzak. Ikasi gure ziurtagiri digitalen plataformaren erabilpen-baldintzak.',
    'terminos_meta_og_title' => 'Zerbitzu-baldintzak - Verumax',
    'terminos_meta_og_description' => 'Zure erabiliz Verumax-en eta bere ziurtagiri-zerbitzuen erabilera legalaren baldintzak.',
    'terminos_meta_twitter_title' => 'Zerbitzu-baldintzak - Verumax',
    'terminos_meta_twitter_description' => 'Zure erabiliz Verumax-en eta bere ziurtagiri-zerbitzuen erabilera legalaren baldintzak.',

    // === SEKSIO BERRIA: NAVIGAZIO OSOA ===

    'nav_volver_inicio' => 'Hasierara Itzuli',
    'nav_tema_claro' => 'Argitasun-Modura Aldatu',
    'nav_tema_oscuro' => 'Iluntasun-Modura Aldatu',
    'nav_soluciones' => 'Soluzio Espezializatuak Sektoreka',
    'nav_ecosistema' => 'Zerbitzuen Ekosistemaren Zenbait Aukera Zure Esku',
    'nav_rapido_titulo' => 'Zeri bilatzen ari zara?',
    'nav_rapido_sectores_titulo' => 'Sektoreka Soluzioak',
    'nav_rapido_sectores_desc' => 'Akademikoa, Profesionala, Ekitaldiak, Enpresariala, eta gehiago.',
    'nav_rapido_ecosistema_titulo' => 'Gure Soluzio Guztiak',
    'nav_rapido_ecosistema_desc' => 'Txartelak, Ziurtagiriak, Kupoiak, Orri Pertsonalizatuak, IA eta gehiago.',
    'nav_soluciones_academico' => 'Akademikoa',
    'nav_soluciones_profesional' => 'Profesionala',
    'nav_soluciones_eventos' => 'Ekitaldiak',
    'nav_soluciones_empresarial' => 'Enpresariala',
    'nav_soluciones_cooperativas' => 'Kooperatibak',
    'nav_soluciones_mutuales' => 'Elkarteak',
    'nav_productos' => 'Soluzioak',
    'nav_productos_tarjeta_digital' => 'Txartel Digitala',
    'nav_productos_certificados' => 'Ziurtagiri Akademikoak',
    'nav_productos_credenciales' => 'Kredentzialak eta Dokumentuak',
    'nav_productos_landing_personales' => 'Orri Pertsonalizatu Pertsonalak',
    'nav_productos_landing_institucionales' => 'Orri Pertsonalizatu Instituzionalak',
    'nav_productos_portfolios' => 'Portfoli Aurrerapenak',
    'nav_productos_cv' => 'Adimen-CV',
    'nav_productos_autenticidad' => 'Autentikotasunaren Ziurtagiriak',
    'nav_productos_ia' => 'Adimenaren Agenteak',
    'nav_productos_impresion' => 'Premium Inprimaketa',
    'nav_productos_vouchers' => 'Kupoiak eta Saria',
    'nav_productos_portal_comunicacion' => 'Komunikazio Ataria',
    'nav_productos_encuestas' => 'Inkestak eta Boztaldia',

    // Hero Section Gehigarria
    'hero_title_line1' => 'Sortu, Kudeatu eta Balidatu',
    'hero_title_line2' => 'zure Presentia Digitala',
    'hero_subtitle' => 'Tresna-sorta faltsutu ezina diren kredentzialak emateko, neurtua baieztatzea duzun presentia digitala osatzeko eta IA agenteen espezialista inplementatzeko.',

    // Equipo Section
    'equipo_titulo' => 'Zurerentzat Pentsatua',
    'equipo_subtitulo' => 'Ezagutza Teknikorik Beharrik Gabe',
    'equipo_card1_titulo' => 'Benetako Talde Humano',
    'equipo_card1_desc' => 'Ez zaitugu software baten bakarrik uzten. Gure talde humano bat guztia beren gain hartzen du: konfigurazioa, diseina, informazioaren karga eta etengabeko laguntza. Zuk zure informazioa soilik bidali behar duzu eta guk gainerakoa egiten dugu.',
    'equipo_card2_titulo' => 'Dashboard Moderno Sartu',
    'equipo_card2_desc' => 'Ezagutza teknikoa badituzu edo ikastea nahi baduzu, dashboard intuitibo, moderno eta seguru bat daukazu guztia beretzat kudeatzeko. Baina beti gure laguntzari eska dezakezu behar duzunean.',
    'equipo_card3_titulo' => 'Laguntza 24/7',
    'equipo_card3_desc' => 'Zuzenean benetako pertsonen ateen sarbidea daukazu lagunduz zaitzaten behar duzunean. Dashboard-a erabiliz edo zuzenean idatziaz, beti laster eta jasotzen duzu jasangarri emaitza.',

    // Categorías Section Gehigarria
    'cat_proximamente' => 'Laster',
    'cat_footer' => 'Kategoria gehiago laster.',
    'cat_footer_link' => 'Galdetu iezaguzu',
    'cat_footer_text' => 'zure sektorea zerrendan ez badago.',

    // Productos/Ecosistema Section
    'productos_title' => 'Tresna-Sorta Osoa Zure Esku',
    'productos_subtitle' => 'Gure soluzio espezialista aurkitu. Bakoitza gure faltsutu ezinezko balidazio-teknologia-n eraikita.',
    'ecosol_tarjeta_digital' => 'Txartel Digitala',
    'ecosol_tarjeta_digital_desc' => 'Faltsutu ezinezko QR eta pertsonalizatua orri-etarekin',
    'ecosol_certificados_academicos' => 'Ziurtagiri Akademikoak',
    'ecosol_certificados_academicos_desc' => 'Diplomat eta analitiko digital egiaztagarria',
    'ecosol_credenciales_documentos' => 'Kredentzialak eta Dokumentuak',
    'ecosol_credenciales_documentos_desc' => 'Dokumentazio profesional egiaztagarria',
    'ecosol_landing_personales' => 'Orri Pertsonalizatu Pertsonalak',
    'ecosol_landing_personales_desc' => 'Zure identitatearekin web-gunea pertsonala',
    'ecosol_landing_institucionales' => 'Orri Pertsonalizatu Instituzionalak',
    'ecosol_landing_institucionales_desc' => 'Presentia web profesionala zure erakundearentzat',
    'ecosol_portfolios' => 'Portfoli Aurrerapenak',
    'ecosol_portfolios_desc' => 'Zure lana erakutsi profesional-balidazioarekin',
    'ecosol_cv_inteligentes' => 'Adimen-CV',
    'ecosol_cv_inteligentes_desc' => 'Curriculum egiaztagarria eta eguneragarria',
    'ecosol_certificados_autenticidad' => 'Autentikotasunaren Ziurtagiriak',
    'ecosol_certificados_autenticidad_desc' => 'Produktuentzat, arte-lanen eta gehiagorentzat',
    'ecosol_agentes_ia' => 'Adimenaren Agente Espezializatuak',
    'ecosol_agentes_ia_desc' => 'Inteligentziadun agenteen pertsonalizatuak',
    'ecosol_impresion_premium' => 'Premium Inprimaketa',
    'ecosol_impresion_premium_desc' => 'Kalitate altuko dokumentu fisikoak',
    'ecosol_vouchers' => 'Kupoiak eta Kupoiak Digitalak',
    'ecosol_vouchers_desc' => 'Behin-behineko kupoiak QR egiaztagarriarekin',
    'ecosol_portal_comunicacion' => 'Komunikazio Ataria',
    'ecosol_portal_comunicacion_desc' => 'Berriak eta berriak-taula ofiziala',
    'ecosol_encuestas' => 'Inkestak eta Boztaldia',
    'ecosol_encuestas_desc' => 'Aktibo daude eta zure komunitatea-ren feedback',

    // Footer Gehigarria
    'footer_inicio' => 'Hasiera',
    'footer_legal' => 'Legala',

    // Veritas IA Section
    'veritas_chat_btn' => 'Veritas IA-rekin Txat Egin',
    'veritas_titulo' => 'Veritas IA',
    'veritas_subtitulo' => 'Gure Adimenaren Agente Espezialiatu',
    'veritas_proximamente' => '¡Laster!',
    'veritas_descripcion' => 'Veritas laster egongo da ziurtagiri, balidazio eta gehiagoari buruzko kontsultak laguntzeko.',
    'veritas_entendido' => 'Ulertu',

    // Privacidad Gehigarria
    'privacidad_seccion1_sub1_titulo' => '1.1 Kontuari Buruzko Informazioa',
    'privacidad_seccion1_sub1_p1' => 'Kontu bat sortzen duzunean, hauxe biltzen dugu:',
    'privacidad_seccion1_sub1_li1' => 'Izen osoa eta harremanetarako datuak (posta elektronikoa, telefonoa)',
    'privacidad_seccion1_sub1_li2' => 'Erakundearen, antolaketaren edo profesional independentearen izena',
    'privacidad_seccion1_sub1_li3' => 'Helbide fisikoa eta fiskala',
    'privacidad_seccion1_sub1_li4' => 'Fakturazio eta ordainketari buruzko informazioa',
    'privacidad_seccion1_sub1_li5' => 'Sarbide-kredentzialak (enkriptatutako erabiltzaile/pasahitza)',
    'privacidad_seccion1_sub2_titulo' => '1.2 Dokumentuei eta Onbenefiziariei Buruzko Datuak',
    'privacidad_seccion1_sub2_p1' => 'Dokumentuak igortzean, onbenefizarien datuak biltzen ditugu (ikasleak, bezeroak, langileak, kideak, etab.):',
    'privacidad_seccion1_sub2_li1' => 'Izen osoa eta identifikazio-zenbakia (DNI, CUIT, etab.)',
    'privacidad_seccion1_sub2_li2' => 'Posta elektronikoa eta telefonoa (jakinarazpenetarako)',
    'privacidad_seccion1_sub2_li3' => 'Dokumentuaren igorpenarekin lotutako datu akademikoak, profesionalak edo lanekoak',
    'privacidad_seccion1_sub2_li4' => 'Argazkia (hautazkoa, dokumentuan sartzen bada)',
    'privacidad_seccion1_sub3_titulo' => '1.3 Erabilpen eta Datu Teknikoak',
    'privacidad_seccion1_sub3_li1' => 'IP helbidea, nabigatzailea, sistema eragilea',
    'privacidad_seccion1_sub3_li2' => 'Bisitatutako orrialdeak, saioaren iraupena, klikak',
    'privacidad_seccion1_sub3_li3' => 'Dokumentuen balidazio-erregistroak (nork balidatu duen, noiz eta nondik)',
    'privacidad_seccion1_sub3_li4' => 'Atariaren erabilpen-metriak (deskargak, sarrerak, etab.)',

    // === PÁGINA PROFESIONAL (TARJETA DIGITAL) ===
    'prof_meta_title' => 'Tarjeta Digital Profesional QR-arekin Faltsutu Ezina | Verumax',
    'prof_meta_description' => 'Zure harremana-txartel digital profesionala QR dinamiko eta faltsutu ezinarekin. Orri pertsonalizatua, dashboard seguru eta eguneraketa berehalakoa.',
    'prof_meta_keywords' => 'tarjeta digitala, qr faltsutu ezina, harremana-txartel digitala, orri profesionala, networking digitala',
    'prof_meta_og_title' => 'Txartel Digitala: Zure Bisita-Txartelaren Eboluzioa',
    'prof_meta_og_description' => 'Ahaztu paper-txartelak. Zure nortasun profesionala txartel digital batean QR egiaztagarriarekin, orri pertsonalizatua eta kudeaketa denbora errealean.',
    'prof_meta_twitter_title' => 'Tarjeta Digital Profesional by Verumax',
    'prof_meta_twitter_description' => 'Etorkizunaren bisita-txartela. QR faltsutu ezina, orri sartu eta eguneraketa berehalakoa.',

    'prof_nav_perfiles' => 'Txartel Digitala',
    'prof_nav_como_funciona' => 'Nola Funtzionatzen Du',
    'prof_nav_caracteristicas' => 'Ezaugarriak',
    'prof_nav_planes' => 'Planoak',
    'prof_nav_empezar' => 'Sortu Nire Txartela',

    'prof_hero_badge' => 'Dena Daukazu Produktu Bakarrean',
    'prof_hero_title' => 'Zure Txartel Digitala',
    'prof_hero_title_highlight' => 'Gure Talde Humano-rekin<br>Konfiguratu',
    'prof_hero_subtitle' => 'Txartel Digitala osoa da: txartel JPG+ web-gunea + bezeroan-kudeaketa + email marketing + agenteen birtuala. Gure talde humano-a DENA konfiguratu duzu. Zuk zure informazioa bidali eta hori zara.',
    'prof_hero_url_ejemplo' => 'Zure URL pertsonalizatua:',
    'prof_hero_url_ejemplo_subdomain' => 'zure-izena',
    'prof_hero_url_ejemplo_domain' => '.verumax.com',
    'prof_cta_empezar' => 'Ikusi Planoak eta Sortu Nire Txartela Digitala',
    'prof_cta_secundario' => 'Ikusi Nola Funtzionatzen Duen',

    'prof_stat_qr' => 'Talde Humano',
    'prof_stat_qr_desc' => 'Gu guztia konfiguratu',
    'prof_stat_actualizacion' => 'Dashboard Sartu',
    'prof_stat_actualizacion_desc' => 'Auto-kudeaketarako nahi duzunean',
    'prof_stat_landing' => 'Osoa Solazioa',
    'prof_stat_landing_desc' => 'Txartela + Web + Tresnak',

    'prof_que_es_titulo' => 'Zer da Txartel Digitala?',
    'prof_que_es_subtitulo' => 'Dena behar duzun zure presentia digitalrentzat',
    'prof_que_es_desc' => 'Txartel Digitala ez da txartel soilik. OSO da behar duzun zenbait zerbitzuren: ① Zure txartel fisika JPG formatuan QR faltsutu ezinarekin partekaritzeko edo inprimatzen ② Zure web-gunea (zure-izena.verumax.com) ③ Bezeroan/kontaktu kudeatzailea ④ Email-marketing-a sistemaren ⑤ 24/7 agente birtuala espezialiatu. DENA gu konfiguratu. Benetako talde humano bat zure presentia digitala osoa osatzen du. Zuk zure informazioa (argazkia, zerbitzuak, orduak) bidali behar duzu eta gu tresna-lan teknikoa guztia egiten dugu. Dashboard-a ere daukazu auto-kudeaketarako nahi duzunean, baina ez da inoiz obligatorioa.',

    'prof_tarjeta_feature1_titulo' => 'Zure Txartel Digitala Fisika',
    'prof_tarjeta_feature1_desc' => 'JPG argazkia kalitate gailan zure diseinu profesionalarekin eta QR faltsutu ezinarekin. Partekaritu WhatsApp, email, LinkedIn edo inprimatu papelean. Ordezten du tradizionala paper-txartelak.',
    'prof_tarjeta_feature2_titulo' => 'Zure Web-Gunea Profesional Osoa',
    'prof_tarjeta_feature2_desc' => 'Domeinu pertsonalizatua (zure-izena.verumax.com) diseinu profesionalarekin, portfolia, zerbitzuak, orduak, kontaktu-formularioa. Ez da soilik lehen-orria, zure web-gunea osoa da gure taldearen konfigurazioa.',
    'prof_tarjeta_feature3_titulo' => 'Tresna-Kudeaketa Sartu',
    'prof_tarjeta_feature3_desc' => 'Bezeroan-kudeaketa + Email marketing + Agente Birtuala Espezialiatu. Osoa integratua eta funtzionatzen. Zerbitzuak dira normalean bereizi kontratatzen dituzunak.',
    'prof_tarjeta_feature4_titulo' => 'Talde Humano + Dashboard Aukerakoa',
    'prof_tarjeta_feature4_desc' => 'Gu guztia konfiguratu duzu. Benetako talde humano bat zure presentia digitala osoa osatzen du. Aldaketak egiteko dashboard-aera ere sarbidea daukazu nahi duzunean, baina beti gure laguntzari eska dezakezu.',

    'prof_como_titulo' => 'Nola Funtzionatzen Duen 3 Urrats Sinpleetan',
    'prof_como_subtitulo' => 'Gu tresna-lan teknikoa guztia egiten dugu zurerentzat',
    'prof_como_paso1' => 'Urratsa 1: Plano Aukeratu eta Zure Informazioa Bidali',
    'prof_como_paso1_desc' => 'Zure hobeto moldatzen zaituen planoa aukeratzen duzu eta guri zure informazioa bidalitzen duzu: izena, argazkia, eskaintzen dituzun zerbitzuak, orduak, kontaktua. Inola ez. Ez duzu ezer teknikoa ukitu behar.',
    'prof_como_paso2' => 'Urratsa 2: Gure Taldea DENA Konfiguratu',
    'prof_como_paso2_desc' => 'Benetako talde humano bat zure web-gunea osoa osatzen du, zure txartela digitala diseinatzen du, zure tresnak konfiguratu (bezeroan kudeaketa, email marketing, agente birtuala). Zuk ez duzu ezer egiten. Gu tresna-lan teknikoa guztia egiten dugu.',
    'prof_como_paso3' => 'Urratsa 3: Hasi Guztia Jada Funtzionatzen',
    'prof_como_paso3_desc' => 'Zure txartela lortu partekaritzeko, zure web-gunea online eta tresna guztia konfiguratu eta prest. Dashboard-a erabili ahal duzu aldaketak egiteko zurerentzat, edo idatzi eta gu egin ditzagun. Beti daukazu benetako talde humano-aren laguntza.',

    'prof_caracteristicas_titulo' => 'Zergatik Aukeratu Gure Txartel Digitala',
    'prof_caracteristicas_subtitulo' => 'Ez da soilik txartela, zure solazioa profesionala osoa da talde humano sartuarekin',

    'prof_caract_qr_titulo' => 'Talde Humano Zurerentzat Dena Egiten',
    'prof_caract_qr_desc' => 'Ez zaitugu software baten bakarrik uzten. Benetako talde humano-a zure web-gunea konfiguratu, zure txartela diseinatzen, zure informazioa kargatu, eta betierako laguntza ematen du. Dashboard-a erabili nahi baduzu, edo idatzi eta gu aldaketak egiten dituzte. Beti daude benetako pertsonen atean.',
    'prof_caract_panel_titulo' => 'Zenbait Zerbitzuen Batura Batean',
    'prof_caract_panel_desc' => 'Ez duzu soilik txartela erosi. Erosi duzu: txartel digitala + web-gunea osoa + bezeroan kudeaketa + email marketing + agente birtuala. Tresnak dira normalean bereizi kontratatzen dituzunak zenbait plataformatan. Hemen daude osoa integratua eta funtzionatzen.',
    'prof_caract_paletas_titulo' => 'Dashboard Sartu Baina Aukerakoa',
    'prof_caract_paletas_desc' => 'Dashboard-a sarbidea daukazu aldaketak egiteko zurerentzat nahi duzunean: argazkia eguneratu, orduak aldatu, zerbitzuak gehitu. Baina INOIZ ez da obligatorioa. Beti gure eska dezakezu egin ditzaketen. Dashboard-a aukera da, ez obligazioa.',
    'prof_caract_landing_titulo' => 'Web-Gunea Profesional Osoa',
    'prof_caract_landing_desc' => 'Ez da soilik "lehen-orria". Zure web-gunea profesional osoa da (zure-izena.verumax.com) portfolia, zerbitzuak xehetuta, kontaktu-formularioa, orduen informazioa. Osoa mugikorrean optimizatua eta gure taldearen konfigurazioa.',
    'prof_caract_formatos_titulo' => 'Zure Presentia Digitala Beharrean Gaur',
    'prof_caract_formatos_desc' => 'Interneten presentia izan ez da aukerakoa. Beharrean dago. Txartel Digitalak daukazu DENA behar duzun: txartela partekaritzeko + web-gunea profesionala + kudeaketa-tresnak. Osoa produktu bakarrean, konfiguratu eta erabilera prest.',
    'prof_caract_seguridad_titulo' => 'Benetako Taldeak Etengabeko Laguntza',
    'prof_caract_seguridad_desc' => 'Ez bakarrik. Beti benetako taldean pertsonen atean laguntzeko. Aldatu nahi duzu zerbait? Idatzi iezaguzu. Ez duzu tresna bat erabiltzen badakizu? Azaldu dizugu. Gehitu nahi duzu eduki? Egiten dugu. Benetako talde humano-aren laguntza, ez chatbot-ak.',

    'prof_casos_titulo' => 'Norentzat da Txartel Digitala?',
    'prof_casos_subtitulo' => 'Industriaren profesional guztiak lehen-norantzako baloreatzen dituzte',

    'prof_caso_abogados' => 'Abokatuak eta Kontsultzailea',
    'prof_caso_abogados_desc' => 'Zure txartela QR-arekin zure bezeroentzat. Eskaneatzen dute eta zure praktika areak, arenduaren orduak eta kontsulta-formularioa atzitu ditzakete.',
    'prof_caso_medicos' => 'Medikuak eta Osasun Profesionalak',
    'prof_caso_medicos_desc' => 'Zure txartela espezialitate eta, kontsultorioren orduak, dituzten gizarte-obren eta deia-zuzeneko botoia turno-agendaketarako.',
    'prof_caso_arquitectos' => 'Arkitektuak eta Diseinatzailea',
    'prof_caso_arquitectos_desc' => 'Zure txartela partekaritu eta zure prospektiboak zure portofolyo ikusgarria zure web-gunea pertsonalizatuan.',
    'prof_caso_comercios' => 'Dendekeriak eta Negozioa',
    'prof_caso_comercios_desc' => 'Zure komertzial txartela orduak, kokalekua, katalogua produktu/zerbitzuekin eta WhatsApp knopoa kontsultetatako.',
    'prof_caso_coaches' => 'Entrenamailuak eta Trebatzeailea',
    'prof_caso_coaches_desc' => 'Zure zerbitzuak erakutsi, iritzi txikiak, eta zure bezeroak zuzenean agendatu ahal ditzakete zure web-etik saioak.',
    'prof_caso_freelancers' => 'Autonomoa eta Artea-Sortzailea',
    'prof_caso_freelancers_desc' => 'Zure txartela digitala zure portofolioa lotuarekin, gizarte-sareak eta tarifak. Inpresio profesional garantizatua.',
    'prof_caso_productores' => 'Elikagai-Produktuak',
    'prof_caso_productores_desc' => 'Zure txartela partekaritu kalitate ziurtagiri, produktuen trazabilitate eta katalogoa. QR zure bezeroak zure informazio egiaztagarri osoa lotuarekin.',
    'prof_caso_artesanos' => 'Artesanuak eta Eskudzintza',
    'prof_caso_artesanos_desc' => 'Zure lan artesanua erakutsi galeria argazkiak, prezioak eta kontaktu zuzena. Perfektua ferian, merkatu eta bezeroan pertsonalak.',
    'prof_caso_trainers' => 'Entrenatzailea Pertsonala eta Nutrizionista',
    'prof_caso_trainers_desc' => 'Zure txartela espezialitate, plano eskuragarria, orduak eta agendaketa-sistemaren. Zure bezeroak turno zuzenean agendatu ahal dituzte zure web-etik.',

    'prof_planes_titulo' => 'Aukeratu Zure Hobera Moldatzen Zaituen Planoa',
    'prof_planes_subtitulo' => 'Plano guztiak talde humano-ak konfigurazio + betierako laguntza + dashboard auto-kudeaketa sartuak',
    'prof_planes_promo' => '🔥 PROMO ABIATU',
    'prof_planes_alta_texto' => 'Alta bonifikatu:',
    'prof_planes_descuento' => '50% DESPIKARRIA - Denboraldi mugatua soilik',

    'prof_plan_esencial_titulo' => 'Essentialis',
    'prof_plan_esencial_desc' => 'Zure presentia digitala profesionala osoa. Gu guztia konfiguratu duzu.',
    'prof_plan_esencial_precio' => '$9 USD',
    'prof_plan_esencial_periodo' => '/ Urtea',
    'prof_plan_esencial_feat1' => 'Txartel Digitala JPG QR Faltsutu Ezinarekin',
    'prof_plan_esencial_feat2' => 'Web-Gunea Pertsonalizatu (zure-izena.verumax.com)',
    'prof_plan_esencial_feat3' => 'Proiektu Portfolia (20 irudiraino)',
    'prof_plan_esencial_feat4' => 'Zerbitzuen Sekzioa Xehetua',
    'prof_plan_esencial_feat5' => 'Kontaktu Formularioa Integratua',
    'prof_plan_esencial_feat6' => 'Bezeroan Kudeaketa (20 kontaktura)',
    'prof_plan_esencial_feat7' => 'Email Marketing (100 emaila/asten)',
    'prof_plan_esencial_feat8' => 'Agente Birtuala Espezialiatu (10 kontsulta/eguna)',
    'prof_plan_esencial_feat9' => 'Agendaketa-Sistema Zita-Egitearen',
    'prof_plan_esencial_feat10' => 'Konfigurazioa Talde Humano-rekin',
    'prof_plan_esencial_feat11' => 'Dashboard Auto-Kudeaketa Sartu',
    'prof_plan_esencial_cta' => 'Hasi Essentialis-arekin',

    'prof_plan_plus_badge' => 'Gehiago Orokorra',
    'prof_plan_plus_titulo' => 'Premium',
    'prof_plan_plus_desc' => 'Dena Essentialis-etik muga hedatua eta tresna profesional aurreratua dituztenak.',
    'prof_plan_plus_precio' => '$19 USD',
    'prof_plan_plus_periodo' => '/ Urtea',
    'prof_plan_plus_feat1_strong' => 'Osoa Essentialis plano, gehi:',
    'prof_plan_plus_feat2' => 'Portfolio Hedatua (100 irudira)',
    'prof_plan_plus_feat3' => 'Bezeroan Kudeaketa (100 kontaktura)',
    'prof_plan_plus_feat4' => 'Email Marketing (1,000 emaila/asten)',
    'prof_plan_plus_feat5' => 'Agente Birtuala Espezialiatu (50 kontsulta/eguna)',
    'prof_plan_plus_feat6' => 'Bideo Pertsonal Presentazioa',
    'prof_plan_plus_feat7' => 'Estatistika Aurreratua QR Eskaneo-etako',
    'prof_plan_plus_feat8' => 'CV Adimen Generatzailea (PDF eta Web)',
    'prof_plan_plus_feat9' => 'Agendaketa-Sistema Zita-Egitearen',
    'prof_plan_plus_feat10' => 'Integrazioa Kredentzia Egiaztatuarekin',
    'prof_plan_plus_cta' => 'Lortu Premium Planoa',

    'prof_plan_pro_badge' => 'Profesionala',
    'prof_plan_pro_titulo' => 'Excellens',
    'prof_plan_pro_desc' => 'Solazioa profesional osoa kudeaketa enpresaren tresna eta presentia digital hedatua.',
    'prof_plan_pro_precio' => '$49 USD',
    'prof_plan_pro_periodo' => '/ Urtea',
    'prof_plan_pro_feat1_strong' => 'Osoa Premium planoa, gehi:',
    'prof_plan_pro_feat2' => 'Portfolio Enpresakuntza (500 irudira)',
    'prof_plan_pro_feat3' => 'Bezeroan Kudeaketa (1,000 kontaktura)',
    'prof_plan_pro_feat4' => 'Email Marketing (5,000 emaila/asten)',
    'prof_plan_pro_feat5' => 'Agente Birtuala Espezialiatu (100 kontsulta/eguna)',
    'prof_plan_pro_feat6' => 'Orrialde Anitzak Pertsonalizatuak',
    'prof_plan_pro_feat7' => 'Analitika Aurreratua eta Txostenak Xehetua',
    'prof_plan_pro_feat8' => 'Integrazioetaak API Pertsonalizatuak',
    'prof_plan_pro_feat9' => 'Laguntza Behargarria 24/7',
    'prof_plan_pro_cta' => 'Lortu Excellens Planoa',

    'prof_plan_elite_badge' => 'Enpresakuntza',
    'prof_plan_elite_titulo' => 'Supremus',
    'prof_plan_elite_desc' => 'Solazioa enpresakuntza definitiboa baliabide hedatua, domeinu propioa eta pertsonalizazioa osoa dituztenak.',
    'prof_plan_elite_precio' => '$99 USD',
    'prof_plan_elite_periodo' => '/ Urtea',
    'prof_plan_elite_feat1_strong' => 'Osoa Excellens planoa, gehi:',
    'prof_plan_elite_feat2' => 'Portfolio Enpresakuntza (2000 irudira)',
    'prof_plan_elite_feat3' => 'Bezeroan Kudeaketa (5,000 kontaktura)',
    'prof_plan_elite_feat4' => 'Email Marketing (10,000 emaila/asten)',
    'prof_plan_elite_feat5' => 'Agente Birtuala Espezialiatu (1,000 kontsulta/eguna)',
    'prof_plan_elite_feat6' => 'Domeinu Propioa Sartu (zure-izena.com)',
    'prof_plan_elite_feat7' => 'Diseina 100% Pertsonalizatu Neurreria',
    'prof_plan_elite_feat8' => 'Subdomeinu Mugagabea Zure Taldearentzat',
    'prof_plan_elite_feat9' => 'Roletan eta Baimenen Sistemaren Aurreratua',
    'prof_plan_elite_feat10' => 'Norbere Kontu Kudeatzailea Dedikatu',
    'prof_plan_elite_cta' => 'Lortu Supremus Planoa',

    // === PÁGINA MUTUALES ===

    'mut_meta_title' => 'Verumax Elkarteak-entzat - Kudeaketa Digital Integra',
    'mut_meta_description' => 'Solazioa osoa elkarteak eta mutualeta elkarteak-entzat. Kredentzia digitala, kudeaketa onurak, ataria kide eta komunikazioa komunitaria.',
    'mut_meta_keywords' => 'elkarteak, elkartea mutualeta, kredentzia digitala, kudeaketa kide, onurak mutualaak',

    'mut_nav_beneficios' => 'Abantailak',
    'mut_nav_pilares' => 'Zutabeak',
    'mut_nav_planes' => 'Planoak',
    'mut_nav_faq' => 'FAQ',
    'mut_nav_mutuales' => 'Elkarteak',

    'mut_hero_badge' => 'Solazioa Integra Elkarteak-entzat',
    'mut_hero_title' => 'Kudeaketa Digitala',
    'mut_hero_title_highlight' => 'Elkarteak-entzat',
    'mut_hero_subtitle' => 'Ekosistemare osoa kudeaketa modernizatu, onurak potentzia eta komunitate-sentidoa bortxatu zure elkarteak-en',
    'mut_cta_solicitar_demo' => 'Eskaera Demo Pertsonalizatua',
    'mut_cta_ver_como_funciona' => 'Ikusi Nola Funtzionatzen Duen',

    'mut_hero_stat_tiempo' => 'Kudeaketa administrataboa gutxago',
    'mut_hero_stat_portal' => 'Kide ataria 24/7',
    'mut_hero_stat_beneficios' => 'Onuren kudeaketa denbora errealean',

    'mut_problemas_titulo' => 'Zuri suena familiar?',
    'mut_problemas_subtitulo' => 'Erronkak elkarteak tradizionalak aurren dituztenak',
    'mut_problema_credenciales' => 'Kredentzia Plastiko Zaharkitua',
    'mut_problema_credenciales_desc' => 'Inprimatze kostuak, etengabea galtzea eta zailtasun kimea kide egoera egiaztatzen.',
    'mut_problema_beneficios' => 'Kudeaketa Manual Onurak',
    'mut_problema_beneficios_desc' => 'Papel kupoiak, iruzurra bikoitzak erabiliz eta denden-a ezin dute despigarria egiaztatzen.',
    'mut_problema_comunicacion' => 'Komunikazioa Inefizientea',
    'mut_problema_comunicacion_desc' => 'Emailak irakurtzen ez, kartelak fisiko zaharkitua eta zailtasun guztiak elkideak bidaltzea.',
    'mut_problema_participacion' => 'Baxua Partaidetzak Asambleetan',
    'mut_problema_participacion_desc' => 'Kontrol manual quorum-en, zerrendak papelean eta tresnen falta komunitateak fomentatzea.',
    'mut_problema_crecimiento' => 'Kudeaketa Administradora Konplikatu',
    'mut_problema_crecimiento_desc' => 'Ortzearen orria, falta trazabilitate eta zailtasun txostenak sortzea.',
    'mut_problema_imagen' => 'Irudia Zaharkitua',
    'mut_problema_imagen_desc' => 'Zailtasun gataza berri gazte-kideak tradizionalak prozesuentak eta presentia digitala ez.',
];
