<?php
// Português Brasileiro - pt_BR
$lang = [
    // Meta
    'meta_title' => 'Verumax - Crie, Gerencie e Valide seu Prestígio Digital',
    'meta_description' => 'Ecossistema de ferramentas para emitir credenciais infalsificáveis, construir sua marca pessoal verificada e implementar assistentes de IA especializados.',

    // Header/Navigation
    'nav_inicio' => 'Início',
    'nav_volver_inicio' => 'Voltar ao Início',
    'nav_tema_claro' => 'Mudar para modo claro',
    'nav_tema_oscuro' => 'Mudar para modo escuro',
    'nav_soluciones' => 'Soluções Especializadas por Setor',
    'nav_ecosistema' => 'Um Ecossistema de Soluções à sua Disposição',

    // Enlaces de Navegación Rápida
    'nav_rapido_titulo' => 'O que você está procurando?',
    'nav_rapido_sectores_titulo' => 'Soluções por Setor',
    'nav_rapido_sectores_desc' => 'Acadêmico, Profissional, Eventos, Empresarial, etc.',
    'nav_rapido_ecosistema_titulo' => 'Todas as Nossas Soluções',
    'nav_rapido_ecosistema_desc' => 'Cartões, Certificados, Vouchers, Landing Pages, IA e mais',
    'nav_soluciones_academico' => 'Acadêmico',
    'nav_soluciones_profesional' => 'Profissional',
    'nav_soluciones_eventos' => 'Eventos',
    'nav_soluciones_empresarial' => 'Empresarial',
    'nav_soluciones_cooperativas' => 'Cooperativas',
    'nav_soluciones_mutuales' => 'Associações',
    'nav_productos' => 'Soluções',
    'nav_productos_tarjeta_digital' => 'Cartão Digital',
    'nav_productos_certificados' => 'Certificados Acadêmicos',
    'nav_productos_credenciales' => 'Credenciais e Documentos',
    'nav_productos_landing_personales' => 'Landing Pages Pessoais',
    'nav_productos_landing_institucionales' => 'Landing Pages Institucionais',
    'nav_productos_portfolios' => 'Portfólios Evoluídos',
    'nav_productos_cv' => 'CV Inteligentes',
    'nav_productos_autenticidad' => 'Certificados de Autenticidade',
    'nav_productos_ia' => 'Agentes de IA',
    'nav_productos_impresion' => 'Impressão Premium',
    'nav_productos_vouchers' => 'Vouchers e Cupons',
    'nav_productos_portal_comunicacion' => 'Portal de Comunicação',
    'nav_productos_encuestas' => 'Pesquisas e Votações',
    'nav_categorias' => 'Categorias',
    'nav_beneficios' => 'Benefícios',
    'nav_faq' => 'FAQ',
    'nav_validar' => 'Validar',
    'nav_demo' => 'Solicitar Demo',

    // Hero Section
    'hero_badge' => 'Confiado por instituições e profissionais globalmente',
    'hero_title_line1' => 'Crie, Gerencie e Valide',
    'hero_title_line2' => 'seu Prestígio Digital',
    'hero_subtitle' => 'Um ecossistema de ferramentas para emitir <span class="text-gold font-bold">credenciais infalsificáveis</span>, construir sua <span class="text-gold font-bold">marca pessoal verificada</span> e implementar <span class="text-gold font-bold">assistentes de IA</span> especializados.',
    'hero_cta_primary' => 'Explorar Soluções',
    'hero_cta_secondary' => 'Validar Documento',

    // Hero Mockup Mobile
    'hero_mockup_certificado' => 'Certificado',
    'hero_mockup_curso' => 'Justiça Restaurativa',
    'hero_mockup_estudiante' => 'João Silva - CPF 123.456.789-00',
    'hero_mockup_verificado' => '✓ Verificado',
    'hero_mockup_valido' => 'Válido até 2026',
    'hero_mockup_ver_detalles' => 'Ver Detalhes',
    'hero_mockup_certificados' => 'Certificados',
    'hero_mockup_en_curso' => 'Em Andamento',

    // Categorías Section
    'cat_title' => 'Soluções por Setor',
    'cat_subtitle' => 'Escolha seu setor para descobrir a solução perfeita projetada para suas necessidades específicas',

    'cat_academico' => 'Acadêmico',
    'cat_academico_1' => 'Instituições Educacionais',
    'cat_academico_2' => 'Centros de Formação',
    'cat_academico_3' => 'Formadores Particulares',
    'cat_academico_cta' => 'Ver Solução →',

    'cat_profesional' => 'Profissional',
    'cat_profesional_1' => 'Saúde e Bem-estar',
    'cat_profesional_2' => 'Engenharia e Arquitetura',
    'cat_profesional_3' => 'Todos os Profissionais',

    'cat_eventos' => 'Eventos',
    'cat_eventos_1' => 'Congressos e Conferências',
    'cat_eventos_2' => 'Festivais e Shows',
    'cat_eventos_3' => 'Controle de Acesso',

    'cat_empresarial' => 'Empresarial',
    'cat_empresarial_1' => 'Garantias e Autenticidade',
    'cat_empresarial_2' => 'Certificados de Qualidade',
    'cat_empresarial_3' => 'Recibos Validados',

    'cat_cooperativas' => 'Cooperativas',
    'cat_cooperativas_1' => 'Credenciais de Cooperados',
    'cat_cooperativas_2' => 'Certificados de Participação',
    'cat_cooperativas_3' => 'Declarações de Atividades',

    'cat_mutuales' => 'Associações',
    'cat_mutuales_1' => 'Credenciais de Associados',
    'cat_mutuales_2' => 'Comprovantes de Serviços',
    'cat_mutuales_3' => 'Carteiras de Benefícios',

    'cat_artistas' => 'Artistas',
    'cat_artistas_1' => 'Pintores',
    'cat_artistas_2' => 'Artesãos',
    'cat_artistas_3' => 'Fotógrafos',

    'cat_tarjeta_digital' => 'Cartão Digital',
    'cat_tarjeta_digital_1' => 'QR Infalsificável',
    'cat_tarjeta_digital_2' => 'Landing Page Incluída',
    'cat_tarjeta_digital_3' => 'Atualização Instantânea',
    'cat_tarjeta_digital_cta' => 'Ver Planos →',

    // Productos/Ecosistema Section
    'productos_title' => 'Um Ecossistema de Soluções à sua Disposição',
    'productos_subtitle' => 'Descubra nossas soluções especializadas. Cada uma construída sobre nossa tecnologia de validação inalterável.',

    // Soluciones del Ecosistema
    'ecosol_tarjeta_digital' => 'Cartão Digital',
    'ecosol_tarjeta_digital_desc' => 'QR infalsificável com landing page personalizada',
    'ecosol_certificados_academicos' => 'Certificados Acadêmicos',
    'ecosol_certificados_academicos_desc' => 'Diplomas e históricos digitais verificáveis',
    'ecosol_credenciales_documentos' => 'Credenciais e Documentos',
    'ecosol_credenciales_documentos_desc' => 'Documentação profissional verificada',
    'ecosol_landing_personales' => 'Landing Pages Pessoais',
    'ecosol_landing_personales_desc' => 'Landing page pessoal com sua identidade',
    'ecosol_landing_institucionales' => 'Landing Pages Institucionais',
    'ecosol_landing_institucionales_desc' => 'Presença web profissional para sua instituição',
    'ecosol_portfolios' => 'Portfólios Evoluídos',
    'ecosol_portfolios_desc' => 'Mostre seu trabalho com validação profissional',
    'ecosol_cv_inteligentes' => 'CV Inteligentes',
    'ecosol_cv_inteligentes_desc' => 'Currículo verificável e atualizável',
    'ecosol_certificados_autenticidad' => 'Certificados de Autenticidade',
    'ecosol_certificados_autenticidad_desc' => 'Para produtos, obras de arte e mais',
    'ecosol_agentes_ia' => 'Agentes de IA Especializados',
    'ecosol_agentes_ia_desc' => 'Assistentes inteligentes personalizados',
    'ecosol_impresion_premium' => 'Impressão Premium',
    'ecosol_impresion_premium_desc' => 'Documentos físicos de alta qualidade',
    'ecosol_vouchers' => 'Vouchers e Cupons Digitais',
    'ecosol_vouchers_desc' => 'Cupons de uso único com QR verificável',
    'ecosol_portal_comunicacion' => 'Portal de Comunicação',
    'ecosol_portal_comunicacion_desc' => 'Mural de novidades e anúncios oficiais',
    'ecosol_encuestas' => 'Pesquisas e Votações',
    'ecosol_encuestas_desc' => 'Participação ativa e feedback da sua comunidade',

    'cat_proximamente' => 'Em Breve',
    'cat_footer' => 'Mais categorias em breve.',
    'cat_footer_link' => 'Entre em contato',
    'cat_footer_text' => 'se seu setor não estiver listado.',

    // Servicios Principales
    'servicios_title' => 'Nossos Serviços Principais',
    'servicios_subtitle' => 'Funcionalidades essenciais que todas as nossas organizações desfrutam, independente do setor',

    'serv_antifraude' => 'Segurança Antifraude Total',
    'serv_antifraude_desc' => 'Códigos QR únicos e impossíveis de falsificar que garantem a autenticidade de cada documento.',

    'serv_portal' => 'Portal 24/7',
    'serv_portal_desc' => 'Acesso permanente para estudantes, clientes, cooperados ou funcionários de qualquer dispositivo.',

    'serv_impresion' => 'Impressão Premium',
    'serv_impresion_desc' => 'Documentos físicos de alta qualidade com hologramas e laminação, enviados para casa.',

    'serv_branding' => 'Identidade Visual Personalizada',
    'serv_branding_desc' => 'Portal e documentos com seu logo, cores e design institucional único.',

    'serv_emision' => 'Emissão Massiva',
    'serv_emision_desc' => 'Gere centenas de documentos automaticamente com notificação instantânea.',

    'serv_validacion' => 'Portal de Validação',
    'serv_validacion_desc' => 'Qualquer pessoa pode verificar a autenticidade dos seus documentos instantaneamente.',

    // Casos de Éxito
    'casos_title' => 'Casos de Sucesso',
    'casos_subtitle' => 'Instituições e profissionais que confiam no Verumax',

    'caso_sajur_org' => 'Sociedade Argentina de Justiça Restaurativa',
    'caso_sajur_tipo' => 'Organização educacional especializada',
    'caso_sajur_texto' => '"Passamos de processar manualmente cada certificado para emitir dezenas em minutos. Nossos estudantes valorizam poder acessar sua trajetória completa 24/7, e os empregadores confiam na validação QR. A economia em tempo administrativo foi de 90%."',

    'caso_liberte_org' => 'Cooperativa de Trabalho Liberté',
    'caso_liberte_tipo' => 'Formação profissional e capacitação',
    'caso_liberte_texto' => '"A implementação foi instantânea. Em menos de 24 horas já estávamos emitindo certificados com nossa marca. O portal personalizado projeta uma imagem profissional que nossos estudantes compartilham com orgulho. A opção de impressão premium é o toque final perfeito."',

    'caso_nutricion_org' => 'Lic. Maria González',
    'caso_nutricion_tipo' => 'Nutricionista profissional independente',
    'caso_nutricion_texto' => '"Meus planos nutricionais agora têm um código QR que meus pacientes podem validar. Isso aumentou significativamente a confiança e reduziu as consultas sobre autenticidade. Além disso, o envio físico premium é perfeito para quem quer tê-lo impresso."',

    'caso_empresa_org' => 'TechVision S.A.',
    'caso_empresa_tipo' => 'Empresa de tecnologia',
    'caso_empresa_texto' => '"Usamos o Verumax para emitir garantias de nossos produtos com QR verificável. Nossos clientes podem validar a autenticidade instantaneamente e acessar todas as informações técnicas. A redução em reclamações por falsificações foi de 95%."',

    // FAQ
    'faq_title' => 'Perguntas Frequentes',
    'faq_subtitle' => 'Tudo o que você precisa saber sobre o Verumax',

    'faq_1_q' => 'Quanto tempo leva para implementar o Verumax?',
    'faq_1_a' => 'Menos de 24 horas. Você só precisa configurar sua marca (logo e cores), carregar seus dados e começar a emitir. Incluímos onboarding guiado passo a passo.',

    'faq_2_q' => 'Os documentos digitais têm a mesma validade que os físicos?',
    'faq_2_a' => 'Sim. Os documentos digitais têm plena validade legal. Além disso, nosso sistema QR permite verificar a autenticidade instantaneamente, algo impossível com documentos físicos tradicionais.',

    'faq_3_q' => 'O que acontece se eu precisar de uma versão física do documento?',
    'faq_3_a' => 'Oferecemos um serviço premium de impressão HD com hologramas de segurança e laminação, enviado por correio rastreado para todo o Brasil. Você pode solicitá-lo diretamente do seu portal e receber acompanhamento do envio.',

    'faq_4_q' => 'Como funciona a validação com QR?',
    'faq_4_a' => 'Cada documento inclui um código QR único que redireciona para um portal de validação personalizado com sua marca. Lá é mostrada toda a informação do documento e sua trajetória completa. É impossível de falsificar ou alterar.',

    'faq_5_q' => 'Posso personalizar o design dos documentos?',
    'faq_5_a' => 'Sim, 100%. Cada instituição ou profissional tem seu portal completamente personalizado com seu logo, cores e design de marca. Os documentos refletem sua identidade visual única.',

    'faq_6_q' => 'Preciso de conhecimentos técnicos para usar a plataforma?',
    'faq_6_a' => 'Não. A plataforma foi projetada para ser extremamente intuitiva. Se você sabe navegar na internet, pode gerenciar o Verumax sem problemas. Além disso, oferecemos suporte técnico completo.',

    'faq_7_q' => 'O que acontece com meus dados? São seguros?',
    'faq_7_a' => 'Segurança absoluta. Usamos criptografia de nível bancário, backups automáticos diários e cumprimos as normativas de proteção de dados pessoais. Seus dados estão mais seguros que em um arquivo físico.',

    // Validar Documento Section
    'validar_title' => 'Validar um Documento',
    'validar_subtitle' => 'Digite o código de validação que aparece no documento (formato: VALID-XXXXXXXXXXXX)',
    'validar_placeholder' => 'VALID-XXXXXXXXXXXX',
    'validar_btn' => 'Validar Agora',
    'validar_ejemplo' => 'Exemplo: VALID-A1B2C3D4E5F6',

    // Contacto Section
    'contacto_title' => 'Comece a Emitir Documentos Profissionais Hoje',
    'contacto_subtitle' => 'Entre em contato para uma demonstração personalizada e descubra como o Verumax pode transformar sua gestão documental.',
    'contacto_nombre' => 'Nome Completo',
    'contacto_email' => 'Email',
    'contacto_institucion' => 'Instituição/Organização',
    'contacto_mensaje' => 'Conte-nos sobre sua necessidade...',
    'contacto_btn' => 'Solicitar Demonstração',
    'contacto_info' => 'Ou escreva-nos diretamente:',

    // Footer
    'footer_descripcion' => 'A plataforma definitiva para documentos digitais e físicos seguros com validação QR.',
    'footer_enlaces' => 'Links Rápidos',
    'footer_inicio' => 'Início',
    'footer_legal' => 'Legal',
    'footer_caracteristicas' => 'Características',
    'footer_contacto' => 'Contato',
    'footer_seguridad' => 'Tecnologia e Segurança de Nível Empresarial',
    'footer_copyright' => 'Todos os direitos reservados.',
    'footer_terminos' => 'Termos de Serviço',
    'footer_privacidad' => 'Política de Privacidade',

    // Badges de Seguridad
    'badge_ssl' => 'SSL',
    'badge_ssl_desc' => 'Criptografia 256-bit',
    'badge_https' => 'HTTPS',
    'badge_https_desc' => 'Conexão Segura',
    'badge_privacidad' => 'Privacidade',
    'badge_privacidad_desc' => 'Dados Protegidos',
    'badge_backup' => 'Backup',
    'badge_backup_desc' => 'Automático Diário',
    'badge_uptime' => 'Uptime 99.9%',
    'badge_uptime_desc' => 'Disponibilidade',
    'badge_soporte' => 'Suporte',
    'badge_soporte_desc' => 'Técnico 24/7',

    // Veritas IA Chat
    'veritas_chat_btn' => 'Chat com Veritas IA',
    'veritas_titulo' => 'Veritas IA',
    'veritas_subtitulo' => 'Nosso Agente de Inteligência Artificial Especializado',
    'veritas_proximamente' => 'Em breve!',
    'veritas_descripcion' => 'Veritas estará disponível muito em breve para ajudá-lo com consultas sobre certificados, validações e mais.',
    'veritas_entendido' => 'Entendido',

    // Estadísticas Hero
    'stat_uptime' => 'Disponibilidade',
    'stat_documentos' => 'Documentos emitidos',
    'stat_acceso' => 'Acesso disponível',
    'stat_ahorro' => 'Economia em custos administrativos',

    // Social Proof Contacto
    'social_confianza' => 'Instituições e profissionais que já confiam no Verumax',
    'social_mas' => '+ mais organizações e profissionais',

    // Beneficios Contacto
    'benefit_demo' => 'Demo grátis sem compromisso',
    'benefit_demo_desc' => 'Teste todas as funcionalidades',
    'benefit_implementacion' => 'Implementação em 24h',
    'benefit_implementacion_desc' => 'Comece a emitir amanhã',
    'benefit_soporte' => 'Suporte técnico incluído',
    'benefit_soporte_desc' => 'Assistência completa',

    // CTA Contacto
    'contacto_cta_btn' => 'Solicitar Demo Grátis',
    'contacto_cta_email' => 'Ou escreva-nos para',

    // Footer - Enlaces rápidos
    'footer_link_beneficios' => 'Benefícios',
    'footer_link_como' => 'Como Funciona',
    'footer_link_validar' => 'Validar Documento',
    'footer_link_demo' => 'Solicitar Demo',

    // Footer - Características
    'footer_feat_qr' => 'Validação QR',
    'footer_feat_portal' => 'Portal 24/7',
    'footer_feat_impresion' => 'Impressão Premium',
    'footer_feat_personalizable' => '100% Personalizável',

    // Footer - Contacto
    'footer_horario' => 'Segunda a Sexta: 9:00 - 18:00',

    // Página de Privacidad
    'privacidad_title' => 'Política de Privacidade',
    'privacidad_updated' => 'Última atualização',

    // Página de Términos de Servicio
    'terminos_title' => 'Termos de Serviço',
    'terminos_updated' => 'Última atualização',

    // Términos de Servicio - Contenido
    'terminos_seccion1_titulo' => '1. Aceitação dos Termos',
    'terminos_seccion1_p1' => 'Ao acessar e utilizar a plataforma Verumax ("o Serviço"), você aceita estar legalmente vinculado por estes Termos de Serviço. Se não concordar com estes termos, não utilize o Serviço.',
    'terminos_seccion1_p2' => 'O Verumax se reserva o direito de modificar estes termos a qualquer momento. As alterações entrarão em vigor imediatamente após sua publicação no site.',

    'terminos_seccion2_titulo' => '2. Descrição do Serviço',
    'terminos_seccion2_p1' => 'O Verumax é uma plataforma que permite a instituições educacionais, profissionais independentes, organizadores de eventos, empresas, cooperativas e associações emitir, gerenciar e validar documentos digitais com códigos QR de verificação.',
    'terminos_seccion2_p2' => 'Os serviços incluem, mas não se limitam a:',
    'terminos_seccion2_li1' => 'Emissão de documentos digitais personalizados',
    'terminos_seccion2_li2' => 'Portal personalizado para cada instituição/profissional',
    'terminos_seccion2_li3' => 'Sistema de validação com códigos QR únicos',
    'terminos_seccion2_li4' => 'Armazenamento seguro na nuvem',
    'terminos_seccion2_li5' => 'Opção de impressão premium de documentos físicos',
    'terminos_seccion2_li6' => 'Emissão massiva de documentos',

    'terminos_seccion3_titulo' => '3. Registro e Conta de Usuário',
    'terminos_seccion3_p1' => 'Para utilizar o Serviço, você deve criar uma conta fornecendo informações precisas, completas e atualizadas. Você é responsável por:',
    'terminos_seccion3_li1' => 'Manter a confidencialidade de sua senha e credenciais de acesso',
    'terminos_seccion3_li2' => 'Todas as atividades que ocorram sob sua conta',
    'terminos_seccion3_li3' => 'Notificar imediatamente qualquer uso não autorizado de sua conta',
    'terminos_seccion3_li4' => 'Fornecer dados verdadeiros de sua instituição ou organização',
    'terminos_seccion3_p2' => 'O Verumax se reserva o direito de suspender ou cancelar contas que violem estes termos ou que forneçam informações falsas.',

    'terminos_seccion4_titulo' => '4. Uso Permitido',
    'terminos_seccion4_p1' => 'O Serviço só pode ser utilizado para fins legítimos e de acordo com estes Termos. Não é permitido utilizar o Verumax para atividades fraudulentas, ilegais ou que infrinjam direitos de terceiros.',

    'terminos_seccion5_titulo' => '5. Propriedade Intelectual',
    'terminos_seccion5_p1' => 'Todo o conteúdo, design, logos e tecnologia do Verumax são propriedade exclusiva da plataforma e estão protegidos pelas leis de propriedade intelectual.',

    'terminos_seccion6_titulo' => '6. Limitação de Responsabilidade',
    'terminos_seccion6_p1' => 'O Verumax não será responsável por danos indiretos, incidentais ou consequentes derivados do uso ou impossibilidade de uso do Serviço.',

    'terminos_seccion7_titulo' => '7. Contato',
    'terminos_seccion7_p1' => 'Para consultas sobre estes Termos de Serviço, entre em contato em:',

    // Política de Privacidad - Contenido
    'privacidad_intro_titulo' => 'Introdução',
    'privacidad_intro_p1' => 'No Verumax, a privacidade e segurança dos seus dados é nossa máxima prioridade. Esta Política de Privacidade descreve como coletamos, usamos, armazenamos e protegemos suas informações pessoais quando você utiliza nossos serviços.',
    'privacidad_intro_p2' => 'Ao utilizar o Verumax, você aceita as práticas descritas nesta política. Se não concordar, não utilize nossos serviços.',

    'privacidad_seccion1_titulo' => '1. Informações que Coletamos',
    'privacidad_seccion1_sub1_titulo' => '1.1 Informações da Conta',
    'privacidad_seccion1_sub1_p1' => 'Quando você cria uma conta, coletamos:',
    'privacidad_seccion1_sub1_li1' => 'Nome completo e dados de contato (e-mail, telefone)',
    'privacidad_seccion1_sub1_li2' => 'Nome da instituição, organização ou profissional independente',
    'privacidad_seccion1_sub1_li3' => 'Endereço físico e fiscal',
    'privacidad_seccion1_sub1_li4' => 'Informações de cobrança e pagamento',
    'privacidad_seccion1_sub1_li5' => 'Credenciais de acesso (usuário/senha criptografada)',
    'privacidad_seccion1_sub2_titulo' => '1.2 Dados de Documentos e Beneficiários',
    'privacidad_seccion1_sub2_p1' => 'Ao emitir documentos, coletamos dados dos beneficiários (estudantes, clientes, funcionários, cooperados, etc.):',
    'privacidad_seccion1_sub2_li1' => 'Nome completo e número de identificação (CPF, RG, etc.)',
    'privacidad_seccion1_sub2_li2' => 'E-mail e telefone (para notificações)',
    'privacidad_seccion1_sub2_li3' => 'Dados acadêmicos, profissionais ou trabalhistas relacionados ao documento emitido',
    'privacidad_seccion1_sub2_li4' => 'Fotografia (opcional, se incluída no documento)',
    'privacidad_seccion1_sub3_titulo' => '1.3 Dados de Uso e Técnicos',
    'privacidad_seccion1_sub3_li1' => 'Endereço IP, navegador, sistema operacional',
    'privacidad_seccion1_sub3_li2' => 'Páginas visitadas, tempo de sessão, cliques',
    'privacidad_seccion1_sub3_li3' => 'Registros de validação de documentos (quem validou, quando, de onde)',
    'privacidad_seccion1_sub3_li4' => 'Métricas de uso do portal (downloads, acessos, etc.)',

    'privacidad_seccion2_titulo' => '2. Como Usamos suas Informações',
    'privacidad_seccion2_p1' => 'Utilizamos os dados coletados para:',
    'privacidad_seccion2_li1_strong' => 'Prover o Serviço:',
    'privacidad_seccion2_li1_texto' => 'Gerar, armazenar e gerenciar documentos digitais',
    'privacidad_seccion2_li2_strong' => 'Validação:',
    'privacidad_seccion2_li2_texto' => 'Verificar a autenticidade de documentos mediante códigos QR',
    'privacidad_seccion2_li3_strong' => 'Notificações:',
    'privacidad_seccion2_li3_texto' => 'Enviar e-mails sobre documentos emitidos, atualizações do serviço',
    'privacidad_seccion2_li4_strong' => 'Cobrança:',
    'privacidad_seccion2_li4_texto' => 'Processar pagamentos e emitir faturas',
    'privacidad_seccion2_li5_strong' => 'Melhoria do Serviço:',
    'privacidad_seccion2_li5_texto' => 'Analisar métricas de uso para otimizar funcionalidades',
    'privacidad_seccion2_li6_strong' => 'Suporte Técnico:',
    'privacidad_seccion2_li6_texto' => 'Resolver consultas e problemas técnicos',
    'privacidad_seccion2_li7_strong' => 'Cumprimento Legal:',
    'privacidad_seccion2_li7_texto' => 'Cumprir obrigações legais e regulatórias',

    'privacidad_seccion3_titulo' => '3. Compartilhar Informações com Terceiros',
    'privacidad_seccion3_p1_strong' => 'Não vendemos nem alugamos',
    'privacidad_seccion3_p1_normal' => 'seus dados pessoais a terceiros. Só compartilhamos informações nestes casos limitados:',
    'privacidad_seccion3_sub1_titulo' => '3.1 Provedores de Serviços',
    'privacidad_seccion3_sub1_p1' => 'Trabalhamos com provedores confiáveis que nos ajudam a operar o Serviço:',
    'privacidad_seccion3_sub1_li1' => 'Hospedagem e armazenamento na nuvem (servidores seguros)',
    'privacidad_seccion3_sub1_li2' => 'Processadores de pagamentos (com certificação PCI-DSS)',
    'privacidad_seccion3_sub1_li3' => 'Serviços de e-mail transacional',
    'privacidad_seccion3_sub1_li4' => 'Serviços de impressão e envio (só para documentos físicos solicitados)',
    'privacidad_seccion3_sub1_p2' => 'Todos os provedores estão contratualmente obrigados a proteger seus dados e não podem usá-los para outros fins.',
    'privacidad_seccion3_sub2_titulo' => '3.2 Requerimentos Legais',
    'privacidad_seccion3_sub2_p1' => 'Podemos divulgar informações se a lei exigir (ordem judicial, processo legal) ou para proteger nossos direitos legais.',
    'privacidad_seccion3_sub3_titulo' => '3.3 Validação Pública',
    'privacidad_seccion3_sub3_p1' => 'Os documentos emitidos são validáveis publicamente mediante código QR. A informação mostrada na validação (nome do beneficiário, instituição emissora, dados do documento) é visível para quem escanear o código.',

    'privacidad_seccion4_titulo' => '4. Segurança dos Dados',
    'privacidad_seccion4_p1' => 'Implementamos medidas de segurança de nível empresarial:',
    'privacidad_seccion4_li1_strong' => 'Criptografia SSL/TLS 256-bit:',
    'privacidad_seccion4_li1_texto' => 'Todas as comunicações estão criptografadas',
    'privacidad_seccion4_li2_strong' => 'Senhas protegidas:',
    'privacidad_seccion4_li2_texto' => 'Armazenadas com hash e salt (bcrypt)',
    'privacidad_seccion4_li3_strong' => 'Backups automáticos diários:',
    'privacidad_seccion4_li3_texto' => 'Com criptografia e armazenamento redundante',
    'privacidad_seccion4_li4_strong' => 'Firewall e monitoramento 24/7:',
    'privacidad_seccion4_li4_texto' => 'Proteção contra acessos não autorizados',
    'privacidad_seccion4_li5_strong' => 'Auditorias de segurança:',
    'privacidad_seccion4_li5_texto' => 'Revisões periódicas de vulnerabilidades',
    'privacidad_seccion4_li6_strong' => 'Acesso restrito:',
    'privacidad_seccion4_li6_texto' => 'Só pessoal autorizado pode acessar dados sensíveis',
    'privacidad_seccion4_p2' => 'Apesar destas medidas, nenhum sistema é 100% seguro. Recomendamos usar senhas fortes e não compartilhar suas credenciais.',

    'privacidad_seccion5_titulo' => '5. Retenção de Dados',
    'privacidad_seccion5_p1' => 'Conservamos seus dados enquanto mantiver uma conta ativa ou conforme exigir a lei:',
    'privacidad_seccion5_li1_strong' => 'Dados da conta:',
    'privacidad_seccion5_li1_texto' => 'Até você cancelar sua conta + período legal mínimo (geralmente 10 anos para fins fiscais)',
    'privacidad_seccion5_li2_strong' => 'Documentos emitidos:',
    'privacidad_seccion5_li2_texto' => 'Permanentemente, já que servem como registro histórico e validação',
    'privacidad_seccion5_li3_strong' => 'Registros de validação:',
    'privacidad_seccion5_li3_texto' => '5 anos para auditoria e prevenção de fraude',
    'privacidad_seccion5_li4_strong' => 'Dados de cobrança:',
    'privacidad_seccion5_li4_texto' => '10 anos segundo normativas contábeis',
    'privacidad_seccion5_p2' => 'Ao cancelar sua conta, eliminamos dados desnecessários de forma segura, mas conservamos registros históricos segundo obrigações legais.',

    'privacidad_seccion6_titulo' => '6. Seus Direitos',
    'privacidad_seccion6_p1' => 'Segundo as leis de proteção de dados pessoais, você tem direito a:',
    'privacidad_seccion6_li1_strong' => 'Acesso:',
    'privacidad_seccion6_li1_texto' => 'Solicitar uma cópia dos seus dados pessoais que temos armazenados',
    'privacidad_seccion6_li2_strong' => 'Retificação:',
    'privacidad_seccion6_li2_texto' => 'Corrigir dados inexatos ou incompletos',
    'privacidad_seccion6_li3_strong' => 'Eliminação:',
    'privacidad_seccion6_li3_texto' => 'Solicitar a eliminação dos seus dados (sujeito a obrigações legais)',
    'privacidad_seccion6_li4_strong' => 'Limitação:',
    'privacidad_seccion6_li4_texto' => 'Restringir certos usos dos seus dados',
    'privacidad_seccion6_li5_strong' => 'Portabilidade:',
    'privacidad_seccion6_li5_texto' => 'Receber seus dados em formato estruturado e transferível',
    'privacidad_seccion6_li6_strong' => 'Oposição:',
    'privacidad_seccion6_li6_texto' => 'Opor-se ao processamento dos seus dados em certas circunstâncias',
    'privacidad_seccion6_li7_strong' => 'Revogação de consentimento:',
    'privacidad_seccion6_li7_texto' => 'Retirar o consentimento concedido a qualquer momento',
    'privacidad_seccion6_p2_antes_link' => 'Para exercer estes direitos, entre em contato em',
    'privacidad_seccion6_p2_link_texto' => 'privacidade@validarcert.com',
    'privacidad_seccion6_p2_normal' => 'Responderemos dentro de 15 dias úteis.',

    'privacidad_seccion7_titulo' => '7. Cookies e Tecnologias Similares',
    'privacidad_seccion7_p1' => 'Utilizamos cookies e tecnologias similares para:',
    'privacidad_seccion7_li1_strong' => 'Cookies essenciais:',
    'privacidad_seccion7_li1_texto' => 'Para o funcionamento do portal (sessão, autenticação)',
    'privacidad_seccion7_li2_strong' => 'Cookies analíticos:',
    'privacidad_seccion7_li2_texto' => 'Para entender como você usa o serviço e melhorá-lo (anônimos)',
    'privacidad_seccion7_li3_strong' => 'Cookies de preferências:',
    'privacidad_seccion7_li3_texto' => 'Para lembrar suas configurações (idioma, tema, etc.)',
    'privacidad_seccion7_p2' => 'Você pode configurar seu navegador para rejeitar cookies, mas isso pode afetar a funcionalidade do Serviço.',

    'privacidad_seccion8_titulo' => '8. Transferências Internacionais',
    'privacidad_seccion8_p1' => 'Seus dados são armazenados principalmente em servidores localizados no Brasil. Em alguns casos, provedores de serviços podem processar dados em outros países com níveis adequados de proteção de dados (ex: Estados Unidos sob Data Privacy Framework, União Europeia sob GDPR).',

    'privacidad_seccion9_titulo' => '9. Privacidade de Menores',
    'privacidad_seccion9_p1' => 'Nosso Serviço não está dirigido a menores de 13 anos. Se descobrirmos que coletamos dados de um menor sem consentimento parental, eliminaremos essa informação imediatamente.',
    'privacidad_seccion9_p2' => 'Para beneficiários menores de idade cujos documentos são emitidos por instituições educacionais, o consentimento se presume concedido pela instituição que atua como representante legal.',

    'privacidad_seccion10_titulo' => '10. Mudanças nesta Política',
    'privacidad_seccion10_p1' => 'Podemos atualizar esta Política de Privacidade ocasionalmente. As mudanças significativas serão notificadas por e-mail ou mediante aviso destacado no portal. A data de "Última atualização" no topo indica quando foi realizada a última modificação.',

    'privacidad_seccion11_titulo' => '11. Contato',
    'privacidad_seccion11_p1' => 'Para consultas, exercer seus direitos ou reportar problemas de privacidade:',
    'privacidad_seccion11_email_privacidad' => 'privacidade@validarcert.com',
    'privacidad_seccion11_email_general_label' => 'E-mail geral:',
    'privacidad_seccion11_email_general' => 'contato@validarcert.com',

    'privacidad_seccion12_titulo' => '12. Autoridade de Aplicação',
    'privacidad_seccion12_p1_antes_strong' => 'No Brasil, a autoridade de aplicação em matéria de proteção de dados pessoais é a',
    'privacidad_seccion12_p1_strong' => 'ANPD (Autoridade Nacional de Proteção de Dados)',
    'privacidad_seccion12_p1_normal' => '. Se você considerar que seus direitos foram violados, pode apresentar uma denúncia junto a este organismo.',
    'privacidad_seccion12_aaip_label' => 'ANPD:',
    'privacidad_seccion12_aaip_url' => 'www.gov.br/anpd',

    // === ACADÉMICO PAGE ===

    // Navigation
    'acad_nav_beneficios' => 'Benefícios',
    'acad_nav_funcionalidades' => 'Funcionalidades',
    'acad_nav_casos_exito' => 'Casos de Sucesso',
    'acad_nav_planes' => 'Planos',
    'acad_nav_faq' => 'Perguntas Frequentes',
    'acad_nav_solicitar_demo' => 'Solicitar Demonstração',
    'acad_nav_academico' => 'Acadêmico',

    // Hero Section
    'acad_hero_badge' => '✓ Solução Acadêmica Completa',
    'acad_hero_title' => 'Certificações Acadêmicas',
    'acad_hero_title_highlight' => 'Digitais Profissionais',
    'acad_hero_subtitle' => 'Solução completa para',
    'acad_hero_instituciones' => 'instituições educacionais',
    'acad_hero_centros_formacion' => 'centros de formação',
    'acad_hero_academias' => 'academias',
    'acad_hero_formadores' => 'formadores particulares',
    'acad_cta_solicitar_demo' => 'Solicitar Demonstração Personalizada',
    'acad_cta_ver_como_funciona' => 'Veja Como Funciona',

    // Hero Value Proposition
    'acad_hero_propuesta_valor' => 'O sistema faz tudo. Você só carrega os dados uma vez.',
    'acad_hero_benefit_1' => 'Geração automática',
    'acad_hero_benefit_2' => 'Notificação por email',
    'acad_hero_benefit_3' => 'QR infalsificável',
    'acad_hero_benefit_4' => 'Download 24/7',

    // Hero Stats
    'acad_hero_stat_tiempo' => 'Menos tempo administrativo',
    'acad_hero_stat_portal' => 'Portal do estudante',
    'acad_hero_stat_falsificaciones' => 'Falsificações possíveis',

    // Sección ROI - Retorno de Inversión
    'acad_roi_titulo' => 'Retorno de Investimento Comprovado',
    'acad_roi_subtitulo' => 'Resultados reais de instituições que já usam Certificatum',
    'acad_roi_ahorro_impresion' => 'Economia mensal em impressão',
    'acad_roi_ahorro_tiempo' => 'Economia em tempo administrativo',
    'acad_roi_reduccion_consultas' => 'Redução de consultas telefônicas',
    'acad_roi_payback' => 'Tempo de Payback',
    'acad_roi_stat_impresion' => '$$$',
    'acad_roi_stat_tiempo' => '40hs',
    'acad_roi_stat_consultas' => '80%',
    'acad_roi_stat_payback' => '2 meses',

    // Tabla Comparativa
    'acad_vs_titulo' => 'Certificatum vs Alternativas',
    'acad_vs_subtitulo' => 'Compare as opções do mercado',
    'acad_vs_aspecto' => 'Aspecto',
    'acad_vs_papel' => 'Papel Tradicional',
    'acad_vs_plataformas' => 'Plataformas Globais',
    'acad_vs_certificatum' => 'Certificatum',
    'acad_vs_costo_emision' => 'Custo de emissão',
    'acad_vs_costo_alto' => 'Alto (impressão, assinaturas)',
    'acad_vs_costo_porcentaje' => '% de vendas',
    'acad_vs_costo_cero' => 'Zero marginal',
    'acad_vs_validacion' => 'Validação',
    'acad_vs_validacion_tel' => 'Ligação telefônica',
    'acad_vs_validacion_generica' => 'Genérica',
    'acad_vs_validacion_qr' => 'QR Instantâneo 24/7',
    'acad_vs_branding' => 'Identidade Visual',
    'acad_vs_branding_suyo' => '100% sua',
    'acad_vs_branding_limitado' => 'Limitada',
    'acad_vs_branding_total' => '100% personalizada',
    'acad_vs_falsificacion' => 'Falsificação',
    'acad_vs_falsificacion_facil' => 'Fácil',
    'acad_vs_falsificacion_posible' => 'Possível',
    'acad_vs_falsificacion_imposible' => 'Impossível',
    'acad_vs_datos' => 'Dados',
    'acad_vs_datos_fisico' => 'Arquivo físico',
    'acad_vs_datos_ellos' => 'São deles',
    'acad_vs_datos_suyos' => 'São 100% seus',

    // Panel de Administración
    'acad_panel_titulo' => 'Painel de Administração Completo',
    'acad_panel_subtitulo' => 'Tudo o que você precisa para gerenciar sua instituição',
    'acad_panel_carga_masiva' => 'Carga massiva desde Excel/CSV',
    'acad_panel_crud' => 'CRUD completo de estudantes e cursos',
    'acad_panel_dashboard' => 'Dashboard com analytics em tempo real',
    'acad_panel_multiusuario' => 'Gestão multi-usuário com papéis',

    // Problemas Section
    'acad_problemas_titulo' => 'Isso parece familiar?',
    'acad_problemas_subtitulo' => 'Estas são as dores de cabeça que o Certificatum elimina',
    'acad_problema_trabajo_manual' => 'Horas de Trabalho Manual',
    'acad_problema_trabajo_manual_desc' => 'Projetar e emitir cada certificado individualmente consome tempo valioso que você poderia dedicar ao ensino.',
    'acad_problema_perdidos' => 'Certificados Perdidos',
    'acad_problema_perdidos_desc' => 'Alunos que perdem ou danificam documentos e solicitam reemissões constantemente.',
    'acad_problema_falsificaciones' => 'Falsificações',
    'acad_problema_falsificaciones_desc' => 'Títulos e certificados falsos circulando sem forma efetiva de verificar sua autenticidade.',
    'acad_problema_trazabilidad' => 'Sem Rastreabilidade',
    'acad_problema_trazabilidad_desc' => 'Falta de histórico acadêmico completo e verificável de cada estudante.',
    'acad_problema_costos' => 'Custos de Impressão',
    'acad_problema_costos_desc' => 'Gastos elevados em papel especial, impressão, toner e armazenamento físico.',
    'acad_problema_archivos' => 'Arquivos Físicos Caóticos',
    'acad_problema_archivos_desc' => 'Montanhas de papéis ocupando espaço valioso e dificultando a busca de informação.',

    // Cómo Funciona Section
    'acad_como_funciona_titulo' => 'Tão simples quanto 1, 2, 3',
    'acad_como_funciona_subtitulo' => 'Implementação imediata, sem complicações técnicas',
    'acad_como_funciona_paso1_titulo' => 'Configure sua Instituição',
    'acad_como_funciona_paso1_desc' => 'Personalize com seu logo, cores institucionais e defina os tipos de certificados que emitirá.',
    'acad_como_funciona_paso2_titulo' => 'Carregue Estudantes e Cursos',
    'acad_como_funciona_paso2_desc' => 'Importe dados massivamente desde Excel ou CSV. Também pode carregar um por um.',
    'acad_como_funciona_paso2_alt' => 'Ou simplesmente envie suas listas e nossa equipe as importa por você.',
    'acad_como_funciona_paso3_titulo' => 'Emita e Valide',
    'acad_como_funciona_paso3_desc' => 'Geração automática com QR único. Notificação por e-mail e acesso imediato para estudantes.',
    'acad_como_funciona_paso3_alt' => 'Também pode solicitar a emissão à nossa equipe e só se preocupar em compartilhar.',

    // Tipos de Documentos
    'acad_documentos_titulo' => 'Tipos de Documentos Acadêmicos',
    'acad_documentos_subtitulo' => 'Todos os documentos que sua instituição precisa emitir',
    'acad_documentos_principales' => 'Documentos Principais',
    'acad_doc_certificado_aprobacion' => 'Certificados de Aprovação',
    'acad_doc_certificado_aprobacion_desc' => 'Certificado oficial que credencia a aprovação de um curso, disciplina ou programa completo.',
    'acad_doc_diplomas' => 'Diplomas de Conclusão',
    'acad_doc_diplomas_desc' => 'Título ou diploma formal que certifica a conclusão exitosa de um programa acadêmico completo.',
    'acad_doc_analiticos' => 'Históricos Acadêmicos',
    'acad_doc_analiticos_desc' => 'Histórico completo com todas as disciplinas cursadas, notas, presenças e competências adquiridas.',
    'acad_doc_constancia_regular' => 'Declarações de Aluno Regular',
    'acad_doc_constancia_regular_desc' => 'Documento que credencia que o estudante está atualmente cursando na instituição.',
    'acad_doc_constancia_inscripcion' => 'Declarações de Matrícula',
    'acad_doc_constancia_inscripcion_desc' => 'Comprovante de matrícula em um curso, disciplina ou programa acadêmico específico.',
    'acad_doc_constancia_finalizacion' => 'Declarações de Conclusão de Cursada',
    'acad_doc_constancia_finalizacion_desc' => 'Certificado que credencia ter completado a cursada, prévio à avaliação final.',

    // Documentos Complementarios
    'acad_documentos_complementarios' => 'Documentos Complementares',
    'acad_doc_asistencia' => 'Certificados de Participação',
    'acad_doc_asistencia_desc' => 'Para workshops, seminários, webinars ou eventos educacionais pontuais.',
    'acad_doc_reconocimientos' => 'Reconhecimentos e Menções',
    'acad_doc_reconocimientos_desc' => 'Prêmios especiais, menções honrosas ou reconhecimentos por desempenho destacado.',
    'acad_doc_competencias' => 'Certificados de Competências',
    'acad_doc_competencias_desc' => 'Creditam habilidades e competências específicas adquiridas durante a formação.',
    'acad_doc_practica' => 'Declarações de Prática Profissional',
    'acad_doc_practica_desc' => 'Documentam estágios, práticas profissionais ou experiência laboral supervisionada.',
    'acad_doc_congresos' => 'Certificados de Participação em Congressos',
    'acad_doc_congresos_desc' => 'Para participação ou apresentações em congressos, jornadas acadêmicas e conferências.',

    // Portal del Estudiante
    'acad_portal_badge' => '★ Feature Destacado',
    'acad_portal_titulo' => 'Portal do Estudante 24/7',
    'acad_portal_subtitulo' => 'Cada estudante tem acesso ao seu próprio portal, personalizado com a identidade visual e o logo da sua instituição. A partir dele, podem ver seu progresso e baixar todos os seus documentos.',
    'acad_portal_acceso_titulo' => 'Acesso 24/7 à sua trajetória completa',
    'acad_portal_acceso_desc' => 'Estudantes acessam de qualquer dispositivo, a qualquer momento.',
    'acad_portal_descarga_titulo' => 'Download de todos os seus documentos',
    'acad_portal_descarga_desc' => 'Diplomas, declarações, certificados, históricos - tudo em um só lugar.',
    'acad_portal_timeline_titulo' => 'Vista de timeline acadêmico',
    'acad_portal_timeline_desc' => 'Visualização cronológica de toda sua trajetória educativa.',
    'acad_portal_qr_titulo' => 'QR individual por documento',
    'acad_portal_qr_desc' => 'Cada documento tem seu código único de validação.',
    'acad_portal_linkedin_titulo' => 'Compartilhar no LinkedIn com um clique',
    'acad_portal_linkedin_desc' => 'Integração direta para publicar conquistas acadêmicas.',

    // Portal Demo Data
    'acad_portal_demo_nombre' => 'João Silva',
    'acad_portal_demo_dni' => 'CPF: 123.456.789-00',
    'acad_portal_demo_progreso' => 'de 4 cursos completados',
    'acad_portal_demo_diploma' => 'Diploma - Justiça Restaurativa',
    'acad_portal_demo_diploma_fecha' => 'Concluído: 15/03/2024',
    'acad_portal_demo_certificado' => 'Certificado - Mediação',
    'acad_portal_demo_certificado_fecha' => 'Concluído: 20/01/2024',
    'acad_portal_demo_curso_progreso' => 'Curso em Andamento',
    'acad_portal_demo_curso_nombre' => 'Resolução de Conflitos',

    // Casos de Uso
    'acad_casos_uso_titulo' => 'Para Quem é o Certificatum?',
    'acad_casos_uso_subtitulo' => 'Instituições e profissionais que confiam em nossa plataforma',
    'acad_caso_universidades' => 'Universidades e Faculdades',
    'acad_caso_universidades_desc' => 'Gestão massiva de títulos, diplomas e históricos para centenas de graduados.',
    'acad_caso_centros' => 'Centros de Formação',
    'acad_caso_centros_desc' => 'Instituições como SAJuR e Liberté que emitem certificações profissionais.',
    'acad_caso_idiomas' => 'Escolas de Idiomas',
    'acad_caso_idiomas_desc' => 'Certificados de níveis completados com validação internacional.',
    'acad_caso_tecnicos' => 'Institutos Técnicos',
    'acad_caso_tecnicos_desc' => 'Certificações técnicas e ofícios com rastreabilidade completa.',
    'acad_caso_laboral' => 'Capacitação Profissional',
    'acad_caso_laboral_desc' => 'Centros de formação continuada e desenvolvimento profissional.',
    'acad_caso_continua' => 'Educação Continuada',
    'acad_caso_continua_desc' => 'Programas de atualização profissional e pós-graduações.',
    'acad_caso_organizadores' => 'Organizadores de Cursos',
    'acad_caso_organizadores_desc' => 'Diplomas e certificados para cursos, workshops e programas especiais.',
    'acad_caso_particulares' => 'Formadores Particulares',
    'acad_caso_particulares_desc' => 'Docentes independentes que emitem certificações profissionais.',

    // Funcionalidades
    'acad_func_titulo' => 'Funcionalidades Pensadas para Instituições',
    'acad_func_subtitulo' => 'Tudo o que você precisa para gerenciar certificações acadêmicas',
    'acad_func_cohortes' => 'Gestão de Turmas',
    'acad_func_cohortes_desc' => 'Organize estudantes por turma, ano ou grupo. Emita documentos massivamente por turma completa.',
    'acad_func_emision_masiva' => 'Emissão Massiva',
    'acad_func_emision_masiva_desc' => 'Gere certificados para 100+ alunos em minutos. Um só clique para toda uma promoção.',
    'acad_func_notificaciones' => 'Notificações Automáticas por E-mail',
    'acad_func_notificaciones_desc' => 'Cada estudante recebe notificação automática quando se emite um documento.',
    'acad_func_branding' => 'Portal com Identidade Visual Institucional',
    'acad_func_branding_desc' => 'Seu logo, cores e domínio. Cada instituição projeta sua própria identidade.',
    'acad_func_trayectoria' => 'Trajetória Acadêmica Completa',
    'acad_func_trayectoria_desc' => 'Histórico verificável com todos os cursos, notas e conquistas do estudante.',
    'acad_func_validacion' => 'Validação Pública Instantânea',
    'acad_func_validacion_desc' => 'Empregadores escaneiam o QR e verificam autenticidade instantaneamente.',

    // Beneficios
    'acad_beneficios_titulo' => 'Resultados Mensuráveis',
    'acad_beneficios_subtitulo' => 'Impacto real em sua instituição desde o primeiro dia',
    'acad_beneficio_tiempo_titulo' => 'Menos Tempo Administrativo',
    'acad_beneficio_tiempo_desc' => 'O que levava horas agora leva minutos',
    'acad_beneficio_ahorro_titulo' => 'Economia em Custos',
    'acad_beneficio_ahorro_desc' => 'Redução drástica em impressão e papelaria',
    'acad_beneficio_falsificaciones_titulo' => 'Falsificações Possíveis',
    'acad_beneficio_falsificaciones_desc' => 'Impossível clonar códigos QR únicos',
    'acad_beneficio_acceso_titulo' => 'Acesso para Estudantes',
    'acad_beneficio_acceso_desc' => 'Portal disponível a todo momento',
    'acad_beneficio_trazabilidad_titulo' => '100% Rastreabilidade e Auditoria',
    'acad_beneficio_trazabilidad_desc' => 'Cada ação fica registrada. Você sabe exatamente quem emitiu qual documento, quando e para quem. Ideal para auditorias e cumprimento normativo.',

    // Casos de Éxito
    'acad_casos_exito_titulo' => 'Casos de Sucesso',
    'acad_casos_exito_subtitulo' => 'Instituições que transformaram sua gestão acadêmica',
    'acad_caso_sajur_nombre' => 'Sociedade Argentina de Justiça Restaurativa',
    'acad_caso_sajur_tipo' => 'Centro de formação especializada',
    'acad_caso_sajur_testimonio' => '"Passamos de processar manualmente cada certificado para emitir dezenas em minutos. Nossos estudantes valorizam poder acessar sua trajetória completa 24/7, e os empregadores confiam na validação QR. A economia em tempo administrativo foi de 90%."',
    'acad_caso_liberte_nombre' => 'Cooperativa de Trabalho Liberté',
    'acad_caso_liberte_tipo' => 'Formação profissional e capacitação',
    'acad_caso_liberte_testimonio' => '"A implementação foi instantânea. Em menos de 24 horas já estávamos emitindo certificados com nossa marca. O portal personalizado projeta uma imagem profissional que nossos estudantes compartilham com orgulho. A opção de impressão premium é o toque final perfeito."',

    // Antes vs Después
    'acad_antes_despues_titulo' => 'Antes vs Depois do Certificatum',
    'acad_antes_despues_subtitulo' => 'A transformação digital da sua gestão acadêmica',
    'acad_antes_titulo' => 'Antes (Tradicional)',
    'acad_antes_trabajo_manual' => 'Horas de trabalho manual por cada certificado',
    'acad_antes_costos' => 'Custos elevados de impressão e papelaria',
    'acad_antes_falsificacion' => 'Risco de falsificação sem forma de verificar',
    'acad_antes_presencial' => 'Estudantes devem vir presencialmente para retirar',
    'acad_antes_almacenamiento' => 'Armazenamento físico caótico e espaço ocupado',
    'acad_antes_estadisticas' => 'Sem estatísticas nem métricas de emissão',
    'acad_despues_titulo' => 'Depois (Certificatum)',
    'acad_despues_emision' => 'Emissão massiva em segundos',
    'acad_despues_emision_highlight' => 'com um só clique',
    'acad_despues_ahorro' => 'Economia de 85%',
    'acad_despues_ahorro_highlight' => 'em custos operacionais',
    'acad_despues_validacion' => 'Validação QR impossível de falsificar',
    'acad_despues_acceso' => 'Acesso 24/7',
    'acad_despues_acceso_highlight' => 'de qualquer dispositivo',
    'acad_despues_digital' => 'Tudo digital e na nuvem,',
    'acad_despues_digital_highlight' => 'sem papéis nem espaço',
    'acad_despues_dashboards' => 'Dashboards e relatórios em tempo real',

    // Integraciones
    'acad_integraciones_titulo' => 'Integrações e Compatibilidade',
    'acad_integraciones_subtitulo' => 'Adapta-se ao seu fluxo de trabalho existente',
    'acad_integ_excel' => 'Excel / CSV',
    'acad_integ_excel_desc' => 'Importação massiva de estudantes e cursos desde arquivos Excel.',
    'acad_integ_api' => 'API REST',
    'acad_integ_api_desc' => 'Integração com sistemas acadêmicos (Moodle, TOTVS, etc.) e plataformas de ensino.',
    'acad_integ_email' => 'E-mail Institucional',
    'acad_integ_email_desc' => 'Notificações desde seu domínio institucional (@suainstituto.edu.br).',
    'acad_integ_subdominios' => 'Subdomínios',
    'acad_integ_subdominios_desc' => 'Portal no seu próprio domínio: certificados.suainstituto.edu.br',

    // FAQ
    'acad_faq_titulo' => 'Perguntas Frequentes',
    'acad_faq_subtitulo' => 'Tudo o que você precisa saber sobre o Certificatum',
    'acad_faq_cargo_titulo' => 'Como carrego a informação dos meus estudantes?',
    'acad_faq_cargo_resp' => 'Você pode carregar estudantes de duas formas: individualmente desde o painel de administração, ou massivamente importando um arquivo Excel/CSV com todos os dados. Fornecemos um modelo para facilitar o processo.',
    'acad_faq_validez_titulo' => 'Os certificados digitais têm validade legal?',
    'acad_faq_validez_resp' => 'Sim, os certificados digitais têm a mesma validade legal que os físicos no Brasil. Além disso, oferecemos opção de impressão premium com papel especial e elementos de segurança para instituições que necessitem.',
    'acad_faq_diseno_titulo' => 'Posso personalizar completamente o design?',
    'acad_faq_diseno_resp' => 'Absolutamente. Você pode configurar seu logo, cores institucionais, assinaturas digitais e toda a identidade visual. Cada certificado é gerado com sua imagem institucional.',
    'acad_faq_acceso_titulo' => 'O que acontece se um estudante perder o acesso ao seu portal?',
    'acad_faq_acceso_resp' => 'O estudante pode recuperar seu acesso usando seu CPF e um processo de verificação por e-mail. Além disso, como administrador da instituição, você pode regenerar o acesso a qualquer momento.',
    'acad_faq_validacion_titulo' => 'Como um empregador valida o certificado?',
    'acad_faq_validacion_resp' => 'O empregador simplesmente escaneia o código QR do certificado com seu celular. Será redirecionado automaticamente para uma página de validação que mostra todos os dados do certificado e a trajetória acadêmica do estudante.',
    'acad_faq_retroactivos_titulo' => 'Posso emitir certificados retroativos?',
    'acad_faq_retroactivos_resp' => 'Sim, você pode carregar e emitir certificados de promoções anteriores sem nenhum problema. O sistema permite indicar datas passadas de emissão.',
    'acad_faq_limite_titulo' => 'Há limite de emissões?',
    'acad_faq_limite_resp' => 'Não há limite de emissões. Você pode gerar tantos certificados quanto necessitar. Os planos se ajustam segundo a quantidade de estudantes ativos em sua instituição.',
    'acad_faq_tecnico_titulo' => 'Preciso de conhecimentos técnicos?',
    'acad_faq_tecnico_resp' => 'Não. A plataforma é muito intuitiva, mas se preferir não mexer em nada, nosso <strong class="text-metallic-green-light">Serviço Concierge</strong> cuida da configuração e carregamento de dados por você. Só nos envia as informações e nós fazemos o resto.',

    // Concierge / Delegación
    'acad_concierge_delegar' => 'Prefere delegar? Nossa equipe cuida da configuração por você.',

    // Banner Promo
    'acad_promo_titulo' => 'PROMO LANÇAMENTO',
    'acad_promo_alta' => 'Alta:',
    'acad_promo_alta_bonificada' => 'Alta Bonificada:',
    'acad_promo_ahorro' => '(Você economiza',
    'acad_descuento_banner' => 'DE DESCONTO em planos - Só por tempo limitado',
    'acad_plan_sin_suscripcion' => 'SEM ASSINATURA',

    // Planes Section
    'acad_planes_titulo' => 'Planos Educacionais',
    'acad_planes_subtitulo' => 'Todos os planos incluem Cartão Digital orientado a certificados + configuração completa + suporte permanente',

    // Plan Singularis (Sin suscripción)
    'acad_plan_singularis_titulo' => 'Singularis',
    'acad_plan_singularis_desc' => 'Ideal para uso ocasional ou testes. Pague apenas pelo que emitir.',
    'acad_plan_singularis_precio_label' => 'por certificado',
    'acad_plan_singularis_feat1' => 'Sem assinatura nem compromisso',
    'acad_plan_singularis_feat2' => 'Pague apenas quando emitir',
    'acad_plan_singularis_feat3' => 'Certificados com QR verificável',
    'acad_plan_singularis_feat4' => 'Validação instantânea',
    'acad_plan_singularis_feat5' => 'Portal público de validação',
    'acad_plan_singularis_cta' => 'Começar sem assinatura',

    // Planes con suscripción
    'acad_plan_pago_mensual' => 'Pagamento mensal',

    // Plan Essentialis
    'acad_plan_essentialis_titulo' => 'Essentialis',
    'acad_plan_essentialis_desc' => 'Ideal para instituições pequenas e formadores autônomos',
    'acad_plan_essentialis_feat1' => '10 Certificados Digitais/mês',
    'acad_plan_essentialis_feat2' => 'Emissão Massiva de Certificados (CSV/Excel)',
    'acad_plan_essentialis_feat3' => 'Cartão Digital Institucional com QR',
    'acad_plan_essentialis_feat4' => 'Site Institucional (instituicao.verumax.com)',
    'acad_plan_essentialis_feat5' => 'Validação QR Infalsificável',
    'acad_plan_essentialis_feat6' => 'Portal do Estudante Básico',
    'acad_plan_essentialis_feat7' => 'Identidade Visual Institucional Personalizada',
    'acad_plan_essentialis_feat8' => 'Notificações Automáticas por Email',
    'acad_plan_essentialis_feat9' => 'Painel de Administração Incluído',
    'acad_plan_essentialis_feat10' => 'Configuração por Equipe Humana',
    'acad_plan_essentialis_cta' => 'Começar com Essentialis',

    // Plan Premium
    'acad_plan_premium_badge' => 'Mais Popular',
    'acad_plan_premium_titulo' => 'Premium',
    'acad_plan_premium_desc' => 'A escolha ideal para centros de formação em crescimento',
    'acad_plan_premium_feat1_strong' => 'TUDO do Essentialis +',
    'acad_plan_premium_feat2' => '100 Certificados Digitais/mês',
    'acad_plan_premium_feat3' => 'Histórico Acadêmico Completo',
    'acad_plan_premium_feat4' => 'Linha do Tempo da Trajetória Estudantil',
    'acad_plan_premium_feat5' => 'Gestão de Turmas e Comissões',
    'acad_plan_premium_cta' => 'Solicitar Plano Premium',

    // Plan Excellens
    'acad_plan_excellens_titulo' => 'Excellens',
    'acad_plan_excellens_desc' => 'Para universidades e grandes instituições educacionais',
    'acad_plan_excellens_feat1_strong' => 'TUDO do Premium +',
    'acad_plan_excellens_feat2' => '1000 Certificados Digitais/mês',
    'acad_plan_excellens_feat3' => 'Sistema Multi-Sede (até 5 sedes)',
    'acad_plan_excellens_feat4' => 'Papéis e Permissões Avançados',
    'acad_plan_excellens_feat5' => 'Integração com Moodle/Canvas/Blackboard',
    'acad_plan_excellens_feat6' => 'API REST Completa para Desenvolvedores',
    'acad_plan_excellens_feat7' => 'Domínio Personalizado (.edu.br / .com)',
    'acad_plan_excellens_cta' => 'Solicitar Plano Excellens',

    // Plan Supremus
    'acad_plan_supremus_titulo' => 'Supremus',
    'acad_plan_supremus_desc' => 'Solução enterprise para redes educacionais e ministérios',
    'acad_plan_supremus_feat1_strong' => 'TUDO do Excellens +',
    'acad_plan_supremus_feat2' => 'Certificados, Constâncias e Diplomas ILIMITADOS',
    'acad_plan_supremus_feat3' => 'Multi-Instituição (Redes Educacionais)',
    'acad_plan_supremus_feat4' => 'Sistema Multi-Sede Ilimitado',
    'acad_plan_supremus_feat5' => 'Blockchain para Registro Permanente',
    'acad_plan_supremus_feat6' => 'Design 100% Personalizado sob Medida',
    'acad_plan_supremus_feat7' => 'Subdomínios Ilimitados por Curso/Faculdade',
    'acad_plan_supremus_feat8' => 'Gerente de Conta Educacional Dedicado',
    'acad_plan_supremus_cta' => 'Contatar para Plano Supremus',

    // CTA Final
    'acad_cta_final_titulo' => 'Transforme a Gestão Acadêmica da sua Instituição',
    'acad_cta_final_desc' => 'Junte-se às instituições que já economizaram milhares de horas administrativas e projetam uma imagem profissional com certificações digitais.',
    'acad_cta_final_demo' => 'Solicitar Demonstração Personalizada',
    'acad_cta_final_contactar' => 'Contatar Vendas',
    'acad_cta_final_implementacion' => 'Implementação',
    'acad_cta_final_menos_tiempo' => 'Menos tempo',
    'acad_cta_final_certificados' => 'Certificados',
    'acad_cta_final_equipo' => 'Nossa equipe de especialistas cuida da configuração inicial para que você possa começar a emitir certificados em minutos.',
    'acad_cta_final_implementacion_desc' => 'Tempo de implementação',

    // Footer
    'acad_footer_tagline' => 'Certificações Digitais Profissionais',
    'acad_footer_derechos' => '© 2025 Verumax. Todos os direitos reservados.',
    'acad_footer_inicio' => 'Início',
    'acad_footer_terminos' => 'Termos de Serviço',
    'acad_footer_privacidad' => 'Privacidade',

    // Meta Tags Académico (Certificatum)
    'acad_meta_title' => 'Certificatum - Certificados Digitais com Validação QR',
    'acad_meta_description' => 'Emita certificados, diplomas e históricos digitais com validação QR. Para instituições educacionais, centros de formação e profissionais autônomos.',
    'acad_meta_keywords' => 'certificados digitais, diplomas online, validação QR, certificados profissionais, formação, cursos',
    'acad_meta_og_title' => 'Certificatum - Certificados Digitais Profissionais',
    'acad_meta_og_description' => 'Emita certificados com validação QR infalsificável. Para instituições, centros de formação e profissionais autônomos.',
    'acad_meta_twitter_title' => 'Certificatum - Certificados Digitais Profissionais',
    'acad_meta_twitter_description' => 'Emita certificados com validação QR infalsificável. Para instituições, centros de formação e profissionais autônomos.',

    // === META TAGS === //

    // Index.php Meta Tags
    'meta_keywords' => 'credenciais digitais, validação QR, marca pessoal verificada, assistentes IA, prestígio digital, certificações infalsificáveis',
    'meta_author' => 'Verumax',
    'meta_og_title' => 'Verumax - Crie, Gerencie e Valide seu Prestígio Digital',
    'meta_og_description' => 'Ecossistema de ferramentas para emitir credenciais infalsificáveis, construir sua marca pessoal verificada e implementar assistentes de IA especializados.',
    'meta_twitter_title' => 'Verumax - Seu Prestígio Digital Verificado',
    'meta_twitter_description' => 'Ferramentas para emitir credenciais infalsificáveis, construir sua marca pessoal e assistentes IA especializados.',

    // Privacidad.php Meta Tags
    'privacidad_meta_description' => 'Política de Privacidade do Verumax. Saiba como coletamos, usamos e protegemos seus dados pessoais.',
    'privacidad_meta_og_title' => 'Política de Privacidade - Verumax',
    'privacidad_meta_og_description' => 'Informação detalhada sobre como o Verumax protege sua privacidade e maneja seus dados pessoais.',
    'privacidad_meta_twitter_title' => 'Política de Privacidade - Verumax',
    'privacidad_meta_twitter_description' => 'Informação detalhada sobre como o Verumax protege sua privacidade e maneja seus dados pessoais.',

    // Terminos.php Meta Tags
    'terminos_meta_description' => 'Termos de Serviço do Verumax. Conheça as condições de uso da nossa plataforma de certificações digitais.',
    'terminos_meta_og_title' => 'Termos de Serviço - Verumax',
    'terminos_meta_og_description' => 'Condições legais para o uso da plataforma Verumax e seus serviços de certificação digital.',
    'terminos_meta_twitter_title' => 'Termos de Serviço - Verumax',
    'terminos_meta_twitter_description' => 'Condições legais para o uso da plataforma Verumax e seus serviços de certificação digital.',

    // ===== PÁGINA PROFESIONAL (CARTÃO DIGITAL) =====
    'prof_meta_title' => 'Cartão Digital Profissional com QR Infalsificável | Verumax',
    'prof_meta_description' => 'Seu cartão de contato digital profissional com QR dinâmico e infalsificável. Site personalizado, painel de administração seguro e atualização instantânea.',
    'prof_meta_keywords' => 'cartão digital, qr infalsificável, cartão de contato digital, site profissional, networking digital',
    'prof_meta_og_title' => 'Cartão Digital: A Evolução do seu Cartão de Visita',
    'prof_meta_og_description' => 'Esqueça os cartões de papel. Sua identidade profissional em um cartão digital com QR verificável, site personalizado e gestão em tempo real.',
    'prof_meta_twitter_title' => 'Cartão Digital Profissional by Verumax',
    'prof_meta_twitter_description' => 'O cartão de visita do futuro. QR infalsificável, site incluído e atualização instantânea.',

    'prof_nav_perfiles' => 'Cartão Digital',
    'prof_nav_como_funciona' => 'Como Funciona',
    'prof_nav_caracteristicas' => 'Características',
    'prof_nav_planes' => 'Planos',
    'prof_nav_empezar' => 'Criar Meu Cartão',

    'prof_hero_badge' => '✓ Tudo o que Você Precisa em um Só Produto',
    'prof_hero_title' => 'Seu Cartão Digital',
    'prof_hero_title_highlight' => 'Configurado por<br>Nossa Equipe Humana',
    'prof_hero_subtitle' => 'O Cartão Digital é a soma de TUDO: cartão em JPG para compartilhar + site + gestor de clientes + email marketing + assistente virtual. Nossa equipe humana configura TUDO por você. Você só envia sua informação e pronto.',
    'prof_hero_url_ejemplo' => 'Sua URL personalizada:',
    'prof_hero_url_ejemplo_subdomain' => 'seunome',
    'prof_hero_url_ejemplo_domain' => '.verumax.com',
    'prof_cta_empezar' => 'Ver Planos e Criar Meu Cartão',
    'prof_cta_secundario' => 'Ver Como Funciona',

    // Sección Hero - Estadísticas
    'prof_stat_qr' => 'Equipe Humana',
    'prof_stat_qr_desc' => 'Nós configuramos tudo',
    'prof_stat_actualizacion' => 'Dashboard Incluído',
    'prof_stat_actualizacion_desc' => 'Para autoadministrar quando quiser',
    'prof_stat_landing' => 'Solução Completa',
    'prof_stat_landing_desc' => 'Cartão + Site + Ferramentas',

    // Sección: ¿Qué es la Tarjeta Digital?
    'prof_que_es_titulo' => 'O que é o Cartão Digital?',
    'prof_que_es_subtitulo' => 'A soma de TUDO o que você precisa para sua presença digital',
    'prof_que_es_desc' => 'O Cartão Digital NÃO é só um cartão. É a SOMA de múltiplos serviços em um: ① Seu cartão físico em formato JPG com QR infalsificável para compartilhar ou imprimir ② Seu site (seunome.verumax.com) ③ Gestor de clientes/contatos ④ Sistema de email marketing ⑤ Assistente virtual especializado 24/7. Tudo isso NÓS configuramos por você. Uma equipe humana real monta sua presença digital completa. Você só nos envia sua informação (foto, serviços, horários) e nós fazemos TODO o trabalho técnico. Você também tem acesso a um dashboard para autoadministrar quando quiser, mas nunca é obrigatório usá-lo.',

    'prof_tarjeta_feature1_titulo' => '① Seu Cartão Físico Digital',
    'prof_tarjeta_feature1_desc' => 'Imagem JPG em alta resolução com seu design profissional e QR infalsificável. Compartilhe por WhatsApp, e-mail, LinkedIn ou imprima em papel. Substitui os cartões de papel tradicionais.',
    'prof_tarjeta_feature2_titulo' => '② Seu Site Profissional Completo',
    'prof_tarjeta_feature2_desc' => 'Domínio personalizado (seunome.verumax.com) com design profissional, portfólio, serviços, horários, formulário de contato. Não é só um landing, é seu site completo configurado por nossa equipe.',
    'prof_tarjeta_feature3_titulo' => '③ Ferramentas de Gestão Incluídas',
    'prof_tarjeta_feature3_desc' => 'Gestor de clientes + Email marketing + Recepcionista Virtual Especializado. Tudo integrado e funcionando. São serviços que habitualmente você contrataria separadamente.',
    'prof_tarjeta_feature4_titulo' => '④ Equipe Humana + Dashboard Opcional',
    'prof_tarjeta_feature4_desc' => 'Nós configuramos TUDO por você. Uma equipe humana real se encarrega de montar sua presença digital completa. Você também tem acesso a um dashboard para fazer mudanças quando quiser, mas sempre pode pedir nossa ajuda.',

    // Sección: Cómo Funciona
    'prof_como_titulo' => 'Como Funciona em 3 Passos Simples',
    'prof_como_subtitulo' => 'Nós fazemos TODO o trabalho técnico por você',
    'prof_como_paso1' => 'Passo 1: Escolha seu Plano e Envie sua Info',
    'prof_como_paso1_desc' => 'Selecione o plano que melhor se adapta a você e nos envia sua informação: nome, foto, serviços que oferece, horários, contato. Nada mais. Você não precisa mexer em nada técnico.',
    'prof_como_paso2' => 'Passo 2: Nossa Equipe Configura TUDO',
    'prof_como_paso2_desc' => 'Uma equipe humana REAL monta seu site completo, desenha seu cartão digital, configura suas ferramentas (gestor de clientes, email marketing, assistente virtual). Você não faz nada. Nós fazemos TODO o trabalho técnico.',
    'prof_como_paso3' => 'Passo 3: Comece a Usar Tudo Já Funcionando',
    'prof_como_paso3_desc' => 'Você recebe seu cartão para compartilhar, seu site já online, e todas as ferramentas configuradas e prontas. Pode usar o dashboard para fazer mudanças você mesmo, ou simplesmente nos escrever e nós fazemos por você. Sempre tem suporte humano real.',

    // Sección: Características Estrella
    'prof_caracteristicas_titulo' => 'Por Que Escolher Nosso Cartão Digital',
    'prof_caracteristicas_subtitulo' => 'Não é só um cartão, é sua solução profissional completa com equipe humana incluída',

    'prof_caract_qr_titulo' => 'Equipe Humana que Faz Tudo por Você',
    'prof_caract_qr_desc' => 'Não deixamos você sozinho com um software. Uma equipe humana REAL configura seu site, desenha seu cartão, carrega sua informação e dá suporte permanente. Você pode usar o dashboard se quiser, ou simplesmente nos escrever e nós fazemos as mudanças. Sempre há pessoas reais por trás.',
    'prof_caract_panel_titulo' => 'A Soma de Múltiplos Serviços em Um',
    'prof_caract_panel_desc' => 'Você não compra só um cartão. Compra: cartão digital + site completo + gestor de clientes + email marketing + assistente virtual. São ferramentas que habitualmente você contrataria separadamente em diferentes plataformas. Aqui estão todas integradas e funcionando.',
    'prof_caract_paletas_titulo' => 'Dashboard Incluído mas Opcional',
    'prof_caract_paletas_desc' => 'Você tem acesso a um painel de administração para fazer mudanças você mesmo quando quiser: atualizar foto, modificar horários, adicionar serviços. Mas NUNCA é obrigatório usá-lo. Sempre pode pedir que façamos nós. O dashboard é uma opção, não uma obrigação.',
    'prof_caract_landing_titulo' => 'Site Profissional Completo',
    'prof_caract_landing_desc' => 'Não é só uma "landing page". É seu site profissional completo (seunome.verumax.com) com portfólio, serviços detalhados, formulário de contato, informação de horários. Tudo otimizado para celulares e configurado por nossa equipe.',
    'prof_caract_formatos_titulo' => 'Sua Presença Digital Necessária Hoje',
    'prof_caract_formatos_desc' => 'Ter presença na internet já não é opcional. É necessário. O Cartão Digital dá a você TUDO o que precisa: cartão para compartilhar + site profissional + ferramentas de gestão. Tudo em um só produto, configurado e pronto para usar.',
    'prof_caract_seguridad_titulo' => 'Suporte Humano Permanente',
    'prof_caract_seguridad_desc' => 'Você nunca fica sozinho. Sempre há pessoas reais do outro lado para ajudá-lo. Quer mudar algo? Escreva-nos. Não sabe como usar uma ferramenta? Explicamos. Precisa adicionar conteúdo? Fazemos por você. Suporte humano real, não chatbots.',

    // Sección: Casos de Uso
    'prof_casos_titulo' => 'Para Quem é o Cartão Digital?',
    'prof_casos_subtitulo' => 'Profissionais de todas as indústrias que valorizam a primeira impressão',

    'prof_caso_abogados' => 'Advogados e Consultores',
    'prof_caso_abogados_desc' => 'Entregue seu cartão com QR aos seus clientes. Eles escaneiam e acessam suas áreas de prática, horários de atendimento e formulário de consulta.',
    'prof_caso_medicos' => 'Médicos e Profissionais da Saúde',
    'prof_caso_medicos_desc' => 'Seu cartão com especialidades, horários de consultório, planos de saúde que aceita e botão direto para agendar consultas.',
    'prof_caso_arquitectos' => 'Arquitetos e Designers',
    'prof_caso_arquitectos_desc' => 'Compartilhe seu cartão e que seus prospectos vejam seu portfólio visual em seu site personalizado.',
    'prof_caso_comercios' => 'Comércios e Empreendedores',
    'prof_caso_comercios_desc' => 'Seu cartão comercial com horários, localização, catálogo de produtos/serviços e botão de WhatsApp para consultas.',
    'prof_caso_coaches' => 'Coaches e Capacitadores',
    'prof_caso_coaches_desc' => 'Mostre seus serviços, depoimentos, e permita que seus clientes agendem sessões diretamente do seu site.',
    'prof_caso_freelancers' => 'Freelancers e Criativos',
    'prof_caso_freelancers_desc' => 'Seu cartão digital com links para seu portfólio, redes sociais e tarifas. Impressão profissional garantida.',
    'prof_caso_productores' => 'Produtores de Alimentos',
    'prof_caso_productores_desc' => 'Compartilhe seu cartão com certificações de qualidade, rastreabilidade de produtos e catálogo. O QR leva seus clientes a toda sua informação verificada.',
    'prof_caso_artesanos' => 'Artesãos e Manualidades',
    'prof_caso_artesanos_desc' => 'Mostre seu trabalho artesanal com galeria de fotos, preços e contato direto. Perfeita para feiras, mercados e clientes particulares.',
    'prof_caso_trainers' => 'Personal Trainers e Nutricionistas',
    'prof_caso_trainers_desc' => 'Seu cartão com especialidades, planos disponíveis, horários e sistema de agendamento. Seus clientes reservam consultas diretamente do seu site.',

    // Sección: Planes y Precios
    'prof_planes_titulo' => 'Escolha o Plano que Melhor se Adapta a Você',
    'prof_planes_subtitulo' => 'Todos os planos incluem configuração por equipe humana + suporte permanente + painel de autoadministração',
    'prof_planes_promo' => '🔥 PROMO LANÇAMENTO',
    'prof_planes_alta_texto' => 'Taxa de adesão bonificada:',
    'prof_planes_descuento' => '50% DE DESCONTO - Somente por tempo limitado',

    'prof_plan_esencial_titulo' => 'Essentialis',
    'prof_plan_esencial_desc' => 'Sua presença digital profissional completa. Nós configuramos tudo por você.',
    'prof_plan_esencial_precio' => '$9 USD',
    'prof_plan_esencial_periodo' => '/ Anual',
    'prof_plan_esencial_feat1' => 'Cartão Digital JPG com QR Infalsificável',
    'prof_plan_esencial_feat2' => 'Site Personalizado (seunome.verumax.com)',
    'prof_plan_esencial_feat3' => 'Portfólio de Projetos (até 20 imagens)',
    'prof_plan_esencial_feat4' => 'Seção de Serviços Detalhada',
    'prof_plan_esencial_feat5' => 'Formulário de Contato Integrado',
    'prof_plan_esencial_feat6' => 'Gestor de Clientes (até 20 contatos)',
    'prof_plan_esencial_feat7' => 'Email Marketing (100 emails/mês)',
    'prof_plan_esencial_feat8' => 'Recepcionista Virtual Especializado (10 consultas/dia)',
    'prof_plan_esencial_feat9' => 'Sistema de Agendamento de Consultas',
    'prof_plan_esencial_feat10' => 'Configuração por Equipe Humana',
    'prof_plan_esencial_feat11' => 'Painel de Autoadministração Incluído',
    'prof_plan_esencial_cta' => 'Começar com Essentialis',

    'prof_plan_plus_badge' => 'Mais Popular',
    'prof_plan_plus_titulo' => 'Premium',
    'prof_plan_plus_desc' => 'Tudo do Essentialis com limites ampliados e ferramentas profissionais avançadas.',
    'prof_plan_plus_precio' => '$19 USD',
    'prof_plan_plus_periodo' => '/ Anual',
    'prof_plan_plus_feat1_strong' => 'Tudo do plano Essentialis, mais:',
    'prof_plan_plus_feat2' => 'Portfólio Ampliado (até 100 imagens)',
    'prof_plan_plus_feat3' => 'Gestor de Clientes (até 100 contatos)',
    'prof_plan_plus_feat4' => 'Email Marketing (1.000 emails/mês)',
    'prof_plan_plus_feat5' => 'Recepcionista Virtual Especializado (50 consultas/dia)',
    'prof_plan_plus_feat6' => 'Vídeo de Apresentação Pessoal',
    'prof_plan_plus_feat7' => 'Estatísticas Avançadas de Escaneamentos QR',
    'prof_plan_plus_feat8' => 'Gerador de CV Inteligente (PDF e Web)',
    'prof_plan_plus_feat9' => 'Sistema de Agendamento de Consultas',
    'prof_plan_plus_feat10' => 'Integração com Credenciais Verificadas',
    'prof_plan_plus_cta' => 'Obter Plano Premium',

    'prof_plan_pro_badge' => 'Profissional',
    'prof_plan_pro_titulo' => 'Excellens',
    'prof_plan_pro_desc' => 'Solução profissional completa com ferramentas de gestão empresarial e presença digital ampliada.',
    'prof_plan_pro_precio' => '$49 USD',
    'prof_plan_pro_periodo' => '/ Anual',
    'prof_plan_pro_feat1_strong' => 'Tudo do plano Premium, mais:',
    'prof_plan_pro_feat2' => 'Portfólio Empresarial (até 500 imagens)',
    'prof_plan_pro_feat3' => 'Gestor de Clientes (até 1.000 contatos)',
    'prof_plan_pro_feat4' => 'Email Marketing (5.000 emails/mês)',
    'prof_plan_pro_feat5' => 'Recepcionista Virtual Especializado (100 consultas/dia)',
    'prof_plan_pro_feat6' => 'Múltiplas Páginas Personalizadas',
    'prof_plan_pro_feat7' => 'Análises Avançadas e Relatórios Detalhados',
    'prof_plan_pro_feat8' => 'Integrações API Personalizadas',
    'prof_plan_pro_feat9' => 'Suporte Prioritário 24/7',
    'prof_plan_pro_cta' => 'Obter Plano Excellens',

    'prof_plan_elite_badge' => 'Empresarial',
    'prof_plan_elite_titulo' => 'Supremus',
    'prof_plan_elite_desc' => 'A solução empresarial definitiva com recursos ampliados, domínio próprio e personalização total.',
    'prof_plan_elite_precio' => '$99 USD',
    'prof_plan_elite_periodo' => '/ Anual',
    'prof_plan_elite_feat1_strong' => 'Tudo do plano Excellens, mais:',
    'prof_plan_elite_feat2' => 'Portfólio Corporativo (até 2000 imagens)',
    'prof_plan_elite_feat3' => 'Gestor de Clientes (até 5.000 contatos)',
    'prof_plan_elite_feat4' => 'Email Marketing (10.000 emails/mês)',
    'prof_plan_elite_feat5' => 'Recepcionista Virtual Especializado (1.000 consultas/dia)',
    'prof_plan_elite_feat6' => 'Domínio Próprio Incluído (seunome.com)',
    'prof_plan_elite_feat7' => 'Design 100% Personalizado sob Medida',
    'prof_plan_elite_feat8' => 'Subdomínios Ilimitados para Sua Equipe',
    'prof_plan_elite_feat9' => 'Sistema de Funções e Permissões Avançado',
    'prof_plan_elite_feat10' => 'Gerente de Conta Dedicado',
    'prof_plan_elite_cta' => 'Obter Plano Supremus',

    // Sección: CTA Final
    'prof_cta_final_titulo' => 'Sua Presença Digital Completa, Configurada por Nós',
    'prof_cta_final_desc' => 'Não deixamos você sozinho com um software. Uma equipe humana real configura TUDO por você: cartão + site + ferramentas. Você só envia sua info e pronto.',
    'prof_cta_final_btn' => 'Ver Planos e Criar Meu Cartão Digital',
    'prof_cta_final_garantia' => '✓ Equipe humana real incluída  •  ✓ Dashboard opcional, não obrigatório  •  ✓ Suporte permanente',

    // Sección: Formas de Pago
    'prof_pagos_titulo' => 'Formas de Pagamento',
    'prof_pagos_subtitulo' => 'Métodos seguros e convenientes para seu país',
    'prof_pagos_argentina' => 'Métodos de Pagamento no Brasil',
    'prof_pagos_internacional' => 'Pagamento Internacional',
    'prof_pago_mercadopago' => 'MercadoPago',
    'prof_pago_mercadopago_desc' => 'Cartão de crédito, débito e PIX',
    'prof_pago_pagofacil' => 'Boleto Bancário',
    'prof_pago_pagofacil_desc' => 'Pagamento em qualquer banco ou lotérica',
    'prof_pago_transferencia' => 'Transferência Bancária',
    'prof_pago_transferencia_desc' => 'Transferência bancária ou PIX',
    'prof_pago_paypal' => 'PayPal',
    'prof_pago_paypal_desc' => 'Cartões e moeda local em todo o mundo',

    // ===== PÁGINA ASSOCIAÇÕES =====

    // Meta Tags
    'mut_meta_title' => 'Verumax para Associações - Gestão Digital Integral',
    'mut_meta_description' => 'Solução completa para associações. Credenciais digitais, gestão de benefícios, portal do associado e comunicação comunitária.',
    'mut_meta_keywords' => 'associações, credenciais digitais, gestão de associados, benefícios associações',

    // Navigation
    'mut_nav_beneficios' => 'Benefícios',
    'mut_nav_pilares' => 'Pilares',
    'mut_nav_planes' => 'Planos',
    'mut_nav_faq' => 'FAQ',
    'mut_nav_mutuales' => 'Associações',

    // Hero Section
    'mut_hero_badge' => '✓ Solução Integral para Associações',
    'mut_hero_title' => 'Gestão Digital',
    'mut_hero_title_highlight' => 'para Associações',
    'mut_hero_subtitle' => 'Um ecossistema completo para modernizar a gestão, potencializar os benefícios e fortalecer o sentido de comunidade da sua associação',
    'mut_cta_solicitar_demo' => 'Solicitar Demo Personalizada',
    'mut_cta_ver_como_funciona' => 'Ver Como Funciona',

    // Hero Stats
    'mut_hero_stat_tiempo' => 'Menos tempo administrativo',
    'mut_hero_stat_portal' => 'Portal do associado 24/7',
    'mut_hero_stat_beneficios' => 'Gestão de benefícios em tempo real',

    // Problemas Section
    'mut_problemas_titulo' => 'Isso parece familiar?',
    'mut_problemas_subtitulo' => 'Os desafios que enfrentam as associações tradicionais',
    'mut_problema_credenciales' => 'Credenciais de Plástico Obsoletas',
    'mut_problema_credenciales_desc' => 'Custos de impressão, extravios constantes e dificuldade para verificar o status do associado.',
    'mut_problema_beneficios' => 'Gestão Manual de Benefícios',
    'mut_problema_beneficios_desc' => 'Cupons de papel, fraudes por uso duplo e estabelecimentos que não podem verificar descontos.',
    'mut_problema_comunicacion' => 'Comunicação Ineficiente',
    'mut_problema_comunicacion_desc' => 'E-mails que não são lidos, murais físicos desatualizados e dificuldade para alcançar todos os associados.',
    'mut_problema_participacion' => 'Baixa Participação em Assembleias',
    'mut_problema_participacion_desc' => 'Controle manual de quórum, listagens em papel e falta de ferramentas para fomentar a participação.',
    'mut_problema_crecimiento' => 'Gestão Administrativa Complexa',
    'mut_problema_crecimiento_desc' => 'Planilhas Excel, falta de rastreabilidade e dificuldade para gerar relatórios.',
    'mut_problema_imagen' => 'Imagem Antiquada',
    'mut_problema_imagen_desc' => 'Dificuldade para atrair novos associados jovens com processos tradicionais e sem presença digital.',
];
?>
