<?php
// Portugues Portugal - pt_PT
$lang = [
    // Meta
    'meta_title' => 'Verumax - Crie, Gira e Valide a sua Presenca Digital',
    'meta_description' => 'Ecossistema de ferramentas para emitir credenciais infalsificaveis, construir a sua presenca digital verificada e implementar assistentes de IA especializados.',

    // Header/Navigation
    'nav_inicio' => 'Inicio',
    'nav_volver_inicio' => 'Voltar ao Inicio',
    'nav_tema_claro' => 'Mudar para modo claro',
    'nav_tema_oscuro' => 'Mudar para modo escuro',
    'nav_soluciones' => 'Solucoes Especializadas por Setor',
    'nav_ecosistema' => 'Um Ecossistema de Solucoes a sua Disposicao',

    // Enlaces de Navegacion Rapida
    'nav_rapido_titulo' => 'O que esta a procurar?',
    'nav_rapido_sectores_titulo' => 'Solucoes por Setor',
    'nav_rapido_sectores_desc' => 'Academico, Profissional, Eventos, Empresarial, etc.',
    'nav_rapido_ecosistema_titulo' => 'Todas as Nossas Solucoes',
    'nav_rapido_ecosistema_desc' => 'Cartoes, Certificados, Vouchers, Landing Pages, IA e mais',
    'nav_soluciones_academico' => 'Academico',
    'nav_soluciones_profesional' => 'Profissional',
    'nav_soluciones_eventos' => 'Eventos',
    'nav_soluciones_empresarial' => 'Empresarial',
    'nav_soluciones_cooperativas' => 'Cooperativas',
    'nav_soluciones_mutuales' => 'Mutuas',
    'nav_productos' => 'Solucoes',
    'nav_productos_tarjeta_digital' => 'Cartao Digital',
    'nav_productos_certificados' => 'Certificados Academicos',
    'nav_productos_credenciales' => 'Credenciais e Documentos',
    'nav_productos_landing_personales' => 'Landing Pages Pessoais',
    'nav_productos_landing_institucionales' => 'Landing Pages Institucionais',
    'nav_productos_portfolios' => 'Portfolios Evoluidos',
    'nav_productos_cv' => 'CV Inteligentes',
    'nav_productos_autenticidad' => 'Certificados de Autenticidade',
    'nav_productos_ia' => 'Agentes de IA',
    'nav_productos_impresion' => 'Impressao Premium',
    'nav_productos_vouchers' => 'Vouchers e Cupoes',
    'nav_productos_portal_comunicacion' => 'Portal de Comunicacao',
    'nav_productos_encuestas' => 'Inqueritos e Votacoes',
    'nav_categorias' => 'Categorias',
    'nav_beneficios' => 'Beneficios',
    'nav_faq' => 'FAQ',
    'nav_validar' => 'Validar',
    'nav_demo' => 'Solicitar Demonstracao',

    // Hero Section
    'hero_badge' => 'Confiado por instituicoes e profissionais globalmente',
    'hero_title_line1' => 'Crie, Gira e Valide',
    'hero_title_line2' => 'a sua Presenca Digital',
    'hero_subtitle' => 'Um ecossistema de ferramentas para emitir <span class="text-gold font-bold">credenciais infalsificaveis</span>, construir a sua <span class="text-gold font-bold">presenca digital verificada</span> e implementar <span class="text-gold font-bold">assistentes de IA</span> especializados.',
    'hero_cta_primary' => 'O que esta a procurar?',
    'hero_cta_secondary' => 'Validar Documento',

    // Hero Mockup Mobile
    'hero_mockup_certificado' => 'Certificado',
    'hero_mockup_curso' => 'Justica Restaurativa',
    'hero_mockup_estudiante' => 'Juan Perez - BI 12345678',
    'hero_mockup_verificado' => 'Verificado',
    'hero_mockup_valido' => 'Valido ate 2026',
    'hero_mockup_ver_detalles' => 'Ver Detalhes',
    'hero_mockup_certificados' => 'Certificados',
    'hero_mockup_en_curso' => 'Em Curso',

    // Equipo Humano Section
    'equipo_titulo' => 'Pensado para Si',
    'equipo_subtitulo' => 'Sem Conhecimentos Tecnicos Requeridos',
    'equipo_card1_titulo' => 'Equipa Humana Real',
    'equipo_card1_desc' => 'Nao o deixamos sozinho com um software. A nossa equipa humana encarrega-se de TUDO: configuracao, design, carregamento de informacao e suporte permanente. Voce apenas envia a sua informacao e nos fazemos o resto.',
    'equipo_card2_titulo' => 'Dashboard Moderno Incluido',
    'equipo_card2_desc' => 'Se tem conhecimentos tecnicos ou quer aprender, conta com um dashboard intuitivo, moderno e seguro para gerir tudo por si mesmo. Mas pode sempre pedir-nos ajuda quando necessitar.',
    'equipo_card3_titulo' => 'Suporte 24/7',
    'equipo_card3_desc' => 'Tem acesso direto a pessoas reais que o ajudam quando necessita. Seja pelo dashboard ou escrevendo-nos diretamente, tera sempre uma resposta rapida e humana.',

    // Categorias Section
    'cat_title' => 'Solucoes por Setor',
    'cat_subtitle' => 'Escolha o seu setor para descobrir a solucao perfeita desenhada para as suas necessidades especificas',

    'cat_academico' => 'Academico',
    'cat_academico_1' => 'Instituicoes Educativas',
    'cat_academico_2' => 'Centros de Formacao',
    'cat_academico_3' => 'Formadores e Formadoras Particulares',
    'cat_academico_cta' => 'Ver Solucao',

    'cat_profesional' => 'Profissional',
    'cat_profesional_1' => 'Saude e Bem-Estar',
    'cat_profesional_2' => 'Engenharia e Arquitetura',
    'cat_profesional_3' => 'Todos os Profissionais',

    'cat_eventos' => 'Eventos',
    'cat_eventos_1' => 'Congressos e Conferencias',
    'cat_eventos_2' => 'Festivais e Concertos',
    'cat_eventos_3' => 'Controlo de Acesso',

    'cat_empresarial' => 'Empresarial',
    'cat_empresarial_1' => 'Garantias e Autenticidade',
    'cat_empresarial_2' => 'Certificados de Qualidade',
    'cat_empresarial_3' => 'Recibos Validados',

    'cat_cooperativas' => 'Cooperativas',
    'cat_cooperativas_1' => 'Credenciais de Socios e Socias',
    'cat_cooperativas_2' => 'Certificados de Participacao',
    'cat_cooperativas_3' => 'Certificados de Atividades',

    'cat_mutuales' => 'Mutuas',
    'cat_mutuales_1' => 'Credenciais de Associados e Associadas',
    'cat_mutuales_2' => 'Comprovativos de Servicos',
    'cat_mutuales_3' => 'Cartilhas de Beneficios',

    'cat_artistas' => 'Artistas',
    'cat_artistas_1' => 'Pintores e Pintoras',
    'cat_artistas_2' => 'Artesaos e Artesas',
    'cat_artistas_3' => 'Fotografos e Fotografas',

    'cat_tarjeta_digital' => 'Cartao Digital',
    'cat_tarjeta_digital_1' => 'QR Infalsificavel',
    'cat_tarjeta_digital_2' => 'Landing Page Incluida',
    'cat_tarjeta_digital_3' => 'Atualizacao Instantanea',
    'cat_tarjeta_digital_cta' => 'Ver Planos',

    // Productos/Ecosistema Section
    'productos_title' => 'Um Ecossistema de Solucoes a sua Disposicao',
    'productos_subtitle' => 'Descubra as nossas solucoes especializadas. Cada uma construida sobre a nossa tecnologia de validacao inalteravel.',

    // Soluciones del Ecosistema
    'ecosol_tarjeta_digital' => 'Cartao Digital',
    'ecosol_tarjeta_digital_desc' => 'QR infalsificavel com landing page personalizada',
    'ecosol_certificados_academicos' => 'Certificados Academicos',
    'ecosol_certificados_academicos_desc' => 'Diplomas e registos academicos digitais verificaveis',
    'ecosol_credenciales_documentos' => 'Credenciais e Documentos',
    'ecosol_credenciales_documentos_desc' => 'Documentacao profissional verificada',
    'ecosol_landing_personales' => 'Landing Pages Pessoais',
    'ecosol_landing_personales_desc' => 'Site pessoal com a sua identidade',
    'ecosol_landing_institucionales' => 'Landing Pages Institucionais',
    'ecosol_landing_institucionales_desc' => 'Presenca web profissional para a sua instituicao',
    'ecosol_portfolios' => 'Portfolios Evoluidos',
    'ecosol_portfolios_desc' => 'Mostre o seu trabalho com validacao profissional',
    'ecosol_cv_inteligentes' => 'CV Inteligentes',
    'ecosol_cv_inteligentes_desc' => 'Curriculo verificavel e atualizavel',
    'ecosol_certificados_autenticidad' => 'Certificados de Autenticidade',
    'ecosol_certificados_autenticidad_desc' => 'Para produtos, obras de arte e mais',
    'ecosol_agentes_ia' => 'Agentes de IA Especializados',
    'ecosol_agentes_ia_desc' => 'Assistentes inteligentes personalizados',
    'ecosol_impresion_premium' => 'Impressao Premium',
    'ecosol_impresion_premium_desc' => 'Documentos fisicos de alta qualidade',
    'ecosol_vouchers' => 'Vouchers e Cupoes Digitais',
    'ecosol_vouchers_desc' => 'Cupoes de uso unico com QR verificavel',
    'ecosol_portal_comunicacion' => 'Portal de Comunicacao',
    'ecosol_portal_comunicacion_desc' => 'Quadro de novidades e anuncios oficiais',
    'ecosol_encuestas' => 'Inqueritos e Votacoes',
    'ecosol_encuestas_desc' => 'Participacao ativa e feedback da sua comunidade',

    'cat_proximamente' => 'Em Breve',
    'cat_footer' => 'Mais categorias em breve.',
    'cat_footer_link' => 'Consulte-nos',
    'cat_footer_text' => 'se o seu setor nao esta listado.',

    // Servicios Principales
    'servicios_title' => 'Os Nossos Servicos Principais',
    'servicios_subtitle' => 'Funcionalidades essenciais que todas as nossas organizacoes desfrutam, independentemente do seu setor',

    'serv_antifraude' => 'Seguranca Anti-Fraude Total',
    'serv_antifraude_desc' => 'Codigos QR unicos e impossiveis de falsificar que garantem a autenticidade de cada documento.',

    'serv_portal' => 'Portal 24/7',
    'serv_portal_desc' => 'Acesso permanente para estudantes, clientes, socios ou colaboradores a partir de qualquer dispositivo.',

    'serv_impresion' => 'Impressao Premium',
    'serv_impresion_desc' => 'Documentos fisicos de alta qualidade com hologramas e laminado, enviados ao domicilio.',

    'serv_branding' => 'Identidade Visual Personalizada',
    'serv_branding_desc' => 'Portal e documentos com o seu logotipo, cores e design institucional unico.',

    'serv_emision' => 'Emissao Massiva',
    'serv_emision_desc' => 'Gere centenas de documentos automaticamente com notificacao instantanea.',

    'serv_validacion' => 'Portal de Validacao',
    'serv_validacion_desc' => 'Qualquer pessoa pode verificar a autenticidade dos seus documentos instantaneamente.',

    // Casos de Exito
    'casos_title' => 'Casos de Sucesso',
    'casos_subtitle' => 'Instituicoes e profissionais que confiam na Verumax',

    'caso_sajur_org' => 'Sociedade Argentina de Justica Restaurativa',
    'caso_sajur_tipo' => 'Organizacao educativa especializada',
    'caso_sajur_texto' => '"Passamos de processar manualmente cada certificado para emitir dezenas em minutos. Os nossos estudantes e as nossas estudantes valorizam poder aceder a sua trajetoria completa 24/7, e os empregadores e as empregadoras confiam na validacao QR. A poupanca em tempo administrativo foi de 90%."',

    'caso_liberte_org' => 'Cooperativa de Trabalho Liberte',
    'caso_liberte_tipo' => 'Formacao profissional e capacitacao',
    'caso_liberte_texto' => '"A implementacao foi instantanea. Em menos de 24 horas ja estavamos a emitir certificados com a nossa marca. O portal personalizado projeta uma imagem profissional que os nossos estudantes e as nossas estudantes partilham com orgulho. A opcao de impressao premium e o toque final perfeito."',

    'caso_nutricion_org' => 'Lic. Maria Goncalves',
    'caso_nutricion_tipo' => 'Nutricionista profissional independente',
    'caso_nutricion_texto' => '"Os meus planos nutricionais agora tem um codigo QR que os meus pacientes podem validar. Isto aumentou significativamente a confianca e reduziu as consultas sobre autenticidade. Alem disso, o envio fisico premium e perfeito para quem quer te-lo impresso."',

    'caso_empresa_org' => 'TechVision S.A.',
    'caso_empresa_tipo' => 'Empresa de tecnologia',
    'caso_empresa_texto' => '"Usamos a Verumax para emitir garantias dos nossos produtos com QR verificavel. Os nossos clientes podem validar a autenticidade instantaneamente e aceder a toda a informacao tecnica. A reducao em reclamacoes por falsificacoes foi de 95%."',

    // FAQ
    'faq_title' => 'Perguntas Frequentes',
    'faq_subtitle' => 'Tudo o que precisa saber sobre a Verumax',

    'faq_1_q' => 'Quanto tempo leva a implementar a Verumax?',
    'faq_1_a' => 'Menos de 24 horas. So precisa de configurar a sua marca (logotipo e cores), carregar os seus dados e comecar a emitir. Incluimos orientacao guiada passo a passo.',

    'faq_2_q' => 'Os documentos digitais tem a mesma validade que os fisicos?',
    'faq_2_a' => 'Sim. Os documentos digitais tem plena validade legal. Alem disso, o nosso sistema QR permite verificar a autenticidade instantaneamente, algo impossivel com documentos fisicos tradicionais.',

    'faq_3_q' => 'O que acontece se precisar de uma versao fisica do documento?',
    'faq_3_a' => 'Oferecemos um servico premium de impressao HD com hologramas de seguranca e laminado, enviado por correio registado para todo o territorio portugues. Pode solicita-lo diretamente a partir do seu portal e receber acompanhamento do envio.',

    'faq_4_q' => 'Como funciona a validacao com QR?',
    'faq_4_a' => 'Cada documento inclui um codigo QR unico que redireciona para um portal de validacao personalizado com a sua marca. Ali mostra-se toda a informacao do documento e a sua trajetoria completa. E impossivel de falsificar ou alterar.',

    'faq_5_q' => 'Posso personalizar o design dos documentos?',
    'faq_5_a' => 'Sim, 100%. Cada instituicao ou profissional tem o seu portal completamente personalizado com o seu logotipo, cores e design de marca. Os documentos refletem a sua identidade visual unica.',

    'faq_6_q' => 'Preciso de conhecimentos tecnicos para usar a plataforma?',
    'faq_6_a' => 'Nao. A plataforma esta desenhada para ser extremamente intuitiva. Se sabe navegar na Internet, pode gerir a Verumax sem problemas. Alem disso, oferecemos suporte tecnico completo.',

    'faq_7_q' => 'O que acontece com os meus dados? Sao seguros?',
    'faq_7_a' => 'Seguranca absoluta. Usamos encriptacao de nivel bancario, copias de seguranca automaticas diarias e cumprimos com as normativas de protecao de dados pessoais. Os seus dados estao mais seguros que num ficheiro fisico.',

    // Validar Documento Section
    'validar_title' => 'Validar um Documento',
    'validar_subtitle' => 'Insira o codigo de validacao que aparece no documento (formato: VALID-XXXXXXXXXXXX)',
    'validar_placeholder' => 'VALID-XXXXXXXXXXXX',
    'validar_btn' => 'Validar Agora',
    'validar_ejemplo' => 'Exemplo: VALID-A1B2C3D4E5F6',

    // Contacto Section
    'contacto_title' => 'Comece a Emitir Documentos Profissionais Hoje',
    'contacto_subtitle' => 'Contacte-nos para uma demonstracao personalizada e descubra como a Verumax pode transformar a sua gestao documental.',
    'contacto_nombre' => 'Nome Completo',
    'contacto_email' => 'Email',
    'contacto_institucion' => 'Instituicao/Organizacao',
    'contacto_mensaje' => 'Conte-nos sobre a sua necessidade...',
    'contacto_btn' => 'Solicitar Demonstracao',
    'contacto_info' => 'Ou escreva-nos diretamente:',

    // Footer
    'footer_descripcion' => 'A plataforma definitiva para documentos digitais e fisicos seguros com validacao QR.',
    'footer_enlaces' => 'Links Rapidos',
    'footer_inicio' => 'Inicio',
    'footer_legal' => 'Legal',
    'footer_caracteristicas' => 'Caracteristicas',
    'footer_contacto' => 'Contacto',
    'footer_seguridad' => 'Tecnologia e Seguranca de Nivel Empresarial',
    'footer_copyright' => 'Todos os direitos reservados.',
    'footer_terminos' => 'Termos de Servico',
    'footer_privacidad' => 'Politica de Privacidade',

    // Badges de Seguridad
    'badge_ssl' => 'SSL',
    'badge_ssl_desc' => 'Encriptacao 256-bit',
    'badge_https' => 'HTTPS',
    'badge_https_desc' => 'Ligacao Segura',
    'badge_privacidad' => 'Privacidade',
    'badge_privacidad_desc' => 'Dados Protegidos',
    'badge_backup' => 'Backup',
    'badge_backup_desc' => 'Automatico Diario',
    'badge_uptime' => 'Uptime 99.9%',
    'badge_uptime_desc' => 'Disponibilidade',
    'badge_soporte' => 'Suporte',
    'badge_soporte_desc' => 'Tecnico 24/7',

    // Veritas IA Chat
    'veritas_chat_btn' => 'Chat com Veritas IA',
    'veritas_titulo' => 'Veritas IA',
    'veritas_subtitulo' => 'O Nosso Agente de Inteligencia Artificial Especializado',
    'veritas_proximamente' => 'Em Breve!',
    'veritas_descripcion' => 'Veritas estara disponivel muito em breve para ajuda-lo com consultas sobre certificados, validacoes e mais.',
    'veritas_entendido' => 'Compreendido',

    // Estadisticas Hero
    'stat_uptime' => 'Disponibilidade',
    'stat_documentos' => 'Documentos emitidos',
    'stat_acceso' => 'Acesso disponivel',
    'stat_ahorro' => 'Poupanca em custos administrativos',

    // Social Proof Contacto
    'social_confianza' => 'Instituicoes e profissionais que ja confiam na Verumax',
    'social_mas' => '+ mais organizacoes e profissionais',

    // Beneficios Contacto
    'benefit_demo' => 'Demo gratis sem compromisso',
    'benefit_demo_desc' => 'Experimente todas as funcoes',
    'benefit_implementacion' => 'Implementacao em 24hs',
    'benefit_implementacion_desc' => 'Comece a emitir amanha',
    'benefit_soporte' => 'Suporte tecnico incluido',
    'benefit_soporte_desc' => 'Assistencia completa',

    // CTA Contacto
    'contacto_cta_btn' => 'Solicitar Demo Gratis',
    'contacto_cta_email' => 'Ou escreva-nos a',

    // Footer - Enlaces rapidos
    'footer_link_beneficios' => 'Beneficios',
    'footer_link_como' => 'Como Funciona',
    'footer_link_validar' => 'Validar Documento',
    'footer_link_demo' => 'Solicitar Demo',

    // Footer - Caracteristicas
    'footer_feat_qr' => 'Validacao QR',
    'footer_feat_portal' => 'Portal 24/7',
    'footer_feat_impresion' => 'Impressao Premium',
    'footer_feat_personalizable' => '100% Personalizavel',

    // Footer - Contacto
    'footer_horario' => 'Seg - Sex: 9:00 - 18:00',

    // Pagina de Privacidad
    'privacidad_title' => 'Politica de Privacidade',
    'privacidad_updated' => 'Ultima atualizacao',

    // Pagina de Termos de Servico
    'terminos_title' => 'Termos de Servico',
    'terminos_updated' => 'Ultima atualizacao',

    // Terminos de Servicio - Contenido
    'terminos_seccion1_titulo' => '1. Aceitacao dos Termos',
    'terminos_seccion1_p1' => 'Ao aceder e utilizar a plataforma Verumax ("o Servico"), aceita estar legalmente vinculado por estes Termos de Servico. Se nao concordar com estes termos, nao utilize o Servico.',
    'terminos_seccion1_p2' => 'A Verumax reserva-se o direito de modificar estes termos a qualquer momento. As alteracoes entrarao em vigor imediatamente apos a sua publicacao no site.',

    'terminos_seccion2_titulo' => '2. Descricao do Servico',
    'terminos_seccion2_p1' => 'A Verumax e uma plataforma que permite a instituicoes educativas, profissionais independentes, organizadores e organizadoras de eventos, empresas, cooperativas e mutuas emitir, gerir e validar documentos digitais com codigos QR de verificacao.',
    'terminos_seccion2_p2' => 'Os servicos incluem, mas nao se limitam a:',
    'terminos_seccion2_li1' => 'Emissao de documentos digitais personalizados',
    'terminos_seccion2_li2' => 'Portal personalizado para cada instituicao/profissional',
    'terminos_seccion2_li3' => 'Sistema de validacao com codigos QR unicos',
    'terminos_seccion2_li4' => 'Armazenamento seguro na nuvem',
    'terminos_seccion2_li5' => 'Opcao de impressao premium de documentos fisicos',
    'terminos_seccion2_li6' => 'Emissao massiva de documentos',

    'terminos_seccion3_titulo' => '3. Registo e Conta de Utilizador',
    'terminos_seccion3_p1' => 'Para utilizar o Servico, deve criar uma conta fornecendo informacao precisa, completa e atualizada. E responsavel por:',
    'terminos_seccion3_li1' => 'Manter a confidencialidade da sua palavra-passe e credenciais de acesso',
    'terminos_seccion3_li2' => 'Todas as atividades que ocorram sob a sua conta',
    'terminos_seccion3_li3' => 'Notificar imediatamente qualquer uso nao autorizado da sua conta',
    'terminos_seccion3_li4' => 'Fornecer dados verazes da sua instituicao ou organizacao',
    'terminos_seccion3_p2' => 'A Verumax reserva-se o direito de suspender ou cancelar contas que violem estes termos ou que fornecam informacao falsa.',

    'terminos_seccion4_titulo' => '4. Uso Permitido',
    'terminos_seccion4_p1' => 'O Servico so pode ser utilizado com fins legitimos e de acordo com estes Termos. Nao e permitido utilizar a Verumax para atividades fraudulentas, ilegais ou que infrinjam direitos de terceiros.',

    'terminos_seccion5_titulo' => '5. Propriedade Intelectual',
    'terminos_seccion5_p1' => 'Todo o conteudo, design, logotipos e tecnologia da Verumax sao propriedade exclusiva da plataforma e estao protegidos por leis de propriedade intelectual.',

    'terminos_seccion6_titulo' => '6. Limitacao de Responsabilidade',
    'terminos_seccion6_p1' => 'A Verumax nao sera responsavel por danos indiretos, incidentais ou consequentes decorrentes do uso ou impossibilidade de uso do Servico.',

    'terminos_seccion7_titulo' => '7. Contacto',
    'terminos_seccion7_p1' => 'Para consultas sobre estes Termos de Servico, contacte-nos em:',

    // Politica de Privacidad - Contenido
    'privacidad_intro_titulo' => 'Introducao',
    'privacidad_intro_p1' => 'Na Verumax, a privacidade e seguranca dos seus dados e a nossa maxima prioridade. Esta Politica de Privacidade descreve como recolhemos, usamos, armazenamos e protegemos a sua informacao pessoal quando utiliza os nossos servicos.',
    'privacidad_intro_p2' => 'Ao utilizar a Verumax, aceita as praticas descritas nesta politica. Se nao concordar, nao utilize os nossos servicos.',

    'privacidad_seccion1_titulo' => '1. Informacao que Recolhemos',
    'privacidad_seccion1_sub1_titulo' => '1.1 Informacao de Conta',
    'privacidad_seccion1_sub1_p1' => 'Quando cria uma conta, recolhemos:',
    'privacidad_seccion1_sub1_li1' => 'Nome completo e dados de contacto (email, telefone)',
    'privacidad_seccion1_sub1_li2' => 'Nome da instituicao, organizacao ou profissional independente',
    'privacidad_seccion1_sub1_li3' => 'Endereco fisico e fiscal',
    'privacidad_seccion1_sub1_li4' => 'Informacao de faturacao e pagamento',
    'privacidad_seccion1_sub1_li5' => 'Credenciais de acesso (utilizador/palavra-passe encriptada)',
    'privacidad_seccion1_sub2_titulo' => '1.2 Dados de Documentos e Beneficiarios',
    'privacidad_seccion1_sub2_p1' => 'Ao emitir documentos, recolhemos dados dos beneficiarios e das beneficiarias (estudantes, clientes, colaboradores e colaboradoras, socios e socias, etc.):',
    'privacidad_seccion1_sub2_li1' => 'Nome completo e numero de identificacao (BI, NIF, etc.)',
    'privacidad_seccion1_sub2_li2' => 'Email e telefone (para notificacoes)',
    'privacidad_seccion1_sub2_li3' => 'Dados academicos, profissionais ou laborais relacionados com o documento emitido',
    'privacidad_seccion1_sub2_li4' => 'Fotografia (opcional, se incluida no documento)',
    'privacidad_seccion1_sub3_titulo' => '1.3 Dados de Uso e Tecnicos',
    'privacidad_seccion1_sub3_li1' => 'Endereco IP, navegador, sistema operativo',
    'privacidad_seccion1_sub3_li2' => 'Paginas visitadas, tempo de sessao, cliques',
    'privacidad_seccion1_sub3_li3' => 'Registos de validacao de documentos (quem validou, quando, de onde)',
    'privacidad_seccion1_sub3_li4' => 'Metricas de uso do portal (transferencias, acessos, etc.)',

    'privacidad_seccion2_titulo' => '2. Como Usamos a Sua Informacao',
    'privacidad_seccion2_p1' => 'Utilizamos os dados recolhidos para:',
    'privacidad_seccion2_li1_strong' => 'Fornecer o Servico:',
    'privacidad_seccion2_li1_texto' => 'Gerar, armazenar e gerir documentos digitais',
    'privacidad_seccion2_li2_strong' => 'Validacao:',
    'privacidad_seccion2_li2_texto' => 'Verificar a autenticidade de documentos mediante codigos QR',
    'privacidad_seccion2_li3_strong' => 'Notificacoes:',
    'privacidad_seccion2_li3_texto' => 'Enviar emails sobre documentos emitidos, atualizacoes do servico',
    'privacidad_seccion2_li4_strong' => 'Faturacao:',
    'privacidad_seccion2_li4_texto' => 'Processar pagamentos e emitir faturas',
    'privacidad_seccion2_li5_strong' => 'Melhoria do Servico:',
    'privacidad_seccion2_li5_texto' => 'Analisar metricas de uso para otimizar funcionalidades',
    'privacidad_seccion2_li6_strong' => 'Suporte Tecnico:',
    'privacidad_seccion2_li6_texto' => 'Resolver consultas e problemas tecnicos',
    'privacidad_seccion2_li7_strong' => 'Cumprimento Legal:',
    'privacidad_seccion2_li7_texto' => 'Cumprir com obrigacoes legais e regulatorias',

    'privacidad_seccion3_titulo' => '3. Partilha de Informacao com Terceiros',
    'privacidad_seccion3_p1_strong' => 'Nao vendemos nem alugamos',
    'privacidad_seccion3_p1_normal' => 'os seus dados pessoais a terceiros. Apenas partilhamos informacao nestes casos limitados:',
    'privacidad_seccion3_sub1_titulo' => '3.1 Prestadores de Servicos',
    'privacidad_seccion3_sub1_p1' => 'Trabalhamos com prestadores fiaveis que nos ajudam a operar o Servico:',
    'privacidad_seccion3_sub1_li1' => 'Alojamento e armazenamento na nuvem (servidores seguros)',
    'privacidad_seccion3_sub1_li2' => 'Processadores de pagamentos (com certificacao PCI-DSS)',
    'privacidad_seccion3_sub1_li3' => 'Servicos de email transacional',
    'privacidad_seccion3_sub1_li4' => 'Servicos de impressao e envio (apenas para documentos fisicos solicitados)',
    'privacidad_seccion3_sub1_p2' => 'Todos os prestadores estao contratualmente obrigados a proteger os seus dados e nao podem usa-los para outros fins.',
    'privacidad_seccion3_sub2_titulo' => '3.2 Requisitos Legais',
    'privacidad_seccion3_sub2_p1' => 'Podemos divulgar informacao se a lei o exigir (ordem judicial, processo legal) ou para proteger os nossos direitos legais.',
    'privacidad_seccion3_sub3_titulo' => '3.3 Validacao Publica',
    'privacidad_seccion3_sub3_p1' => 'Os documentos emitidos sao validaveis publicamente mediante codigo QR. A informacao mostrada na validacao (nome do beneficiario ou da beneficiaria, instituicao emissora, dados do documento) e visivel para quem digitalizar o codigo.',

    'privacidad_seccion4_titulo' => '4. Seguranca dos Dados',
    'privacidad_seccion4_p1' => 'Implementamos medidas de seguranca de nivel empresarial:',
    'privacidad_seccion4_li1_strong' => 'Encriptacao SSL/TLS 256-bit:',
    'privacidad_seccion4_li1_texto' => 'Todas as comunicacoes estao encriptadas',
    'privacidad_seccion4_li2_strong' => 'Palavras-passe protegidas:',
    'privacidad_seccion4_li2_texto' => 'Armazenadas com hash e salt (bcrypt)',
    'privacidad_seccion4_li3_strong' => 'Copias de seguranca automaticas diarias:',
    'privacidad_seccion4_li3_texto' => 'Com encriptacao e armazenamento redundante',
    'privacidad_seccion4_li4_strong' => 'Firewall e monitorizacao 24/7:',
    'privacidad_seccion4_li4_texto' => 'Protecao contra acessos nao autorizados',
    'privacidad_seccion4_li5_strong' => 'Auditorias de seguranca:',
    'privacidad_seccion4_li5_texto' => 'Revisoes periodicas de vulnerabilidades',
    'privacidad_seccion4_li6_strong' => 'Acesso restrito:',
    'privacidad_seccion4_li6_texto' => 'Apenas pessoal autorizado pode aceder a dados sensiveis',
    'privacidad_seccion4_p2' => 'Apesar destas medidas, nenhum sistema e 100% seguro. Recomendamos usar palavras-passe fortes e nao partilhar as suas credenciais.',

    'privacidad_seccion5_titulo' => '5. Retencao de Dados',
    'privacidad_seccion5_p1' => 'Conservamos os seus dados enquanto mantiver uma conta ativa ou conforme exigido por lei:',
    'privacidad_seccion5_li1_strong' => 'Dados de conta:',
    'privacidad_seccion5_li1_texto' => 'Ate que cancele a sua conta + periodo legal minimo (geralmente 10 anos para fins fiscais)',
    'privacidad_seccion5_li2_strong' => 'Documentos emitidos:',
    'privacidad_seccion5_li2_texto' => 'Permanentemente, ja que servem como registo historico e validacao',
    'privacidad_seccion5_li3_strong' => 'Registos de validacao:',
    'privacidad_seccion5_li3_texto' => '5 anos para auditoria e prevencao de fraude',
    'privacidad_seccion5_li4_strong' => 'Dados de faturacao:',
    'privacidad_seccion5_li4_texto' => '10 anos conforme normativas contabilisticas',
    'privacidad_seccion5_p2' => 'Ao cancelar a sua conta, eliminamos dados desnecessarios de forma segura, mas conservamos registos historicos conforme obrigacoes legais.',

    'privacidad_seccion6_titulo' => '6. Os Seus Direitos',
    'privacidad_seccion6_p1' => 'Conforme as leis de protecao de dados pessoais, tem direito a:',
    'privacidad_seccion6_li1_strong' => 'Acesso:',
    'privacidad_seccion6_li1_texto' => 'Solicitar uma copia dos seus dados pessoais que temos armazenados',
    'privacidad_seccion6_li2_strong' => 'Retificacao:',
    'privacidad_seccion6_li2_texto' => 'Corrigir dados inexatos ou incompletos',
    'privacidad_seccion6_li3_strong' => 'Eliminacao:',
    'privacidad_seccion6_li3_texto' => 'Solicitar a eliminacao dos seus dados (sujeito a obrigacoes legais)',
    'privacidad_seccion6_li4_strong' => 'Limitacao:',
    'privacidad_seccion6_li4_texto' => 'Restringir certos usos dos seus dados',
    'privacidad_seccion6_li5_strong' => 'Portabilidade:',
    'privacidad_seccion6_li5_texto' => 'Receber os seus dados num formato estruturado e transferivel',
    'privacidad_seccion6_li6_strong' => 'Oposicao:',
    'privacidad_seccion6_li6_texto' => 'Opor-se ao processamento dos seus dados em certas circunstancias',
    'privacidad_seccion6_li7_strong' => 'Revogacao de consentimento:',
    'privacidad_seccion6_li7_texto' => 'Retirar o consentimento concedido a qualquer momento',
    'privacidad_seccion6_p2_antes_link' => 'Para exercer estes direitos, contacte-nos em',
    'privacidad_seccion6_p2_link_texto' => 'privacidade@validarcert.com',
    'privacidad_seccion6_p2_normal' => 'Responderemos dentro de 15 dias uteis.',

    'privacidad_seccion7_titulo' => '7. Cookies e Tecnologias Semelhantes',
    'privacidad_seccion7_p1' => 'Utilizamos cookies e tecnologias semelhantes para:',
    'privacidad_seccion7_li1_strong' => 'Cookies essenciais:',
    'privacidad_seccion7_li1_texto' => 'Para o funcionamento do portal (sessao, autenticacao)',
    'privacidad_seccion7_li2_strong' => 'Cookies analiticos:',
    'privacidad_seccion7_li2_texto' => 'Para compreender como usa o servico e melhora-lo (anonimas)',
    'privacidad_seccion7_li3_strong' => 'Cookies de preferencias:',
    'privacidad_seccion7_li3_texto' => 'Para recordar as suas configuracoes (idioma, tema, etc.)',
    'privacidad_seccion7_p2' => 'Pode configurar o seu navegador para rejeitar cookies, mas isso pode afetar a funcionalidade do Servico.',

    'privacidad_seccion8_titulo' => '8. Transferencias Internacionais',
    'privacidad_seccion8_p1' => 'Os seus dados sao armazenados principalmente em servidores localizados na Argentina. Em alguns casos, prestadores de servicos podem processar dados noutros paises com niveis adequados de protecao de dados (ex: Estados Unidos sob o Data Privacy Framework, Uniao Europeia sob o RGPD).',

    'privacidad_seccion9_titulo' => '9. Privacidade de Menores',
    'privacidad_seccion9_p1' => 'O nosso Servico nao se destina a menores de 13 anos. Se descobrirmos que recolhemos dados de um menor sem consentimento parental, eliminaremos essa informacao imediatamente.',
    'privacidad_seccion9_p2' => 'Para beneficiarios e beneficiarias menores de idade cujos documentos sao emitidos por instituicoes educativas, o consentimento presume-se concedido pela instituicao que atua no exercicio da responsabilidade parental delegada ou tutela academica.',

    'privacidad_seccion10_titulo' => '10. Alteracoes a esta Politica',
    'privacidad_seccion10_p1' => 'Podemos atualizar esta Politica de Privacidade ocasionalmente. Alteracoes significativas serao notificadas por email ou mediante aviso destacado no portal. A data de "Ultima atualizacao" no topo indica quando foi feita a ultima modificacao.',

    'privacidad_seccion11_titulo' => '11. Contacto',
    'privacidad_seccion11_p1' => 'Para consultas, exercer os seus direitos ou reportar problemas de privacidade:',
    'privacidad_seccion11_email_privacidad' => 'privacidade@validarcert.com',
    'privacidad_seccion11_email_general_label' => 'Email geral:',
    'privacidad_seccion11_email_general' => 'contacto@validarcert.com',

    'privacidad_seccion12_titulo' => '12. Autoridade de Aplicacao',
    'privacidad_seccion12_p1_antes_strong' => 'Em Portugal, a autoridade de aplicacao em materia de protecao de dados pessoais e a',
    'privacidad_seccion12_p1_strong' => 'Comissao Nacional de Protecao de Dados (CNPD)',
    'privacidad_seccion12_p1_normal' => '. Se considerar que os seus direitos foram violados, pode apresentar uma queixa junto deste organismo.',
    'privacidad_seccion12_aaip_label' => 'CNPD:',
    'privacidad_seccion12_aaip_url' => 'www.cnpd.pt',

    // === ACADEMICO PAGE ===

    // Navigation
    'acad_nav_beneficios' => 'Beneficios',
    'acad_nav_funcionalidades' => 'Funcionalidades',
    'acad_nav_casos_exito' => 'Casos de Sucesso',
    'acad_nav_planes' => 'Planos',
    'acad_nav_faq' => 'FAQ',
    'acad_nav_solicitar_demo' => 'Solicitar Demonstracao',
    'acad_nav_academico' => 'Academico',

    // Hero Section
    'acad_hero_badge' => 'Solucao Academica Completa',
    'acad_hero_title' => 'Certificacoes Academicas',
    'acad_hero_title_highlight' => 'Digitais Profissionais',
    'acad_hero_subtitle' => 'Solucao completa para',
    'acad_hero_instituciones' => 'instituicoes educativas',
    'acad_hero_centros_formacion' => 'centros de formacao',
    'acad_hero_academias' => 'academias',
    'acad_hero_formadores' => 'formadores e formadoras particulares',
    'acad_cta_solicitar_demo' => 'Solicitar Demonstracao Personalizada',
    'acad_cta_ver_como_funciona' => 'Ver Como Funciona',

    // Hero Stats
    'acad_hero_stat_tiempo' => 'Menos tempo administrativo',
    'acad_hero_stat_portal' => 'Portal do estudante',
    'acad_hero_stat_falsificaciones' => 'Falsificacoes possiveis',

    // Hero - Propuesta de Valor y Beneficios
    'acad_hero_propuesta_valor' => 'O sistema faz tudo. Voce apenas carrega os dados uma vez.',
    'acad_hero_benefit_1' => 'Geracao automatica',
    'acad_hero_benefit_2' => 'Notificacao por email',
    'acad_hero_benefit_3' => 'QR infalsificavel',
    'acad_hero_benefit_4' => 'Transferencia 24/7',

    // Seccion ROI - Retorno de Inversion
    'acad_roi_titulo' => 'Retorno de Investimento Comprovado',
    'acad_roi_subtitulo' => 'Resultados reais de instituicoes que ja usam o Certificatum',
    'acad_roi_ahorro_impresion' => 'Poupanca mensal em impressao',
    'acad_roi_ahorro_tiempo' => 'Poupanca em tempo administrativo',
    'acad_roi_reduccion_consultas' => 'Reducao de consultas telefonicas',
    'acad_roi_payback' => 'Tempo de Payback',
    'acad_roi_stat_impresion' => '$$$',
    'acad_roi_stat_tiempo' => '40hs',
    'acad_roi_stat_consultas' => '80%',
    'acad_roi_stat_payback' => '2 meses',

    // Tabla Comparativa
    'acad_vs_titulo' => 'Certificatum vs Alternativas',
    'acad_vs_subtitulo' => 'Compare as opcoes do mercado',
    'acad_vs_aspecto' => 'Aspeto',
    'acad_vs_papel' => 'Papel Tradicional',
    'acad_vs_plataformas' => 'Plataformas Globais',
    'acad_vs_certificatum' => 'Certificatum',
    'acad_vs_costo_emision' => 'Custo de emissao',
    'acad_vs_costo_alto' => 'Alto (impressao, assinaturas)',
    'acad_vs_costo_porcentaje' => '% de vendas',
    'acad_vs_costo_cero' => 'Zero marginal',
    'acad_vs_validacion' => 'Validacao',
    'acad_vs_validacion_tel' => 'Chamada telefonica',
    'acad_vs_validacion_generica' => 'Generica',
    'acad_vs_validacion_qr' => 'QR Instantaneo 24/7',
    'acad_vs_branding' => 'Identidade Corporativa',
    'acad_vs_branding_suyo' => '100% sua',
    'acad_vs_branding_limitado' => 'Limitada',
    'acad_vs_branding_total' => '100% personalizada',
    'acad_vs_falsificacion' => 'Falsificacao',
    'acad_vs_falsificacion_facil' => 'Facil',
    'acad_vs_falsificacion_posible' => 'Possivel',
    'acad_vs_falsificacion_imposible' => 'Impossivel',
    'acad_vs_datos' => 'Dados',
    'acad_vs_datos_fisico' => 'Arquivo fisico',
    'acad_vs_datos_ellos' => 'Sao deles',
    'acad_vs_datos_suyos' => 'Sao 100% seus',

    // Panel de Administracion
    'acad_panel_titulo' => 'Painel de Administracao Completo',
    'acad_panel_subtitulo' => 'Tudo o que precisa para gerir a sua instituicao',
    'acad_panel_carga_masiva' => 'Carregamento massivo a partir de Excel/CSV',
    'acad_panel_crud' => 'CRUD completo de estudantes e cursos',
    'acad_panel_dashboard' => 'Dashboard com analytics em tempo real',
    'acad_panel_multiusuario' => 'Gestao multi-utilizador com funcoes',

    // Problemas Section
    'acad_problemas_titulo' => 'Soa familiar?',
    'acad_problemas_subtitulo' => 'Estes sao os problemas que o Certificatum elimina',
    'acad_problema_trabajo_manual' => 'Horas de Trabalho Manual',
    'acad_problema_trabajo_manual_desc' => 'Desenhar e emitir cada certificado individualmente consome tempo valioso que poderia dedicar ao ensino.',
    'acad_problema_perdidos' => 'Certificados Perdidos',
    'acad_problema_perdidos_desc' => 'Estudantes que perdem ou danificam documentos e solicitam reemissoes constantemente.',
    'acad_problema_falsificaciones' => 'Falsificacoes',
    'acad_problema_falsificaciones_desc' => 'Titulos e certificados falsos a circular sem forma eficaz de verificar a sua autenticidade.',
    'acad_problema_trazabilidad' => 'Sem Rastreabilidade',
    'acad_problema_trazabilidad_desc' => 'Falta de historico academico completo e verificavel de cada estudante.',
    'acad_problema_costos' => 'Custos de Impressao',
    'acad_problema_costos_desc' => 'Gastos elevados em papel especial, impressao, toner e armazenamento fisico.',
    'acad_problema_archivos' => 'Arquivos Fisicos Caoticos',
    'acad_problema_archivos_desc' => 'Montanhas de papeis a ocupar espaco valioso e a dificultar a busca de informacao.',

    // Como Funciona Section
    'acad_como_funciona_titulo' => 'Tao simples como 1, 2, 3',
    'acad_como_funciona_subtitulo' => 'Implementacao imediata, sem complicacoes tecnicas',
    'acad_como_funciona_paso1_titulo' => 'Configure a sua Instituicao',
    'acad_como_funciona_paso1_desc' => 'Personalize com o seu logotipo, cores institucionais e defina os tipos de certificados que emitira.',
    'acad_como_funciona_paso2_titulo' => 'Carregue Estudantes e Cursos',
    'acad_como_funciona_paso2_desc' => 'Importe dados massivamente a partir de Excel ou CSV. Tambem pode carregar um por um.',
    'acad_como_funciona_paso2_alt' => 'Ou simplesmente envie-nos as suas listagens e a nossa equipa importa-as por si.',
    'acad_como_funciona_paso3_titulo' => 'Emita e Valide',
    'acad_como_funciona_paso3_desc' => 'Geracao automatica com QR unico. Notificacao por email e acesso imediato para estudantes.',
    'acad_como_funciona_paso3_alt' => 'Tambem pode solicitar a emissao a nossa equipa e apenas encarregar-se de partilhar.',

    // Tipos de Documentos
    'acad_documentos_titulo' => 'Tipos de Documentos Academicos',
    'acad_documentos_subtitulo' => 'Todos os documentos que a sua instituicao necessita emitir',
    'acad_documentos_principales' => 'Documentos Principais',
    'acad_doc_certificado_aprobacion' => 'Certificados de Aprovacao',
    'acad_doc_certificado_aprobacion_desc' => 'Certificado oficial que comprova a aprovacao num curso, disciplina ou programa completo.',
    'acad_doc_diplomas' => 'Diplomas de Conclusao',
    'acad_doc_diplomas_desc' => 'Titulo ou diploma formal que certifica a conclusao bem-sucedida de um programa academico completo.',
    'acad_doc_analiticos' => 'Registos Academicos',
    'acad_doc_analiticos_desc' => 'Historico completo com todas as disciplinas cursadas, classificacoes, assiduidade e competencias adquiridas.',
    'acad_doc_constancia_regular' => 'Certificados de Aluno Regular',
    'acad_doc_constancia_regular_desc' => 'Documento que comprova que o estudante ou a estudante esta atualmente a frequentar a instituicao.',
    'acad_doc_constancia_inscripcion' => 'Certificados de Inscricao',
    'acad_doc_constancia_inscripcion_desc' => 'Comprovativo de inscricao num curso, disciplina ou programa academico especifico.',
    'acad_doc_constancia_finalizacion' => 'Certificados de Conclusao de Curso',
    'acad_doc_constancia_finalizacion_desc' => 'Certificado que comprova ter concluido o curso, antes da avaliacao final.',

    // Documentos Complementarios
    'acad_documentos_complementarios' => 'Documentos Complementares',
    'acad_doc_asistencia' => 'Certificados de Participacao',
    'acad_doc_asistencia_desc' => 'Para workshops, seminarios, webinars ou eventos educativos pontuais.',
    'acad_doc_reconocimientos' => 'Reconhecimentos e Mencoes',
    'acad_doc_reconocimientos_desc' => 'Premios especiais, mencoes honrosas ou reconhecimentos por desempenho proeminente.',
    'acad_doc_competencias' => 'Certificados de Competencias',
    'acad_doc_competencias_desc' => 'Comprovam habilidades e competencias especificas adquiridas durante a formacao.',
    'acad_doc_practica' => 'Certificados de Pratica Profissional',
    'acad_doc_practica_desc' => 'Documentam estagios, praticas profissionais ou experiencia laboral supervisionada.',
    'acad_doc_congresos' => 'Certificados de Participacao em Congressos',
    'acad_doc_congresos_desc' => 'Para assistencia ou apresentacoes em congressos, jornadas academicas e conferencias.',

    // Portal del Estudiante
    'acad_portal_badge' => 'Funcionalidade Destacada',
    'acad_portal_titulo' => 'Portal do Estudante 24/7',
    'acad_portal_subtitulo' => 'Cada estudante tem acesso ao seu próprio portal, personalizado com a identidade visual e o logótipo da sua instituição. A partir daí, podem ver o seu progresso e transferir todos os seus documentos.',
    'acad_portal_acceso_titulo' => 'Acesso 24/7 a sua trajetoria completa',
    'acad_portal_acceso_desc' => 'Estudantes acedem a partir de qualquer dispositivo, em qualquer momento.',
    'acad_portal_descarga_titulo' => 'Transferencia de todos os seus documentos',
    'acad_portal_descarga_desc' => 'Diplomas, certificados, registos academicos - tudo num so lugar.',
    'acad_portal_timeline_titulo' => 'Vista cronologica academica',
    'acad_portal_timeline_desc' => 'Visualizacao cronologica de toda a sua trajetoria educacional.',
    'acad_portal_qr_titulo' => 'QR individual por documento',
    'acad_portal_qr_desc' => 'Cada documento tem o seu codigo unico de validacao.',
    'acad_portal_linkedin_titulo' => 'Partilhar no LinkedIn com um clique',
    'acad_portal_linkedin_desc' => 'Integracao direta para publicar conquistas academicas.',

    // Portal Demo Data
    'acad_portal_demo_nombre' => 'Juan Perez',
    'acad_portal_demo_dni' => 'BI: 12.345.678',
    'acad_portal_demo_progreso' => 'de 4 cursos concluidos',
    'acad_portal_demo_diploma' => 'Diploma - Justica Restaurativa',
    'acad_portal_demo_diploma_fecha' => 'Concluido: 15/03/2024',
    'acad_portal_demo_certificado' => 'Certificado - Mediacao',
    'acad_portal_demo_certificado_fecha' => 'Concluido: 20/01/2024',
    'acad_portal_demo_curso_progreso' => 'Curso em Progresso',
    'acad_portal_demo_curso_nombre' => 'Resolucao de Conflitos',

    // Casos de Uso
    'acad_casos_uso_titulo' => 'Para Quem e o Certificatum?',
    'acad_casos_uso_subtitulo' => 'Instituicoes e profissionais que confiam na nossa plataforma',
    'acad_caso_universidades' => 'Universidades e Ensino Superior',
    'acad_caso_universidades_desc' => 'Gestao em massa de titulos, diplomas e registos academicos para centenas de graduados e graduadas.',
    'acad_caso_centros' => 'Centros de Formacao',
    'acad_caso_centros_desc' => 'Instituicoes como SAJuR e Liberte que emitem certificacoes profissionais.',
    'acad_caso_idiomas' => 'Academias de Linguas',
    'acad_caso_idiomas_desc' => 'Certificados de niveis concluidos com validacao internacional.',
    'acad_caso_tecnicos' => 'Institutos Tecnicos',
    'acad_caso_tecnicos_desc' => 'Certificacoes tecnicas e profissionais com rastreabilidade completa.',
    'acad_caso_laboral' => 'Formacao Profissional',
    'acad_caso_laboral_desc' => 'Centros de formacao continua e desenvolvimento profissional.',
    'acad_caso_continua' => 'Educacao Continua',
    'acad_caso_continua_desc' => 'Programas de atualizacao profissional e pos-graduacao.',
    'acad_caso_organizadores' => 'Organizadores e Organizadoras de Cursos',
    'acad_caso_organizadores_desc' => 'Diplomas e certificados para cursos, workshops e programas especiais.',
    'acad_caso_particulares' => 'Formadores e Formadoras Particulares',
    'acad_caso_particulares_desc' => 'Docentes independentes que emitem certificacoes profissionais.',

    // Funcionalidades
    'acad_func_titulo' => 'Funcionalidades Pensadas para Instituicoes',
    'acad_func_subtitulo' => 'Tudo o que precisa para gerir certificacoes academicas',
    'acad_func_cohortes' => 'Gestao de Turmas',
    'acad_func_cohortes_desc' => 'Organize estudantes por turma, ano ou grupo. Emita documentos em massa por turma completa.',
    'acad_func_emision_masiva' => 'Emissao Massiva',
    'acad_func_emision_masiva_desc' => 'Gere certificados para 100+ estudantes em minutos. Um clique para toda uma turma.',
    'acad_func_notificaciones' => 'Notificacoes Automaticas por Email',
    'acad_func_notificaciones_desc' => 'Cada estudante recebe notificacao automatica quando e emitido um documento.',
    'acad_func_branding' => 'Portal com Identidade Visual Institucional',
    'acad_func_branding_desc' => 'O seu logotipo, cores e dominio. Cada instituicao projeta a sua propria identidade.',
    'acad_func_trayectoria' => 'Trajetoria Academica Completa',
    'acad_func_trayectoria_desc' => 'Historico verificavel com todos os cursos, classificacoes e conquistas do estudante ou da estudante.',
    'acad_func_validacion' => 'Validacao Publica Instantanea',
    'acad_func_validacion_desc' => 'Empregadores e empregadoras digitalizam o QR e verificam autenticidade instantaneamente.',

    // Beneficios
    'acad_beneficios_titulo' => 'Resultados Mensuráveis',
    'acad_beneficios_subtitulo' => 'Impacto real na sua instituicao desde o primeiro dia',
    'acad_beneficio_tiempo_titulo' => 'Menos Tempo Administrativo',
    'acad_beneficio_tiempo_desc' => 'O que demorava horas agora demora minutos',
    'acad_beneficio_ahorro_titulo' => 'Poupanca em Custos',
    'acad_beneficio_ahorro_desc' => 'Reducao drastica em impressao e papelaria',
    'acad_beneficio_falsificaciones_titulo' => 'Falsificacoes Possiveis',
    'acad_beneficio_falsificaciones_desc' => 'Impossivel clonar codigos QR unicos',
    'acad_beneficio_acceso_titulo' => 'Acesso para Estudantes',
    'acad_beneficio_acceso_desc' => 'Portal disponivel em qualquer momento',
    'acad_beneficio_trazabilidad_titulo' => '100% Rastreabilidade e Auditoria',
    'acad_beneficio_trazabilidad_desc' => 'Cada acao fica registada. Sabe exatamente quem emitiu que documento, quando e para quem. Ideal para auditorias e cumprimento normativo.',

    // Casos de Exito
    'acad_casos_exito_titulo' => 'Casos de Sucesso',
    'acad_casos_exito_subtitulo' => 'Instituicoes que transformaram a sua gestao academica',
    'acad_caso_sajur_nombre' => 'Sociedade Argentina de Justica Restaurativa',
    'acad_caso_sajur_tipo' => 'Centro de formacao especializada',
    'acad_caso_sajur_testimonio' => '"Passamos de processar manualmente cada certificado para emitir dezenas em minutos. Os nossos estudantes e as nossas estudantes valorizam poder aceder a sua trajetoria completa 24/7, e os empregadores e as empregadoras confiam na validacao QR. A poupanca em tempo administrativo foi de 90%."',
    'acad_caso_liberte_nombre' => 'Cooperativa de Trabalho Liberte',
    'acad_caso_liberte_tipo' => 'Formacao profissional e capacitacao',
    'acad_caso_liberte_testimonio' => '"A implementacao foi instantanea. Em menos de 24 horas ja estavamos a emitir certificados com a nossa marca. O portal personalizado projeta uma imagem profissional que os nossos estudantes e as nossas estudantes partilham com orgulho. A opcao de impressao premium e o toque final perfeito."',

    // Antes vs Despues
    'acad_antes_despues_titulo' => 'Antes vs Depois do Certificatum',
    'acad_antes_despues_subtitulo' => 'A transformacao digital da sua gestao academica',
    'acad_antes_titulo' => 'Antes (Tradicional)',
    'acad_antes_trabajo_manual' => 'Horas de trabalho manual por cada certificado',
    'acad_antes_costos' => 'Custos elevados de impressao e papelaria',
    'acad_antes_falsificacion' => 'Risco de falsificacao sem forma de verificar',
    'acad_antes_presencial' => 'Estudantes devem comparecer presencialmente para levantar',
    'acad_antes_almacenamiento' => 'Armazenamento fisico caotico e espaco ocupado',
    'acad_antes_estadisticas' => 'Sem estatisticas nem metricas de emissao',
    'acad_despues_titulo' => 'Depois (Certificatum)',
    'acad_despues_emision' => 'Emissao massiva em segundos',
    'acad_despues_emision_highlight' => 'com um clique',
    'acad_despues_ahorro' => 'Poupanca de 85%',
    'acad_despues_ahorro_highlight' => 'em custos operacionais',
    'acad_despues_validacion' => 'Validacao QR impossivel de falsificar',
    'acad_despues_acceso' => 'Acesso 24/7',
    'acad_despues_acceso_highlight' => 'a partir de qualquer dispositivo',
    'acad_despues_digital' => 'Tudo digital e na nuvem,',
    'acad_despues_digital_highlight' => 'sem papeis nem espaco',
    'acad_despues_dashboards' => 'Dashboards e relatorios em tempo real',

    // Integraciones
    'acad_integraciones_titulo' => 'Integracoes e Compatibilidade',
    'acad_integraciones_subtitulo' => 'Adapta-se ao seu fluxo de trabalho existente',
    'acad_integ_excel' => 'Excel / CSV',
    'acad_integ_excel_desc' => 'Importacao massiva de estudantes e cursos a partir de ficheiros Excel.',
    'acad_integ_api' => 'API REST',
    'acad_integ_api_desc' => 'Integracao com sistemas SIU, Moodle e plataformas academicas.',
    'acad_integ_email' => 'Email Institucional',
    'acad_integ_email_desc' => 'Notificacoes a partir do seu dominio institucional (@suainstitucao.edu).',
    'acad_integ_subdominios' => 'Subdominios',
    'acad_integ_subdominios_desc' => 'Portal no seu proprio dominio: certificados.suainstitucao.edu',

    // FAQ
    'acad_faq_titulo' => 'Perguntas Frequentes',
    'acad_faq_subtitulo' => 'Tudo o que precisa saber sobre o Certificatum',
    'acad_faq_cargo_titulo' => 'Como carrego a informacao dos meus estudantes?',
    'acad_faq_cargo_resp' => 'Pode carregar estudantes de tres formas: individualmente a partir do painel de administracao, massivamente importando um ficheiro Excel/CSV, ou copiando e colando uma lista diretamente. Fornecemos modelos para facilitar o processo.',
    'acad_faq_validez_titulo' => 'Os certificados digitais tem validade legal?',
    'acad_faq_validez_resp' => 'Sim, os certificados digitais tem a mesma validade legal que os fisicos. Alem disso, oferecemos opcao de impressao premium com papel especial e elementos de seguranca para instituicoes que o requeiram.',
    'acad_faq_diseno_titulo' => 'Posso personalizar completamente o design?',
    'acad_faq_diseno_resp' => 'Absolutamente. Pode configurar o seu logotipo, cores institucionais, assinaturas digitais e toda a identidade visual. Cada certificado e gerado com a sua imagem institucional.',
    'acad_faq_acceso_titulo' => 'O que acontece se um estudante ou uma estudante perder o acesso ao seu portal?',
    'acad_faq_acceso_resp' => 'O estudante ou a estudante pode recuperar o seu acesso usando o seu BI e um processo de verificacao por email. Alem disso, como administrador ou administradora da instituicao, pode regenerar o acesso em qualquer momento.',
    'acad_faq_validacion_titulo' => 'Como valida um empregador ou uma empregadora o certificado?',
    'acad_faq_validacion_resp' => 'O empregador ou a empregadora simplesmente digitaliza o codigo QR do certificado com o seu telemovel. Sera redirecionado automaticamente para uma pagina de validacao que mostra todos os dados do certificado e a trajetoria academica do estudante ou da estudante.',
    'acad_faq_retroactivos_titulo' => 'Posso emitir certificados retroativos?',
    'acad_faq_retroactivos_resp' => 'Sim, pode carregar e emitir certificados de turmas anteriores sem qualquer problema. O sistema permite indicar datas passadas de emissao.',
    'acad_faq_limite_titulo' => 'Ha limite de emissoes?',
    'acad_faq_limite_resp' => 'Nao ha limite de emissoes. Pode gerar tantos certificados quanto necessite. Os planos ajustam-se conforme a quantidade de estudantes ativos na sua instituicao.',
    'acad_faq_tecnico_titulo' => 'Preciso de conhecimentos tecnicos?',
    'acad_faq_tecnico_resp' => 'Nao. A plataforma e muito intuitiva, mas se preferir nao mexer em nada, o nosso <strong class="text-metallic-green-light">Servico Concierge</strong> encarrega-se da configuracao e carregamento de dados por si. Apenas nos envia a informacao e nos fazemos o resto.',

    // Concierge / Delegacao
    'acad_concierge_delegar' => 'Prefere delegar? A nossa equipa encarrega-se da configuracao por si.',

    // Banner Promo
    'acad_promo_titulo' => 'PROMOCAO DE LANCAMENTO',
    'acad_promo_alta' => 'Ativacao:',
    'acad_promo_alta_bonificada' => 'Ativacao Bonificada:',
    'acad_promo_ahorro' => '(Poupa',
    'acad_descuento_banner' => 'DE DESCONTO em planos - Apenas por tempo limitado',
    'acad_plan_sin_suscripcion' => 'SEM SUBSCRICAO',

    // CTA Final
    'acad_cta_final_titulo' => 'Transforme a Gestao Academica da sua Instituicao',
    'acad_cta_final_desc' => 'Junte-se as instituicoes que ja pouparam milhares de horas administrativas e projetam uma imagem profissional com certificacoes digitais.',
    'acad_cta_final_equipo' => 'A nossa equipa de especialistas encarrega-se da configuracao inicial para que possa comecar a emitir certificados em minutos.',
    'acad_cta_final_demo' => 'Solicitar Demonstracao Personalizada',
    'acad_cta_final_contactar' => 'Contactar Vendas',
    'acad_cta_final_implementacion' => '48hs',
    'acad_cta_final_implementacion_desc' => 'Tempo de implementacao',
    'acad_cta_final_menos_tiempo' => 'Menos tempo administrativo',
    'acad_cta_final_certificados' => 'Certificados ilimitados',

    // Footer
    'acad_footer_tagline' => 'Certificacoes Digitais Profissionais',
    'acad_footer_derechos' => '2025 Verumax. Todos os direitos reservados.',
    'acad_footer_inicio' => 'Inicio',
    'acad_footer_terminos' => 'Termos',
    'acad_footer_privacidad' => 'Privacidade',

    // Meta Tags Academico
    'acad_meta_title' => 'Certificatum - Certificados Digitais com Validacao QR',
    'acad_meta_description' => 'Emita certificados, diplomas e registos academicos digitais com validacao QR. Para instituicoes educativas, centros de formacao e formadores e formadoras independentes.',
    'acad_meta_keywords' => 'certificados digitais, diplomas online, validacao QR, certificados profissionais, formacao, cursos',
    'acad_meta_og_title' => 'Certificatum - Certificados Digitais Profissionais',
    'acad_meta_og_description' => 'Emita certificados com validacao QR infalsificavel. Para instituicoes, centros de formacao e formadores e formadoras independentes.',
    'acad_meta_twitter_title' => 'Certificatum - Certificados Digitais Profissionais',
    'acad_meta_twitter_description' => 'Emita certificados com validacao QR infalsificavel. Para instituicoes, centros de formacao e formadores e formadoras independentes.',

    // === META TAGS === //

    // Index.php Meta Tags
    'meta_keywords' => 'credenciais digitais, validacao QR, presenca digital verificada, assistentes IA, presenca digital, certificacoes infalsificaveis',
    'meta_author' => 'Verumax',
    'meta_og_title' => 'Verumax - Crie, Gira e Valide a sua Presenca Digital',
    'meta_og_description' => 'Ecossistema de ferramentas para emitir credenciais infalsificaveis, construir a sua presenca digital verificada e implementar assistentes de IA especializados.',
    'meta_twitter_title' => 'Verumax - A sua Presenca Digital Verificada',
    'meta_twitter_description' => 'Ferramentas para emitir credenciais infalsificaveis, construir a sua presenca digital e assistentes IA especializados.',

    // Privacidad.php Meta Tags
    'privacidad_meta_description' => 'Politica de Privacidade da Verumax. Conheca como recolhemos, usamos e protegemos os seus dados pessoais.',
    'privacidad_meta_og_title' => 'Politica de Privacidade - Verumax',
    'privacidad_meta_og_description' => 'Informacao detalhada sobre como a Verumax protege a sua privacidade e gere os seus dados pessoais.',
    'privacidad_meta_twitter_title' => 'Politica de Privacidade - Verumax',
    'privacidad_meta_twitter_description' => 'Informacao detalhada sobre como a Verumax protege a sua privacidade e gere os seus dados pessoais.',

    // Terminos.php Meta Tags
    'terminos_meta_description' => 'Termos de Servico da Verumax. Conheca as condicoes de uso da nossa plataforma de certificacoes digitais.',
    'terminos_meta_og_title' => 'Termos de Servico - Verumax',
    'terminos_meta_og_description' => 'Condicoes legais para o uso da plataforma Verumax e dos seus servicos de certificacao digital.',
    'terminos_meta_twitter_title' => 'Termos de Servico - Verumax',
    'terminos_meta_twitter_description' => 'Condicoes legais para o uso da plataforma Verumax e dos seus servicos de certificacao digital.',

    // ===== PAGINA PERFILES PRO (VERSAO CARTAO DIGITAL PROTAGONISTA) =====
    'prof_meta_title' => 'Cartao Digital Profissional com QR Infalsificavel | Verumax',
    'prof_meta_description' => 'O seu cartao de contacto digital profissional com QR dinamico e infalsificavel. Landing page personalizada, painel de administracao seguro e atualizacao instantanea.',
    'prof_meta_keywords' => 'cartao digital, qr infalsificavel, cartao de contacto digital, landing page profissional, networking digital',
    'prof_meta_og_title' => 'Cartao Digital: A Evolucao do seu Cartao de Visita',
    'prof_meta_og_description' => 'Esqueca os cartoes de papel. A sua identidade profissional num cartao digital com QR verificavel, landing page personalizada e gestao em tempo real.',
    'prof_meta_twitter_title' => 'Cartao Digital Profissional by Verumax',
    'prof_meta_twitter_description' => 'O cartao de visita do futuro. QR infalsificavel, landing page incluida e atualizacao instantanea.',

    'prof_nav_perfiles' => 'Cartao Digital',
    'prof_nav_como_funciona' => 'Como Funciona',
    'prof_nav_caracteristicas' => 'Caracteristicas',
    'prof_nav_planes' => 'Planos',
    'prof_nav_empezar' => 'Criar o Meu Cartao',

    'prof_hero_badge' => 'Tudo o que Precisa num So Produto',
    'prof_hero_title' => 'O Seu Cartao Digital',
    'prof_hero_title_highlight' => 'Configurado pela<br>Nossa Equipa Humana',
    'prof_hero_subtitle' => 'O Cartao Digital e a soma de TUDO: cartao em JPG para partilhar + site web + gestor de clientes + email marketing + assistente virtual. A nossa equipa humana configura TUDO por si. Voce apenas envia a sua informacao e pronto.',
    'prof_hero_url_ejemplo' => 'O seu URL personalizado:',
    'prof_hero_url_ejemplo_subdomain' => 'seunome',
    'prof_hero_url_ejemplo_domain' => '.verumax.com',
    'prof_cta_empezar' => 'Ver Planos e Criar o Meu Cartao',
    'prof_cta_secundario' => 'Ver Como Funciona',

    // Secao Hero - Estatisticas
    'prof_stat_qr' => 'Equipa Humana',
    'prof_stat_qr_desc' => 'Nos configuramos tudo',
    'prof_stat_actualizacion' => 'Dashboard Incluido',
    'prof_stat_actualizacion_desc' => 'Para autogerir quando quiser',
    'prof_stat_landing' => 'Solucao Completa',
    'prof_stat_landing_desc' => 'Cartao + Web + Ferramentas',

    // Secao: O que e o Cartao Digital?
    'prof_que_es_titulo' => 'O que e o Cartao Digital?',
    'prof_que_es_subtitulo' => 'A soma de TUDO o que precisa para a sua presenca digital',
    'prof_que_es_desc' => 'O Cartao Digital NAO e apenas um cartao. E a SOMA de multiplos servicos num so: 1 O seu cartao fisico em formato JPG com QR infalsificavel para partilhar ou imprimir 2 O seu site web (seunome.verumax.com) 3 Gestor de clientes/contactos 4 Sistema de email marketing 5 Assistente virtual especializado 24/7. Tudo isto e configurado por NOS. Uma equipa humana real monta a sua presenca digital completa. Voce apenas nos envia a sua informacao (foto, servicos, horarios) e nos fazemos TODO o trabalho tecnico. Tambem tem acesso a um dashboard para autogerir quando quiser, mas nunca e obrigatorio usa-lo.',

    'prof_tarjeta_feature1_titulo' => '1 O Seu Cartao Fisico Digital',
    'prof_tarjeta_feature1_desc' => 'Imagem JPG em alta resolucao com o seu design profissional e QR infalsificavel. Partilhe por WhatsApp, email, LinkedIn ou imprima em papel. Substitui os cartoes de papel tradicionais.',
    'prof_tarjeta_feature2_titulo' => '2 O Seu Site Web Profissional Completo',
    'prof_tarjeta_feature2_desc' => 'Dominio personalizado (seunome.verumax.com) com design profissional, portfolio, servicos, horarios, formulario de contacto. Nao e apenas uma landing, e o seu site web completo configurado pela nossa equipa.',
    'prof_tarjeta_feature3_titulo' => '3 Ferramentas de Gestao Incluidas',
    'prof_tarjeta_feature3_desc' => 'Gestor de clientes + Email marketing + Rececionista Virtual Especializado. Tudo integrado e a funcionar. Sao servicos que habitualmente contrataria separadamente.',
    'prof_tarjeta_feature4_titulo' => '4 Equipa Humana + Dashboard Opcional',
    'prof_tarjeta_feature4_desc' => 'Nos configuramos TUDO por si. Uma equipa humana real encarrega-se de montar a sua presenca digital completa. Tambem tem acesso a um dashboard para fazer alteracoes quando quiser, mas pode sempre pedir-nos ajuda.',

    // Secao: Como Funciona
    'prof_como_titulo' => 'Como Funciona em 3 Simples Passos',
    'prof_como_subtitulo' => 'Nos fazemos TODO o trabalho tecnico por si',
    'prof_como_paso1' => 'Passo 1: Escolhe o seu Plano e Envia a sua Info',
    'prof_como_paso1_desc' => 'Seleciona o plano que melhor se adapta a si e envia-nos a sua informacao: nome, foto, servicos que oferece, horarios, contacto. Nada mais. Nao tem de mexer em nada tecnico.',
    'prof_como_paso2' => 'Passo 2: A Nossa Equipa Configura TUDO',
    'prof_como_paso2_desc' => 'Uma equipa humana REAL monta o seu site web completo, desenha o seu cartao digital, configura as suas ferramentas (gestor de clientes, email marketing, assistente virtual). Voce nao faz nada. Nos fazemos TODO o trabalho tecnico.',
    'prof_como_paso3' => 'Passo 3: Comeca a Usar Tudo Ja a Funcionar',
    'prof_como_paso3_desc' => 'Recebe o seu cartao para partilhar, o seu site web ja online, e todas as ferramentas configuradas e prontas. Pode usar o dashboard para fazer alteracoes por si mesmo, ou simplesmente escrever-nos e nos fazemos por si. Tera sempre suporte humano real.',

    // Secao: Caracteristicas Estrela
    'prof_caracteristicas_titulo' => 'Porque Escolher o Nosso Cartao Digital',
    'prof_caracteristicas_subtitulo' => 'Nao e apenas um cartao, e a sua solucao profissional completa com equipa humana incluida',

    'prof_caract_qr_titulo' => 'Equipa Humana que Faz Tudo por Si',
    'prof_caract_qr_desc' => 'Nao o deixamos sozinho com um software. Uma equipa humana REAL configura o seu site web, desenha o seu cartao, carrega a sua informacao, e da-lhe suporte permanente. Pode usar o dashboard se quiser, ou simplesmente escrever-nos e nos fazemos as alteracoes. Ha sempre pessoas reais por tras.',
    'prof_caract_panel_titulo' => 'A Soma de Multiplos Servicos num So',
    'prof_caract_panel_desc' => 'Nao compra apenas um cartao. Compra: cartao digital + site web completo + gestor de clientes + email marketing + assistente virtual. Sao ferramentas que habitualmente contrataria separadamente em diferentes plataformas. Aqui estao todas integradas e a funcionar.',
    'prof_caract_paletas_titulo' => 'Dashboard Incluido mas Opcional',
    'prof_caract_paletas_desc' => 'Tem acesso a um painel de administracao para fazer alteracoes por si mesmo quando quiser: atualizar foto, modificar horarios, adicionar servicos. Mas NUNCA e obrigatorio usa-lo. Pode sempre pedir-nos que o facamos nos. O dashboard e uma opcao, nao uma obrigacao.',
    'prof_caract_landing_titulo' => 'Site Web Profissional Completo',
    'prof_caract_landing_desc' => 'Nao e apenas uma "landing page". E o seu site web profissional completo (seunome.verumax.com) com portfolio, servicos detalhados, formulario de contacto, informacao de horarios. Tudo otimizado para dispositivos moveis e configurado pela nossa equipa.',
    'prof_caract_formatos_titulo' => 'A Sua Presenca Digital Necessaria Hoje',
    'prof_caract_formatos_desc' => 'Ter presenca na internet ja nao e opcional. E necessario. O Cartao Digital da-lhe TUDO o que precisa: cartao para partilhar + site web profissional + ferramentas de gestao. Tudo num so produto, configurado e pronto a usar.',
    'prof_caract_seguridad_titulo' => 'Suporte Humano Permanente',
    'prof_caract_seguridad_desc' => 'Nunca fica sozinho. Ha sempre pessoas reais do outro lado para ajuda-lo. Quer alterar algo? Escreva-nos. Nao sabe como usar uma ferramenta? Explicamos-lhe. Precisa de adicionar conteudo? Fazemos por si. Suporte humano real, nao chatbots.',

    // Secao: Casos de Uso
    'prof_casos_titulo' => 'Para Quem e o Cartao Digital?',
    'prof_casos_subtitulo' => 'Profissionais de todas as industrias que valorizam a primeira impressao',

    'prof_caso_abogados' => 'Advogados e Advogadas e Consultores e Consultoras',
    'prof_caso_abogados_desc' => 'Entregue o seu cartao com QR aos seus clientes. Eles digitalizam e acedem as suas areas de pratica, horarios de atendimento e formulario de consulta.',
    'prof_caso_medicos' => 'Medicos e Medicas e Profissionais de Saude',
    'prof_caso_medicos_desc' => 'O seu cartao com especialidades, horarios de consultorio, seguros de saude que aceita e botao direto para agendar consultas.',
    'prof_caso_arquitectos' => 'Arquitetos e Arquitetas e Designers',
    'prof_caso_arquitectos_desc' => 'Partilhe o seu cartao e deixe os seus potenciais clientes verem o seu portfolio visual no seu site web personalizado.',
    'prof_caso_comercios' => 'Comercios e Empreendedores e Empreendedoras',
    'prof_caso_comercios_desc' => 'O seu cartao comercial com horarios, localizacao, catalogo de produtos/servicos e botao de WhatsApp para consultas.',
    'prof_caso_coaches' => 'Coaches e Formadores e Formadoras',
    'prof_caso_coaches_desc' => 'Mostre os seus servicos, testemunhos, e permita aos seus clientes agendar sessoes diretamente a partir do seu site.',
    'prof_caso_freelancers' => 'Freelancers e Criativos e Criativas',
    'prof_caso_freelancers_desc' => 'O seu cartao digital com links para o seu portfolio, redes sociais e tarifas. Impressao profissional garantida.',
    'prof_caso_productores' => 'Produtores e Produtoras de Alimentos',
    'prof_caso_productores_desc' => 'Partilhe o seu cartao com certificacoes de qualidade, rastreabilidade de produtos e catalogo. O QR leva os seus clientes a toda a sua informacao verificada.',
    'prof_caso_artesanos' => 'Artesaos e Artesas e Trabalhos Manuais',
    'prof_caso_artesanos_desc' => 'Mostre o seu trabalho artesanal com galeria de fotos, precos e contacto direto. Perfeito para feiras, mercados e clientes particulares.',
    'prof_caso_trainers' => 'Personal Trainers e Nutricionistas',
    'prof_caso_trainers_desc' => 'O seu cartao com especialidades, planos disponiveis, horarios e sistema de agendamento. Os seus clientes reservam consultas diretamente a partir do seu site.',

    // Secao: Planos e Precos
    'prof_planes_titulo' => 'Escolha o Plano que Melhor se Adapta a Si',
    'prof_planes_subtitulo' => 'Todos os planos incluem configuracao por equipa humana + suporte permanente + painel de autoadministracao',
    'prof_planes_promo' => 'PROMOCAO DE LANCAMENTO',
    'prof_planes_alta_texto' => 'Ativacao bonificada:',
    'prof_planes_descuento' => '50% DE DESCONTO - Apenas por tempo limitado',

    'prof_plan_esencial_titulo' => 'Essentialis',
    'prof_plan_esencial_desc' => 'A sua presenca digital profissional completa. Nos configuramos tudo por si.',
    'prof_plan_esencial_precio' => '9 USD',
    'prof_plan_esencial_periodo' => '/ Anual',
    'prof_plan_esencial_feat1' => 'Cartao Digital JPG com QR Infalsificavel',
    'prof_plan_esencial_feat2' => 'Site Web Personalizado (seunome.verumax.com)',
    'prof_plan_esencial_feat3' => 'Portfolio de Projetos (ate 20 imagens)',
    'prof_plan_esencial_feat4' => 'Secao de Servicos Detalhada',
    'prof_plan_esencial_feat5' => 'Formulario de Contacto Integrado',
    'prof_plan_esencial_feat6' => 'Gestor de Clientes (ate 20 contactos)',
    'prof_plan_esencial_feat7' => 'Email Marketing (100 emails/mes)',
    'prof_plan_esencial_feat8' => 'Rececionista Virtual Especializado (10 consultas/dia)',
    'prof_plan_esencial_feat9' => 'Sistema de Agendamento de Consultas',
    'prof_plan_esencial_feat10' => 'Configuracao por Equipa Humana',
    'prof_plan_esencial_feat11' => 'Painel de Autoadministracao Incluido',
    'prof_plan_esencial_cta' => 'Comecar com Essentialis',

    'prof_plan_plus_badge' => 'Mais Popular',
    'prof_plan_plus_titulo' => 'Premium',
    'prof_plan_plus_desc' => 'Tudo do Essentialis com limites ampliados e ferramentas profissionais avancadas.',
    'prof_plan_plus_precio' => '19 USD',
    'prof_plan_plus_periodo' => '/ Anual',
    'prof_plan_plus_feat1_strong' => 'Tudo do plano Essentialis, mais:',
    'prof_plan_plus_feat2' => 'Portfolio Ampliado (ate 100 imagens)',
    'prof_plan_plus_feat3' => 'Gestor de Clientes (ate 100 contactos)',
    'prof_plan_plus_feat4' => 'Email Marketing (1.000 emails/mes)',
    'prof_plan_plus_feat5' => 'Rececionista Virtual Especializado (50 consultas/dia)',
    'prof_plan_plus_feat6' => 'Video de Apresentacao Pessoal',
    'prof_plan_plus_feat7' => 'Estatisticas Avancadas de Leituras QR',
    'prof_plan_plus_feat8' => 'Gerador de CV Inteligente (PDF e Web)',
    'prof_plan_plus_feat9' => 'Sistema de Agendamento de Consultas',
    'prof_plan_plus_feat10' => 'Integracao com Credenciais Verificadas',
    'prof_plan_plus_cta' => 'Obter Plano Premium',

    'prof_plan_pro_badge' => 'Profissional',
    'prof_plan_pro_titulo' => 'Excellens',
    'prof_plan_pro_desc' => 'Solucao profissional completa com ferramentas de gestao empresarial e presenca digital ampliada.',
    'prof_plan_pro_precio' => '49 USD',
    'prof_plan_pro_periodo' => '/ Anual',
    'prof_plan_pro_feat1_strong' => 'Tudo do plano Premium, mais:',
    'prof_plan_pro_feat2' => 'Portfolio Empresarial (ate 500 imagens)',
    'prof_plan_pro_feat3' => 'Gestor de Clientes (ate 1.000 contactos)',
    'prof_plan_pro_feat4' => 'Email Marketing (5.000 emails/mes)',
    'prof_plan_pro_feat5' => 'Rececionista Virtual Especializado (100 consultas/dia)',
    'prof_plan_pro_feat6' => 'Multiplas Paginas Personalizadas',
    'prof_plan_pro_feat7' => 'Analiticas Avancadas e Relatorios Detalhados',
    'prof_plan_pro_feat8' => 'Integracoes API Personalizadas',
    'prof_plan_pro_feat9' => 'Suporte Prioritario 24/7',
    'prof_plan_pro_cta' => 'Obter Plano Excellens',

    'prof_plan_elite_badge' => 'Empresarial',
    'prof_plan_elite_titulo' => 'Supremus',
    'prof_plan_elite_desc' => 'A solucao empresarial definitiva com recursos ampliados, dominio proprio e personalizacao total.',
    'prof_plan_elite_precio' => '99 USD',
    'prof_plan_elite_periodo' => '/ Anual',
    'prof_plan_elite_feat1_strong' => 'Tudo do plano Excellens, mais:',
    'prof_plan_elite_feat2' => 'Portfolio Corporativo (ate 2000 imagens)',
    'prof_plan_elite_feat3' => 'Gestor de Clientes (ate 5.000 contactos)',
    'prof_plan_elite_feat4' => 'Email Marketing (10.000 emails/mes)',
    'prof_plan_elite_feat5' => 'Rececionista Virtual Especializado (1.000 consultas/dia)',
    'prof_plan_elite_feat6' => 'Dominio Proprio Incluido (seunome.com)',
    'prof_plan_elite_feat7' => 'Design 100% Personalizado a Medida',
    'prof_plan_elite_feat8' => 'Subdominios Ilimitados para a Sua Equipa',
    'prof_plan_elite_feat9' => 'Sistema de Funcoes e Permissoes Avancado',
    'prof_plan_elite_feat10' => 'Gestor de Conta Dedicado',
    'prof_plan_elite_cta' => 'Obter Plano Supremus',

    // Secao: Planos Academicos (Certificatum)
    'acad_planes_titulo' => 'Planos Educativos',
    'acad_planes_subtitulo' => 'Todos os planos incluem Cartao Digital orientado a certificados + configuracao completa + suporte permanente',

    // Plan Singularis (Pagamento por Certificado)
    'acad_plan_singularis_titulo' => 'Singularis',
    'acad_plan_singularis_desc' => 'Ideal para uso ocasional ou testes. Pague apenas pelo que emite.',
    'acad_plan_singularis_precio_label' => 'por certificado',
    'acad_plan_singularis_feat1' => 'Sem subscricao nem compromisso',
    'acad_plan_singularis_feat2' => 'Pague apenas quando emitir',
    'acad_plan_singularis_feat3' => 'Certificados com QR verificavel',
    'acad_plan_singularis_feat4' => 'Validacao instantanea',
    'acad_plan_singularis_feat5' => 'Portal publico de validacao',
    'acad_plan_singularis_cta' => 'Comecar sem subscricao',

    // Planos - Geral
    'acad_plan_pago_mensual' => 'Pagamento mensal',

    // Plan Essentialis
    'acad_plan_essentialis_titulo' => 'Essentialis',
    'acad_plan_essentialis_desc' => 'Ideal para instituicoes pequenas e formadores e formadoras independentes',
    'acad_plan_essentialis_feat1' => '10 Certificados Digitais/mes',
    'acad_plan_essentialis_feat2' => 'Emissao Massiva de Certificados (CSV/Excel)',
    'acad_plan_essentialis_feat3' => 'Cartao Digital Institucional com QR',
    'acad_plan_essentialis_feat4' => 'Site Web Institucional (instituicao.verumax.com)',
    'acad_plan_essentialis_feat5' => 'Validacao QR Infalsificavel',
    'acad_plan_essentialis_feat6' => 'Portal do Estudante Basico',
    'acad_plan_essentialis_feat7' => 'Identidade Visual Institucional Personalizada',
    'acad_plan_essentialis_feat8' => 'Notificacoes Automaticas por Email',
    'acad_plan_essentialis_feat9' => 'Painel de Administracao Incluido',
    'acad_plan_essentialis_feat10' => 'Configuracao por Equipa Humana',
    'acad_plan_essentialis_cta' => 'Comecar com Essentialis',

    'acad_plan_premium_badge' => 'Mais Popular',
    'acad_plan_premium_titulo' => 'Premium',
    'acad_plan_premium_desc' => 'A escolha ideal para centros de formacao em crescimento',
    'acad_plan_premium_feat1_strong' => 'TUDO do Essentialis +',
    'acad_plan_premium_feat2' => '100 Certificados Digitais/mes',
    'acad_plan_premium_feat3' => 'Historico Academico Completo',
    'acad_plan_premium_feat4' => 'Linha de Tempo de Trajetoria Estudantil',
    'acad_plan_premium_feat5' => 'Gestao de Turmas e Comissoes',
    'acad_plan_premium_cta' => 'Solicitar Plano Premium',

    'acad_plan_excellens_titulo' => 'Excellens',
    'acad_plan_excellens_desc' => 'Para universidades e grandes instituicoes educativas',
    'acad_plan_excellens_feat1_strong' => 'TUDO do Premium +',
    'acad_plan_excellens_feat2' => '1000 Certificados Digitais/mes',
    'acad_plan_excellens_feat3' => 'Sistema Multi-Sede (ate 5 sedes)',
    'acad_plan_excellens_feat4' => 'Funcoes e Permissoes Avancadas',
    'acad_plan_excellens_feat5' => 'Integracao com Moodle/Canvas/Blackboard',
    'acad_plan_excellens_feat6' => 'API REST Completa para Programadores',
    'acad_plan_excellens_feat7' => 'Dominio Personalizado (.edu.pt / .com)',
    'acad_plan_excellens_cta' => 'Solicitar Plano Excellens',

    'acad_plan_supremus_titulo' => 'Supremus',
    'acad_plan_supremus_desc' => 'Solucao enterprise para redes educativas e ministerios',
    'acad_plan_supremus_feat1_strong' => 'TUDO do Excellens +',
    'acad_plan_supremus_feat2' => 'Certificados, Certificados e Diplomas ILIMITADOS',
    'acad_plan_supremus_feat3' => 'Multi-Instituicao (Redes Educativas)',
    'acad_plan_supremus_feat4' => 'Sistema Multi-Sede Ilimitado',
    'acad_plan_supremus_feat5' => 'Blockchain para Registo Permanente',
    'acad_plan_supremus_feat6' => 'Design 100% Personalizado a Medida',
    'acad_plan_supremus_feat7' => 'Subdominios Ilimitados por Curso/Faculdade',
    'acad_plan_supremus_feat8' => 'Gestor de Conta Educativo Dedicado',
    'acad_plan_supremus_cta' => 'Contactar para Plano Supremus',

    // Secao: CTA Final
    'prof_cta_final_titulo' => 'A Sua Presenca Digital Completa, Configurada por Nos',
    'prof_cta_final_desc' => 'Nao o deixamos sozinho com um software. Uma equipa humana real configura TUDO por si: cartao + site web + ferramentas. Voce apenas envia a sua info e pronto.',
    'prof_cta_final_btn' => 'Ver Planos e Criar o Meu Cartao Digital',
    'prof_cta_final_garantia' => 'Equipa humana real incluida  Dashboard opcional, nao obrigatorio  Suporte permanente',

    // Secao: Formas de Pagamento
    'prof_pagos_titulo' => 'Formas de Pagamento',
    'prof_pagos_subtitulo' => 'Metodos seguros e convenientes para o seu pais',
    'prof_pagos_argentina' => 'Metodos de Pagamento na Argentina',
    'prof_pagos_internacional' => 'Pagamento Internacional',
    'prof_pago_mercadopago' => 'MercadoPago',
    'prof_pago_mercadopago_desc' => 'Cartao de credito, debito e numerario',
    'prof_pago_pagofacil' => 'PagoFacil',
    'prof_pago_pagofacil_desc' => 'Pagamento em numerario em qualquer balcao',
    'prof_pago_transferencia' => 'Transferencia Bancaria',
    'prof_pago_transferencia_desc' => 'IBAN para euros',
    'prof_pago_paypal' => 'PayPal',
    'prof_pago_paypal_desc' => 'Cartoes e moeda local em todo o mundo',

    // ===== PAGINA MUTUAS =====

    // Meta Tags
    'mut_meta_title' => 'Verumax para Mutuas - Gestao Digital Integral',
    'mut_meta_description' => 'Solucao completa para mutuas e associacoes mutualistas. Credenciais digitais, gestao de beneficios, portal do associado e da associada e comunicacao comunitaria.',
    'mut_meta_keywords' => 'mutuas, associacoes mutualistas, credenciais digitais, gestao de associados, beneficios mutuais',

    // Navigation
    'mut_nav_beneficios' => 'Beneficios',
    'mut_nav_pilares' => 'Pilares',
    'mut_nav_planes' => 'Planos',
    'mut_nav_faq' => 'FAQ',
    'mut_nav_mutuales' => 'Mutuas',

    // Hero Section
    'mut_hero_badge' => 'Solucao Integral para Mutuas',
    'mut_hero_title' => 'Gestao Digital',
    'mut_hero_title_highlight' => 'para Mutuas',
    'mut_hero_subtitle' => 'Um ecossistema completo para modernizar a gestao, potenciar os beneficios e fortalecer o sentido de comunidade da sua mutua',
    'mut_cta_solicitar_demo' => 'Solicitar Demonstracao Personalizada',
    'mut_cta_ver_como_funciona' => 'Ver Como Funciona',

    // Hero Stats
    'mut_hero_stat_tiempo' => 'Menos tempo administrativo',
    'mut_hero_stat_portal' => 'Portal do associado e da associada 24/7',
    'mut_hero_stat_beneficios' => 'Gestao de beneficios em tempo real',

    // Problemas Section
    'mut_problemas_titulo' => 'Soa familiar?',
    'mut_problemas_subtitulo' => 'Os desafios que enfrentam as mutuas tradicionais',
    'mut_problema_credenciales' => 'Credenciais de Plastico Obsoletas',
    'mut_problema_credenciales_desc' => 'Custos de impressao, extravios constantes e dificuldade para verificar o estado do associado ou da associada.',
    'mut_problema_beneficios' => 'Gestao Manual de Beneficios',
    'mut_problema_beneficios_desc' => 'Cupoes de papel, fraudes por dupla utilizacao e comercios que nao conseguem verificar descontos.',
    'mut_problema_comunicacion' => 'Comunicacao Ineficiente',
    'mut_problema_comunicacion_desc' => 'Emails que nao sao lidos, quadros fisicos desatualizados e dificuldade para chegar a todos os associados e a todas as associadas.',
    'mut_problema_participacion' => 'Baixa Participacao em Assembleias',
    'mut_problema_participacion_desc' => 'Controlo manual de quorum, listagens em papel e falta de ferramentas para fomentar a participacao.',
    'mut_problema_crecimiento' => 'Gestao Administrativa Complexa',
    'mut_problema_crecimiento_desc' => 'Folhas de calculo Excel, falta de rastreabilidade e dificuldade para gerar relatorios.',
    'mut_problema_imagen' => 'Imagem Antiquada',
    'mut_problema_imagen_desc' => 'Dificuldade para atrair novos associados e novas associadas jovens com processos tradicionais e sem presenca digital.',
];
?>
